### ISSUE TITLE
Turn a Collection from Guardian to Open at anytime after the collection is live.

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#1000]
### Discussed in https://github.com/soonaverse/soonaverse-dao/discussions/999

<div type='discussions-op-text'>

<sup>Originally posted by **wiredutch** January  2, 2023</sup>
Collections

Being able to turn the Collection from Guardian to Open at anytime after the collection is live.

</div>

This should be allowed for collection that has not been minted or minted.

**Comment by adamunchained** [comment]
@boldizsar-unchained - please assign this back to me after you complete this. We'll need to tweak front-end. Thanks

**Comment by boldizsar-unchained** [comment]
Maybe not UI, but this issue #2029
Fixed here https://github.com/soonaverse/soonaverse/pull/2032
