### ISSUE TITLE
Staking Level Dark Theme Highlight is not dark enough

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#1001]
Can we make the highlight for staking a bit more dark theme-ish. The Column Title is not adjusted for dark theme as well

<img width="988" alt="image" src="https://user-images.githubusercontent.com/44786846/210878648-9ff90a06-c297-48c1-bc41-dc6bddb32105.png">

Maybe more like this (excuse the numbers not being visible) but please use whatever looks best!
![image](https://user-images.githubusercontent.com/44786846/210879203-7fa2d5f7-9325-4cd4-a584-e33b4e4d6137.png)

**Comment by humaint** [comment]
already fixed in 1960 branch. waiting for release
