### ISSUE TITLE
Trying to create a token 'Data can not be encoded in JSON: NaN'

### ISSUE THREAD

**Issue by Bambi666** [soonaverse/soonaverse-dao#1003]
Hello everyone,

I tried to create a token on Soonaverse launchpad. After filling out everything and clicking 'Submit token' on the last page, I give my signature and always end up with error code 'Data can not be encoded in JSON: NaN'. Token wasn't created :(

1. Create -> Token
2. Fill everything out and continue to last page.
3. Press submit token and sign MM.
4. Error code 'Data can not be encoded in JSON: NaN' show up in top right corner

**Expected behavior**
Token should have been created.

**Screenshots**
[https://ibb.co/9YtwYK3](url)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Firefox, Microsoft Edge, Opera

Thanks in advance!

**Comment by Bambi666** [comment]
I also tried to empty cookies& cache as well as history and tried on another computer. Still the same issue!

**Comment by CptBananu** [comment]
For devs:

Allocation percentage adds up to 100% (so correct)

Max supply is 69,420,666 tokens

Price is 0.00666 (maybe that's the cause?)

**Comment by Bambi666** [comment]
Found out we used , instead of .   .......no comment :p

**Comment by adamunchained** [comment]
yeah unfortunately it's a localization issue.
