### ISSUE TITLE
People could erroneously expect MXT / Soon rewards for staking.

### ISSUE THREAD

**Issue by mexaverso** [soonaverse/soonaverse-dao#1007]
Please see this video of the prompts shown after clicking the staking button and tell me if it could not cause rewards expectations.
There shall be a clear message that NO REWARDS are offered (for now).
Thanks.
https://watch.screencastify.com/v/vAmYdwTYijl1OfcXdh1D

**Comment by adamunchained** [comment]
@humaint - see brach https://github.com/soonaverse/soonaverse/tree/feat/1007 I've hidden the last sentence if it's not SOON token.

Can you please add warning for non SOON staking?

"Please make sure you understand benefits you will receive by staking, if any.".
Or you think we don't have to add this sentence?

**Comment by adamunchained** [comment]
I've hide the link to SOON rewards. 

In the next release we can think about improving the flow based on further feedback. 

@humaint - please have think about this.

**Comment by mexaverso** [comment]
Hi. Thanks for unlinking to soon rewards page. Now: ¿What benefits do MXT stakers have at all? MXT staking is being unilaterally offered by Soonaverse without explaining me (the space) what can I offer for now. ¿DAO voting? thanks.
