### ISSUE TITLE
Payments stuck in 'Processing'

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1010]
A transaction on Jan 16 2023 and a transaction on April 15 2022 are stuck in 'Processing' for the user. No tx given by Soonaverse.

https://soonaverse.com/member/0x4bdea1ceb9f480d6116b3d12855554b382d33692/transactions

**Comment by adamunchained** [comment]
@boldizsar-unchained - can you check please?

**Comment by adamunchained** [comment]
It's this credit: 0xb7b66036675a4e21ddc59a0a91371308cc391fd5

**Comment by boldizsar-unchained** [comment]
@adamunchained The one on April 15 (0x7ee38496beddf4215f67a1b705ad9ce1fb39bc44) is a royalty payment and it was successful, see https://explorer.iota.org/mainnet/message/1a7f07efbf4c54c39d87d663f7649bb16e7506dd477cdcebe73d1e19c9c98c75

For the one on Jan 16 see my related PR.
