### ISSUE TITLE
Multiple public sales before tradable on open market

### ISSUE THREAD

**Issue by AdrienAO** [soonaverse/soonaverse-dao#1012]
**Describe the bug**
Token Launchpad: We would like to create a token, and have 2 public sales. After the first one, the token should not be tradable on the open market. Prices for both sales should be different. Second sale after X month and then it could be tradable on open market.

**To Reproduce**
1. Go to 'Create Token'

**Expected behavior**

Public Sale 1 Allocation:
Public Sale 2 Allocation:

Time between Public Sale 1 & 2 in months (or to be set manually)

Token to be tradable yet: Y/N

**Comment by adamunchained** [comment]
Just to clarify, we only support one public sale via our platform. Second sale would have to be another token. Your second token could be the final token and you airdrop tokens from previous sales.

**Comment by adamunchained** [comment]
@boldizsar-unchained - please let's introduce a flag (editable by guardian) to disable trading of token on Soonaverse.

**Comment by adamunchained** [comment]
@AdrienAO - we now enabled support to disable trading of token. This can only be disabled when you're creating tokens and enabled later. It's supported on the back-end for now only. Once you create a token let us know and we will disable token trading for it so you don't have to wait for UI update.
