### ISSUE TITLE
User given IOTA address to send SMR to

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1017]
User was using the exchange to purchase miota with SMR, but the address provided for them to send their payment to is an IOTA address.

![Trading](https://user-images.githubusercontent.com/38050901/213811067-9e8bb052-609c-4292-aa60-8243bde98b31.JPG)

**Comment by adamunchained** [comment]
fixed and will be in prod in next 10 minutes
