### ISSUE TITLE
NFT isn't locked during the transaction window

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1018]
Initiating the transaction window does not prevent the price from changing during the transaction. One user's example:

NFT:
https://soonaverse.com/nft/0xea656b3aa875d5bf362c6bba7b4967fb22aafb7e

![image-7](https://user-images.githubusercontent.com/38050901/213812528-3fa5560f-0054-4f4f-8e37-a25ebe1ca2dd.png)
![image-8](https://user-images.githubusercontent.com/38050901/213812602-199a3adc-1623-4a02-b569-aa757a74f9c1.png)

**Comment by adamunchained** [comment]
Are you saying that you expect price to refresh if they change it during transaction?

**Comment by SeanTMartin** [comment]
Currently, it DOES refresh the price if they change it during the transaction, as pictured above. We thought that it the price would be locked as soon as the transaction started, but it was not locked and the price changed during the transaction.

**Comment by adamunchained** [comment]
Did you try to pay the previous amount? I think the issue is that we show refreshed price (UI bug) but they would actually have to pay the original price.

Could you try please?

**Comment by SeanTMartin** [comment]
Tested this behavior. Paying the refreshed price does not work, just like you said. Purchasing at the original price works.
