### ISSUE TITLE
Error when creating proposal

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1023]
User is getting an error trying to create a proposal. This is the message:

Validation failed: [{"message":"\"settings.awards\" is not allowed","path":["settings","awards"],"type":"any.unknown","context":{"label":"settings.awards","value":[],"key":"awards"}}]

**Comment by adamunchained** [comment]
This has been fixed in prod. We've had been improving some params validation on the backend due OTR and it broke some UI functions that didn't properly construct requests.
