### ISSUE TITLE
Price not correctly sorted for NFTs

### ISSUE THREAD

**Issue by whatmicha** [soonaverse/soonaverse-dao#1026]
**Describe the bug**
If I'm choosing to sort the bug by price from low > high it does not to this correctly. 
At least it sorts it from n to n+x correctly but n isn't the lowest price 
![image](https://user-images.githubusercontent.com/110422993/214690437-034ea9fd-05ba-459f-8a6b-fcf32f3b3e1d.png)
![image](https://user-images.githubusercontent.com/110422993/214690565-b3c3f71a-b289-410f-a6e7-4c5e78a4e624.png)

**To Reproduce**
1. Go to 'https://soonaverse.com/market/collections'
2. search for "Valid Scouts"

3. Click on 'Valid Scouts (if it is visible, sometimes also buggy... ) 
![image](https://user-images.githubusercontent.com/110422993/214691233-de1d9102-9421-4621-bb49-b18d080f7f4a.png)
'
4. look at prices for the first NFTs
5. click on low to high
6. See error
7. click on "newest" 
8. see error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 
Chrome

**Comment by adamunchained** [comment]
@whatmicha - can you provide more details? I can see NFTs are sorted correctly and search works (see attached video). Am I missing something?

https://user-images.githubusercontent.com/130610/214748824-3a0abf7d-d9cd-4429-8234-9856d1c60c0d.mov

**Comment by whatmicha** [comment]
Hi,

just uploading a video to show how it looks on my end.

https://user-images.githubusercontent.com/110422993/215351870-81dda36b-4160-4533-9a85-39a000187944.mp4

**Comment by adamunchained** [comment]
@whatmicha - I'm asking various ppl to test this as I can't still replicate this.

<img width="556" alt="Screenshot 2023-02-02 at 10 20 41 AM" src="https://user-images.githubusercontent.com/130610/216412795-42790d3e-2ef9-4556-80c8-421cb0d69566.png">

Just to confirm this happens to you every time?

**Comment by adamunchained** [comment]
Unable to reproduce by multiple parties, please re-open if you're able to do so and provide steps to reproduce.
