### ISSUE TITLE
NFT collection stuck in Shimmer migration

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1032]
Hello,

discord member "Iart Lamb#6377" reported that their NFT collection (https://soonaverse.com/nft/0x39015e6a9c84b7058b6bcc7ca09053ba6cc7e1cc) is stuck in migration to shimmer network since january 26th.

Could u pls check if there is an issue? Collection is relatively small so IPFS congestion seems unlikely to me.

Thx in advance

**Comment by adamunchained** [comment]
We have marked it for reprocessing and it has now finished.
