### ISSUE TITLE
Sorting filter issue

### ISSUE THREAD

**Issue by guhyeonjeong** [soonaverse/soonaverse-dao#1033]
**Describe the bug**
not properly sorted when 'Recently created' and 'On Sale' options are selected

**To Reproduce**
1. Go to '[soonaverse.com/collection](https://soonaverse.com/collection/0x021b5b27ead6ec003ba8f1b605f853a5baf9a803)'
2. Click on 'Recently created' and 'On Sale' on the Filters&Sort menu
4. some NFTs which should have been filtered out could be displayed

**Expected behavior**
properly filtered out

**Screenshots**
![image](https://user-images.githubusercontent.com/3461814/215940676-e4a36659-110d-4254-befc-abaa4f477f4b.png)

**Desktop (please complete the following information):**
 - OS: macOS (13.1)
 - Browser chrome (109.0.5414.119)

**Comment by adamunchained** [comment]
This was fixed. One of the NFT was out of sync within the search engine.
