### ISSUE TITLE
Different search results based on Mobile vs. Desktop

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1035]
Different results come up from the search depending on if I use mobile or desktop.
![image](https://user-images.githubusercontent.com/38050901/216449156-6a9315d1-fd90-47b4-b5ff-fb9fbad54fa4.png)

![image](https://user-images.githubusercontent.com/38050901/216449193-6b58ac7f-7d66-40ea-9430-adf709119b17.png)

**Comment by SeanTMartin** [comment]
Here is an example of a user that shows up on desktop but not mobile.

https://soonaverse.com/member/0x961ec61dae3fefb7d365bfaa557978bedd6a61bf/activity

**Comment by adamunchained** [comment]
we must migrate search within space to use Algolia search

**Comment by adamunchained** [comment]
will be fixed part of the https://github.com/soonaverse/soonaverse-dao/issues/943
