### ISSUE TITLE
Default language is switched to german and cant be changed to english

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#1036]
**Describe the bug**
I opened Soonaverse today, and strangely, the language in My Profile" is displayed in german (though i never used it in German Language.)
The language switcher shows it should be English. Switching to German and back to English does not change anything.
Mt default PC and Browswre language is set to English
Other sites are displayed in English though

**To Reproduce**

**Expected behavior**
Whole website should be in english

**Screenshots**
See video

https://user-images.githubusercontent.com/77154511/216896685-b3baaa79-7381-4ad2-b213-8b5405463f69.mp4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Win11
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] latest

**Additional context**

**Comment by adamunchained** [comment]
This language switch is an ongoing battle for out team:(

From which location do you currently access Soonaverse? I'm particularly after the country.

**Comment by Phyloiota** [comment]
Hmm okay, so i dont know if i was on a VPN yesterday.
Today i tried it and it works and comes up in English, accessing from Indonesia, or via VPN from german, both show up in English....

**Comment by adamunchained** [comment]
As per decision here: https://soonaverse.com/proposal/0x5b4fdba6db5ae2a079fd38528bbdda1388b38cef/overview

We will be switching only to english for now.
