### ISSUE TITLE
Creating collection - minimum one NFT from collection

### ISSUE THREAD

**Issue by ILLUMINATIOTA** [soonaverse/soonaverse-dao#1039]
When trying to create a collection and wanting to choose option: only available for owners of nft from collection the list is empty, no collections to choose from available.

1. Create a collection
2. Settings of collection. who has access to collection?
3. Minimum one NFT from collection X
4. No collections to choose from show up

**Comment by adamunchained** [comment]
There must be a bug in search. We'll fix it in upcoming release that will go out in about two weeks.

**Comment by adamunchained** [comment]
HI @ILLUMINATIOTA 

I've just tested and it seems to wrong. I was able to find collection. Please note you have to type value to show options. 

See my example:
<img width="528" alt="Screenshot 2023-02-09 at 1 20 46 PM" src="https://user-images.githubusercontent.com/130610/217941916-0ab2f428-d974-41a4-b50e-96057d7ba33c.png">

Feel free to re-open if it's still an issue

**Comment by ILLUMINATIOTA** [comment]
Thanks Adam, was a mistake on our side.
