### ISSUE TITLE
Order of my NFT's is messed up / makes no sense

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#1046]
**Describe the bug**
In "my Profile" the way my NFT's are displayed does not make any sense. It looks like it is just randomly ordered. No NFT' s from the same collection appear grouped or next to each other.
This makes it incredibly difficult to find an NFT>
I don't know why this has changed, but it was not like this till a few weeks ago.
Please implement a logical ordering, based on collections or artists, or even better implement a filter / order mechanism that allows me to decide how i want them to be ordered.

**To Reproduce**

**Expected behavior**
A logical approach that puts NFTs that belong together next to each other

**Screenshots**
![image](https://user-images.githubusercontent.com/77154511/218246366-dd798758-e802-45fd-a216-8ad807a09010.png)
![image](https://user-images.githubusercontent.com/77154511/218246379-5660f7bc-14ea-4123-a083-05c36d84406e.png)
![image](https://user-images.githubusercontent.com/77154511/218246387-a15972eb-c1c7-45bd-82f9-850e3b28cdff.png)

As you see in the screenshots, nearly no NFT is grouped next to another one from the same collection.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
Order has been changed in upcoming release to be SOLD ON DESC.

We'll create new issue to build filters on this page.

**Comment by Phyloiota** [comment]
Cool Adam, thx

**Comment by adamunchained** [comment]
@Phyloiota don't close this yet! It's not yet release, coming out this Friday:)
