### ISSUE TITLE
[TLP]: $PUNK Token must be linked to Soonaverse

### ISSUE THREAD

**Issue by IOTAPUNKS** [soonaverse/soonaverse-dao#1047]
### Email

mail@iotapunks.store

### Company Name

IOTAPUNKS

### Token Link

https://soonaverse.com/space/0x4dcfd426d4f47019fce9502bf484b51b19f84822/overview

### Your Position

CEO

### Name

IOTAPUNKS

### Have you already done a public sale?

No

### Files and other information

```shell
The IOTAPUNK Token ($PUNK) has been minted on Shimmer. Now a listing for Soonaverse has been requested. To enable a listing on Soonaverse the $PUNK Token must be linked to the Soonaverse Network. Here are all the necessary data. Thank you very much for your help!

Token-ID:
0x08b3420d742acfac6938c9334b2e3d0d9fa7b838c47d047914cbfd607c2549e22c0100000000

https://cdn.discordapp.com/attachments/1072065073587167293/1074741507946459219/image.png
```

**Comment by adamunchained** [comment]
You have to create the actual token under your space but you will not mint the token. Once created we will link that token to your token on Shimmer.

**Comment by adamunchained** [comment]
it's linked
