### ISSUE TITLE
Public voting filter deleted our voting public ranking at the right place 

### ISSUE THREAD

**Issue by priceactionbars** [soonaverse/soonaverse-dao#1050]
Yesterday we did a giveaway on our twitter.
One of the condition was to give a thumps up to our collection.👍🏼

First we ranked last in the public vote filter section because we had zero thumps up as you see in the printscreen i took👇🏼
![IMG_20230212_193211.png](https://user-images.githubusercontent.com/82802122/218807717-ec79b68b-0548-4127-9efb-9daec16c5fc5.png)

Once we had between 10-15likes from our collection IOTA robot club apes - season 1,game edition, we were ranking in the middle  as you see we took a printscreen. (we were ranked between tanglepay and lunar buddies collection) 👇🏼
![IMG_20230214_174706.jpg](https://user-images.githubusercontent.com/82802122/218807885-de456810-d9e3-4c00-b245-f3b304dbae3b.jpg)

During in the evening we had at some moment 59 likes reached (thumps up)👍🏼

We were ranked 3th in the public vote next to soonabot and shimmer doge. 

This morning, i looked again we had 26 thumps up instead 59 thumps up.

I scrolled down in the filter section to see if we were ranked in the same place as yesterday.
🤔

Unfortunatly we weren't ranked at the 4th place and neither in the middle but now in the end. 🥺

So my question is what's happened? 🥺Who deleted our  thumps ups likes and put us in the end of the ranking of the public voting filter. 

Why is this public vote not working properly for us, is there a bug? Isn't the data measured by thr amount thumps up in total?

 Even with 27 thumps up, we are not righteous ranked in the public voting filter section and yesterday we were 4th ranked! 🙂

Why are we suddenly ranked in the end and first in the middle of the public vote filter section or when had 57 thumps up almost in thr 3th place?. 

It seems us really unfair what happened. 
Can you have a look what happened and if yes adjust it back we're we belong the right place on the public voting rank. 🥺

Another issue i analysed is we had 1430 members yesterday on our space and this morning back to 1396? Is there any bug or something? These were the members that were last member of our space yesterday 👇🏼
![Screenshot_20230214_180009_com.android.gallery3d.jpg](https://user-images.githubusercontent.com/82802122/218808354-8e9f96cd-54b4-46d6-8a8f-6d9329c45278.jpg)

**Comment by adamunchained** [comment]
Are you sure ppl didn't just change their opinion? 

Also please note you got 41 down votes which drags your collection down:

<img width="465" alt="Screenshot 2023-02-14 at 9 35 27 AM" src="https://user-images.githubusercontent.com/130610/218814885-ad70bfea-5fe7-4891-8ccd-81aae5295ddb.png">

**Comment by adamunchained** [comment]
note, down votes are intentially hidden to the public. Only NFT Rank Moderators can see them.

**Comment by priceactionbars** [comment]
Oke we couldn't knew about the votes down, because it is not visible from our screen so we can't figure out how and why. 


How can we update ourselves how many votes down we have always, do we need always ask nft moderator or is this not allowed? We only see the votes up


Kind regards

**Comment by adamunchained** [comment]
You can query an API, see here for one of your collection: https://soonaverse.com/api/getById?uid=0xb7017cbe45809469cbc455a35e82b517231ba5a4&collection=collection

You can see parameter votes:

```"votes":{"downvotes":41,"voteDiff":-13,"upvotes":28}```
