### ISSUE TITLE
Add support for various decimals on the token (within UI)

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#1051]
Add support for various decimals on the token (within UI)

Right now we always show token with 6 decimals although there are various tokens that use different decimals.

UI should support various decimals and visualize token appropriately.

**Comment by IOTAPUNKS** [comment]
In fact each token can be configured differently when minted on Shimmer. $PUNK token for example has 10 digits in total, but no decimal places. But Shimmer allows 6 decimal places. Therefore we find it very important that each token can set the decimal places according to its own configuration. Thank you very much for this support and suggestion! :four_leaf_clover: :metal:

**Comment by DigiMine22** [comment]
We join and ask a UI conversion. Each project should be allowed to freely choose the number and decimal places as he considers correct and appropriate. We don't think it's right way to link just a token with 6 decimal places and a solution as a representation with many zeros after the decimal point only brings problems. Therefore we ask to provide the possibility to list tokens that have no decimal places. We thank you for your effort and support of the implementation.

**Comment by abhiraj136** [comment]
please fix this issue asap

**Comment by AT22SOD** [comment]
It's crucial that every token can set the number of decimal it uses, based on its own settings.

**Comment by adamunchained** [comment]
We'll try to expedite this.

**Comment by humaint** [comment]
@adamunchained not sure how to test

**Comment by adamunchained** [comment]
@humaint 

You can now create / import token that does not necessary have 6 decimals by default. 

Create a new token with various decimals (i.e. 0 or 2) and test the token across the system that token value shows correctly and equally as it would in Firefly or Tangle Explorer.

Please note I'm deploying one more fix I've found on various modals that are using tokens. It should be in wen2 within next 2 hours.

**Comment by adamunchained** [comment]
@IOTAPUNKS @DigiMine22 @abhiraj136 @A22NFT - this is now supported in production.

You can create a new token and set number of decimals. You can also create a new space and import token from the Shimmer. Go into the "manage" tab under the space (space without token).

If you already have an existing token record in Soonaverse, please let us know which one and we'll update number of decimals on it.

**Comment by IOTAPUNKS** [comment]
Great news, thank you!

**Comment by IOTAPUNKS** [comment]
Thank you for adding this feature!

Can you please set the number of Tokens back to the original number (2,520,266,667 Tokens) and initiate the listing from the $PUNK-Token.

https://soonaverse.com/token/0x70a484eb9ac89a197649b9b93e6db744fdf7b28a/overview

Thank you!
