### ISSUE TITLE
NFT discounts not up to date

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1054]
Hello guys,

I rhink there might be an issue with minting discounts bot being calcculated correctly (or too slow)

Discounts are:
> 4 XP = 5%  
> 9 XP = 10%  
> 14 XP = 15% 

How long does it ususally take from issuing an award (incl XP) till the user benefits from those XP regarding discount?

Buyers of Crypto Gins collection (https://soonaverse.com/collection/0x3a1030fcdf52f1b4da02c38a6da28848e0d65307) had multiple issues where they had enough XP for a discount but the price of the NFT didn't match. They had 10 XP but only got 5% (instead of 10%) discount.
Could it be that their XP was "too fresh" to be recognized bc something had to be fully processed first in the background? Some of those XP seem to have been issued shortly before the sale.

Cheers,
Bananu

**Comment by adamunchained** [comment]
@boldizsar-unchained - I believe this is related to https://github.com/soonaverse/soonaverse/issues/2197

**Comment by adamunchained** [comment]
@cptbananu - could you re-test this in new release please?

**Comment by adamunchained** [comment]
this was fixed part of the https://github.com/soonaverse/soonaverse/issues/2197
