### ISSUE TITLE
Little optical glitch in the sidebar

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#1055]
**Describe the bug**
Icons seem to be misaligned in the sidebar menu

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77154511/220835351-6e56cb8e-0220-4fe8-b344-47844902b442.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by humaint** [comment]
I can't reproduce this. @Phyloiota does the menu fold when browser thrinks like this:![SCR-20230329-iok.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/2653b80a-3b83-43ee-9ae5-0125902c126e)
