### ISSUE TITLE
NFT page keeps fetching the old version and it doesn't refresh until you reload browser.

### ISSUE THREAD

**Issue by celarium3945** [soonaverse/soonaverse-dao#1056]
**Describe the bug**
When navigate through soonaverse, NFT page are not up to date. It can be seen wen we change NFT price and come back to the page, the displayed price is the older one.

**To Reproduce**
as exemple Lendexe Tiere III. I got a NFT for sale 3600 (settler 4718) :
![image](https://user-images.githubusercontent.com/103221824/221349148-4fef3bdb-6e84-4d47-85dc-9e2c94592082.png)

now I change its price from 3600 to 3550
then I clic on lendexe space, colection and settler
my nft appear the same (3600)
even if I wait some minutes it did not change
now I change from price low to high -> available date ->price low to high  => the price of my NFT did not change (always 3600)
now I change from price low to high -> price high to low ->price low to high  => the price of my NFT did not change (always 3600)
if I go back to the main lendexe space, look at tier I and come back on Tier III : the price of my NFT did not change (always 3600)
I should reload the browser to get the right price displayed.
![image](https://user-images.githubusercontent.com/103221824/221349275-97bc7fff-66f0-41c2-ab52-112ab7249656.png)

**Expected behavior**
when price change, it should be displayed in few seconds without doeing anything. (no need to relaod browser)

**Desktop (please complete the following information):**
 - OS: Windows 11 Famille version 22h2
 - Browser : Microsoft Edge

**Comment by adamunchained** [comment]
@celarium3945 - we'll release a fix tonight that will disable local caching of the results. Can you please try again tomorrow if you're still experiencing the issue?

**Comment by celarium3945** [comment]
No more issue, it works well!! :)

**Comment by adamunchained** [comment]
Glad to hear that. thank you for reporting!
