### ISSUE TITLE
Mismatch of awards and related award-gated NFTs

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1057]
Hi guys,

it seems that some badges/awards changed their available amount upon the recent migration.
So far we have 2 cases:

1) IotaPunks:
Award: https://soonaverse.com/award/0xa918c9067aeb38373186eb4fbdd365421f5f355b/overview
Initial data: 500 badges à 10 XP
Current data: 74 badges à 5000 XP
![image](https://user-images.githubusercontent.com/104099536/221365502-5e7642f4-bfac-4bb7-be65-c0c912fd0054.png)

2) IotaMorons:
Award: https://soonaverse.com/award/0xeb7c955ad58416d521855cc767b6a1339a2c0aa5/overview
Initial data: 250 badges
Current data: 180 badges
![image](https://user-images.githubusercontent.com/104099536/221365624-02aa637f-e21c-4458-9f51-bb39eb1349fb.png)

Second case isn't about the XP but about the number of awards (180) tied to a number of RWAs (222 Moron t-shirts) that are connected to an NFT each.

The article says that awards were reduced due to storage deposit but how can this mismatch of t-shirt-NFTs to their digital twins be corrected bc those NFTs are gated by the mentioned award? Could they just add another award as gate to the existing collection as long as it hasn't been migrated to shimmer?

Related discord tickets:
#bugissue-187
#bugissue-188

Kind regards,
Bananu

**Comment by adamunchained** [comment]
Yeah, just create another award and set it on the collection. Awards on collections are editable anytime.

**Comment by IOTAPUNKS** [comment]
I have been trying to add a new badge to my collection. Unfortunately I get an error message. This message also occurs when I do not make any changes to the collection. In other collections I don't have this problem, I can save them without any changes. In other collections, however, no badge is required. 

https://discord.com/channels/892481940953915433/1078976737372807278/1079095586982215680 

Collection: https://soonaverse.com/collection/0xcd8f364bf020613a1c8a1181ac94ddab425bc6f2
New Badge: https://soonaverse.com/award/0x55b8a781e3cc35b62ab1983eafb0d6cc2f1a4a9b/overview

**Comment by adamunchained** [comment]
This has been fixed. You can edit collection.

**Comment by IOTAPUNKS** [comment]
Thank You!
