### ISSUE TITLE
[Payment Issue Token]: 

### ISSUE THREAD

**Issue by 05hr39** [soonaverse/soonaverse-dao#1058]
### Discord Name

05hr39

### Soonaverse Profile Id

0xc164651DCe7b0d72a6E296f24f575f22a0aA6883

### Transaction Type

Buying

### Transaction Source

Token Launchpad

### Payment Problem

I made the claim Deposit but did not recieve any FEE-Token.

### Wallet Type

FireFly

### Wallet Version

2.0.1

### Payment Sent to Address

smr1qrulghfuwd2ldv7aureqz4eg3hnl26rnq5hky7x090nlqdpjalsmjqzy7hu

### Amount Sent

0,0508 SMR

### Payment Message Id

0x9e31b18ae46a0e51d93676e628b4857d049f99298028651ee03c989bc1064687

### Comments

```shell
Payment Transaction on Soonaverse 0x9e31b18ae46a0e51d93676e628b4857d049f99298028651ee03c989bc1064687

Token Transaction ID on Soonaverse
0x151edc214bdea01d4adda2cfcd65fbe8d5f9fe4c7c461fafd6ea9cd1599d8d10

Would love to get in touch with my Fee-Token.
```

**Comment by adamunchained** [comment]
You have subsequently claimed it. See here:
<img width="924" alt="Screenshot 2023-03-14 at 12 44 09 PM" src="https://user-images.githubusercontent.com/130610/225119175-d92598d0-4be4-4216-87d9-5f215d449c32.png">

https://explorer.shimmer.network/shimmer/search/0xb541f0dd940ec812c5d29221ebe865314b8070c976c274c7112564722146d2da

**Comment by 05hr39** [comment]
Yes, but i have a different addr registered and in use, smr...2x9f
The Token Bill Payment(FEE) went to the address you mentioned smr....44uh
https://explorer.shimmer.network/shimmer/addr/smr1qpz2yrmaeuhtpqp4qy53c83dt25mzgrpjp7da6qz6wgl7egkquz4gap44uh

The transaction bounced on this addr for a few hours. maybe some expire,  output unlock condition :
This is the last "Fee " related Transaction on this addr:
https://explorer.shimmer.network/shimmer/transaction/0x0c2a00bf69c82336de010b8c0c111acf4cf857281eafcf06fdfcc6dc287f7c81

I found one transID in my wallet related ,might be relevant:
https://explorer.shimmer.network/shimmer/transaction/0x051b6120c9dfd94e823bdc93c1405d84da73f8843c10a1c7cf059f7083731838

Sorry to bother u and thanks for your hard work!
