### ISSUE TITLE
NftId and CollectionId are not included in the Transactions CSV Export function, only TokenID. Despite the UI showing both.

### ISSUE THREAD

**Issue by Derivs** [soonaverse/soonaverse-dao#1059]
**Describe the bug**
NftId and CollectionId are not included in the Transactions CSV Export function, only TokenID. Despite the UI showing both.
This is needed to create data needed for tax purposes

**To Reproduce**
1. Go to Profile --> Transactions
2. Click on 'export csv'
3. See only tokenID

**Expected behavior**
I was expecting a column in the csv for NftId and CollectionId

**Screenshots**
In the UI all three fields, TokenId, NftId and CollectionId are displayed:
<img width="800" alt="Screenshot 2023-02-26 at 18 14 44" src="https://user-images.githubusercontent.com/3865177/221425680-42ec7dc0-7a72-4a60-8c3f-c40c3de2658c.png">

In the CSV only token ID is exported
<img width="1624" alt="Screenshot 2023-02-26 at 18 15 35" src="https://user-images.githubusercontent.com/3865177/221425830-14ac2ac2-191c-473a-821e-fad7cf187647.png">

**Additional context**

**Comment by adamunchained** [comment]
Columns added. As it was a super simple fix, released into prod as well.
