### ISSUE TITLE
Missing badges.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1061]
The user created 2 badges (rare badge, basic badge). They report that they made 150 basic badges and 50 rare badges. Now there is just 37 rare badges and 40 basic badges in total. The user thinks this happened after a collection was fixed by the Soonaverse.

Basic badge:

https://soonaverse.com/award/0x748db3473e76a8644835d6600c0c37ffc86aa11b/overview

Rare badge:

https://soonaverse.com/award/0xae20be1e78ee376fc6be01762aefca2c8b5abbf5/overview

**Comment by adamunchained** [comment]
Yes. As discussed in #support channel and mentioned in the article. We had to reduce total number of available badges on existing awards as part of the migration process. This has been done to reduce storage deposit cost. User have to create a new award.

Total has been reduced to "issued" + 20%.
