### ISSUE TITLE
[Payment Issue Token]: 

### ISSUE THREAD

**Issue by creps** [soonaverse/soonaverse-dao#1062]
### Discord Name

@Alex-#1607

### Soonaverse Profile Id

0x60fca6e8adc5acca600c2c34505a3f06975b4f43

### Transaction Type

Buying

### Transaction Source

Token Launchpad

### Payment Problem

I can't Claim locked tokens

### Wallet Type

FireFly

### Wallet Version

1.7.1

### Comments

```shell
I've three transactions on Soonaverse that i can't claim the locked tokens. When i try to claim i receive the message: "Can not credit this transaction"

The tx are: 
__________
TranUID: 0xc7edd9c679e5e741a8bd762f3c84565cc6d29741
SMR
Amount: 163
__________
TranUID: 0xa31730f9e14094a2660b24f729c8a51fcafb6eb1
FEE
Amount: 100
__________
TranUID: 0x90dfb2ad85730ada043ac2609a787751a85a868a
FEE
Amount: 9900
```

**Comment by CptBananu** [comment]
Added screenshot from initial discord ticket:

![image-30](https://user-images.githubusercontent.com/104099536/221690091-601959d0-d2a0-4829-9951-cd36c8ad23cb.png)

**Comment by adamunchained** [comment]
This has been corrected. You can claim back those tokens.
