### ISSUE TITLE
Users can vote multiple times + proposal graphic not updating

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1065]
Users are able to vote more than once in this collection. Additionally, the votes graph isn't updating with the results.

https://soonaverse.com/proposal/0xcc9388118a554158416773e04273b03a5036312e/votes

**Comment by adamunchained** [comment]
They can vote as many times as they want. They’re just changing their opinion! That’s not a bug!

I’ll investigate why the results is not showing.

**Comment by adamunchained** [comment]
This issues has been resolved. As discussed user couldn't vote multiple times and there was just an issue with presentation of results.
