### ISSUE TITLE
User cannot buy from 'Available' collection

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1066]
User is trying to buy an nft but is receiving an error that reads "No more NFT available for sale" when there are 12 remaining.

Collection:
https://soonaverse.com/nft/0x9c33c1f0b506b1cbb55553f83ae62df3c13bdf2a

**Comment by adamunchained** [comment]
Most likely all NFTs were sold and the counter is not showing correct amount. We’ll investigate.

**Comment by adamunchained** [comment]
Hi @theflyingrabbit 

I've made a mistake on how availableNfts is used on the front-end. availableNfts indicates number of available of NFTs that were not sold during initial sale (i.e. owner not set).

Hence this is wrong: 

```
if (prev === NftAvailable.UNAVAILABLE) {
    availableNfts = [NftAvailable.SALE, NftAvailable.AUCTION_AND_SALE].includes(curr) ? 1 : 0;
    nftsOnAuction = [NftAvailable.AUCTION, NftAvailable.AUCTION_AND_SALE].includes(curr) ? 1 : 0;
  } else if (prev === NftAvailable.SALE) {
    availableNfts = [NftAvailable.UNAVAILABLE, NftAvailable.AUCTION].includes(curr) ? -1 : 0;
    nftsOnAuction = [NftAvailable.AUCTION, NftAvailable.AUCTION_AND_SALE].includes(curr) ? 1 : 0;
  } else if (prev === NftAvailable.AUCTION) {
    nftsOnAuction = curr === NftAvailable.UNAVAILABLE ? -1 : 0;
  } else if (prev === NftAvailable.AUCTION_AND_SALE) {
    availableNfts = curr === NftAvailable.UNAVAILABLE ? -1 : 0;
    nftsOnAuction = curr === NftAvailable.UNAVAILABLE ? -1 : 0;
  }
```

We should only consider availableNfts when owner is not set. This means when they create nft in a collection it'll increase availableNfts and once it's sold to someone availableNfts is decreased.

There also seems to be an issue with this collection where placeholderNft NFTs (placeholderNft=true, always one in collection) is not set hidden after all NFTs within the collection were sold (initial sale). I've noticed few other collection with similar logic. This must got broken during recent refactoring.

**Comment by theflyingrabbit** [comment]
@adamunchained let's have a call about this today.
