### ISSUE TITLE
Shimmer OG NFT can't be bought --> "INTERNAL" error message

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1067]
Hi guys,

atm it isn't possible to buy one of the listed Shimmer OG NFTs on Soonaverse. 

Clicking on "Confirm and lock" results in an unusal longlasting loading animation followed by an error message only saying "INTERNAL".

![image](https://user-images.githubusercontent.com/104099536/222257418-a64b37c2-0ff9-41fb-898f-528df95cb0b5.png)

Kind regards,
Bananu

**Comment by CptBananu** [comment]
Also depositing only seems to work via Tanglepay and not via Shimmer Firefly "NFT beta"

**Comment by adamunchained** [comment]
> Also depositing only seems to work via Tanglepay and not via Shimmer Firefly "NFT beta"

@CptBananu - I’ve deposited yesterday with Firefly BETA. See my NFT. 

@theflyingrabbit - is looking into an internal issue as we speak

**Comment by CptBananu** [comment]
@adamunchained Well then these users probably made a mistake in the tx settings... Does one have to gift storage deposit? And what about expiration time? They both said that they didn't set any but it was clearly there. So either they didn't recognize the default expiration time or it got set accidently by FF

This is a screenshot from them:
![image](https://user-images.githubusercontent.com/104099536/222292628-809ce6d2-9136-44a2-a25d-de8e0ed78b14.png)

**Comment by adamunchained** [comment]
This issue has now been resolved btw. They must gift storage deposit. Expiration time is not important.
