### ISSUE TITLE
NFT collections not showing in NFT marketplace

### ISSUE THREAD

**Issue by ILLUMINATIOTA** [soonaverse/soonaverse-dao#1069]
**Describe the bug**
NFT collections not showing in NFT marketplace (available SOON + recently added). Two collections missing: https://soonaverse.com/collection/0x2cd21a185aeb18d06589d3ab8ea88ad18ba5de36 and https://soonaverse.com/collection/0xe37e438d5fcc4f118363dd0b6caa47519390d45e

**To Reproduce**
1. Go to NFT marketplace
2. Click on available SOON
3. Collections not showing up.

**Expected behavior**
Should show in avalable SOON and recently added!

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Tried them all....Firefox, Edge, Opera, Chrome

**Additional context**
Collections are a re-upload after cancelling first upload. (Changed the cards slightly)

**Comment by adamunchained** [comment]
This has been fixed. See the list.
