### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1071]
### Email

majishan.iota@gmail.com

### Company Name

NL Hold'em Fish Buffet

### Token Link

https://soonaverse.com/token/0x164a30a7fb6ad8f6d02a74528a29bb136298874a/overview

### Your Position

Founder / Co-Founder

### Name

Majishan

### Have you already done a public sale?

No

### Files and other information

```shell
Token needs to be approved and linked to already existing token (Token ID: 0x08f3ba5fb75b1c28cdccdcb281e514e72657663c5a932c2628c5929cb13cef6acd0100000000). 37% of FISH have been distributed via Airdrops to our NFT buyers and via Twitter giveaways.
```

**Comment by MajishanIOTA** [comment]
In addition: The airdrop was manually via firefly and not with Soonaverse!

**Comment by MajishanIOTA** [comment]
@adamunchained are you there ?

**Comment by adamunchained** [comment]
this has been linked. Please note, we only support 6 decimals. See more here: #1051

**Comment by MajishanIOTA** [comment]
I think you made a mistake linking the tokens. Now 1 Mio equals 1. Nothing is working. Token Supply is showing wrong (https://soonaverse.com/token/0x164a30a7fb6ad8f6d02a74528a29bb136298874a/metrics) and I just put 37 Mio for sale, now there is 37 for sell and can't even buy those....
