### ISSUE TITLE
[NFT] Shimmer mainnet on chain NFT not listed on Soonaverse after deposit

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#1072]
**Describe the bug**
I have minted my own NFT collection on Shimmer mainnet using the Shimmer libraries.
Try to deposit the NFT to Soonaverse.
The window stayed open in the browser. No NFT has been accredited.

**To Reproduce**
1. Mint NFT on chain using the libraries and not Soonaverse
2. Go to the profile to deposit
3. Send the NFT to the proposed address
4. NFT is sent and nothing happens

**Expected behavior**
NFT deposited

**Screenshots**
**THIS IS AN EXAMPLE IMAGE** The timer ran out and nothing happened
![](https://media.discordapp.net/attachments/847493892265738271/1080548080123924480/image.png?width=838&height=613)

**Soonaverse address in question, related to the issue**: `smr1qq3fslz0jtq0mwusk02tl683y8q4mj3vr06jq5xe2uca9hggeqdpywf5v4t`

**Desktop (please complete the following information):**
 - OS: GNU/Linux Mint
 - Browser: Chromium
 - Version: 110.0.5481.177 (Official Build) Arch Linux (64-bit)

**Additional context**
NFT ID: `0xda9e2170f6eb0f5920401032f87edabe70dc8e4e55f47052217b5cc86c2424f9`
Collection ID: `0x02948906a1e5567d947216b9c4234222d104d05391d0fcc8b1a500bad61dd2eb`
Transaction on Shimmer explorer: https://explorer.shimmer.network/shimmer/transaction/0x5abe508a1ff55809793c715b3ad9e71075ac325dc1f88d01844780b8e62d9924

**Comment by theflyingrabbit** [comment]
Hello. I have identified the issue. For some reason it is not possible to download the nft's image from ipfs, it runs forever.
Check this url: https://ipfs.io/ipfs/bafybeic2v5oyhe2r5p24lwz5ozh2peysszprxpdn2ufwthbk5syins5hka
The fix will be deployed today, and your nft should be credited back later today.

**Comment by adamunchained** [comment]
Fixed deployed to prod and NFT was credited back
