### ISSUE TITLE
Delete NFT collection

### ISSUE THREAD

**Issue by Schnielz87** [soonaverse/soonaverse-dao#1073]
I have 2 collections on Soonavers and unfortunately I made a mistake in the date format.  Instead of the American date, I took the European date format and now my NFT's start instead of today, only in 88 days.  How can I either: change the date?  or delete the collections completely so that I can set them up again?

here are the two collections:

https://soonaverse.com/collection/0x114783a8fb81f3bdf4ed4029cfbff4e48ff9bf06

https://soonaverse.com/collection/0x76dc62aa3d521355f214ee39a61c4e21b7d0f2f0

**Comment by adamunchained** [comment]
I've rejected those collection and you can re-create them.

**Comment by Schnielz87** [comment]
great, thank you very much for your help 🤗

Adam ***@***.***> schrieb am Mo., 6. März 2023, 21:49:
