### ISSUE TITLE
Android mobile: Autoredirect to Tanglepay after a few seconds

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1074]
Hello guys,

When u go to Soonaverse on android mobile browser (Firefox, Opera), after a few seconds one gets autoredirected to tanglepay. Although this happens only once per session it is quite annoying and may also seem suspicious to new users.

Kind Regards,
Bananu

**Comment by adamunchained** [comment]
I've just released a hotfix for this. It was an issue with TanglePay library. Can you please check again? I don't have Android mobile so it's possible for me to validate.

I've also fixed an issue where filters were opening up on mobile in collections / NFTs pages by default.
