### ISSUE TITLE
Not properly displayed page

### ISSUE THREAD

**Issue by guhyeonjeong** [soonaverse/soonaverse-dao#1075]
**Describe the bug**
Staking information is not properly displayed(cut out) if a browser size is changed

**To Reproduce**
1. Go to https://soonaverse.com/member/0xac2c8bdc99cc8edd3db4d43756d2b021953d0423/tokens
2. Adjust a browser size ( I made it narrower horizontally)
3. See error

**Expected behavior**
Properly displayed without loss of information

**Screenshots**
![image](https://user-images.githubusercontent.com/3461814/223310400-ac6f4fd7-82bc-47cf-a8cd-d7c1aed9170d.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Browser: Chrome
 - Version: 110.0.5481.177

**Comment by humaint** [comment]
full screen shows disabled scroll bars
