### ISSUE TITLE
Voting results of proposal showing wrong

### ISSUE THREAD

**Issue by ILLUMINATIOTA** [soonaverse/soonaverse-dao#1076]
Results show wrong in proposal section

People who didn't vote yet are counted as a 'yes'-vote on our recently started proposals.

https://soonaverse.com/proposal/0x69f45e765e871dd2019e8738901a6d975bcfec35/overview

https://soonaverse.com/proposal/0xf423a25fdc2e479b03ed3a97eb95cc0986767895/overview

**Comment by adamunchained** [comment]
How so?

1. Proposal, you have 2 yes/4 no. It shows correctly 40% Yes / 60% No out of total voted.
2. Proposal, you have 1 yes/4 no. It shows correctly 20% yes / 80 % no out of total voted

**Comment by adamunchained** [comment]
Feel free to re-open if there is something I’ve missed

**Comment by ILLUMINATIOTA** [comment]
This is still an issue. It may show correct results if looked deep into proposal but on the proposal page every not yet voted vote counts as first vote option!

**Comment by ILLUMINATIOTA** [comment]
![Screenshot 2023-03-31 182656](https://user-images.githubusercontent.com/124702141/229177668-1428b6c7-be72-4d95-8eaa-127b3d858316.png)

**Comment by humaint** [comment]
![SCR-20230404-jpa.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/f5444ea1-1ba8-40ce-ba5c-d0ad2f051e1a)

@adamunchained it looks like a random error on some proposals, like this [example](https://soonaverse.com/proposal/0x9b23a13484b99d52fe3b177f2eadde8a4fc9d996/votes) 

there are casted votes but the graph doesn't reflect them

**Comment by theflyingrabbit** [comment]
@adamunchained 
The proposals reported by ILLUMINATIOTA seem correct to me.

The one reported by humaint is indeed wrong. answers 4:0 should be 4:1. This is an old proposal however, I am assuming that there must have been a temporary bug at some point as I can't find any bug in the code.
I have also tested proposals manually via the UI and it seems to be working properly.

**Comment by adamunchained** [comment]
closing as this was an issue with old proposals. 

@ILLUMINATIOTA - do you have this issue with new proposals?
