### ISSUE TITLE
After Shimmer migration: burned NFTs still "listed"

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1077]
Hi guys,

a user told us in discord #bugissue-208 the following:

_We have migrated this collection to shimmer: https://soonaverse.com/collection/0xf505d36b58f9a46d0c7088f0a257e5bf87b627c2
All unsold are burned.

But the burned ones are still visible in the collection and if you click on them, you will get a 'not found' message._

Could u pls check on this?

Cheers,
Bananu

**Comment by adamunchained** [comment]
@theflyingrabbit - It seems to be an issue with Algolia. It didn’t remove the records from Algolia after they were burn in Soonaverse.
