### ISSUE TITLE
Wrong date in one collection 

### ISSUE THREAD

**Issue by mikaa-ger** [soonaverse/soonaverse-dao#1078]
Hey Support, we had a format error in excel, the date was wrong. We want to publish a collection pon 11 March, not 03 Nov (11.03, not 03.11)... 

Can you please change the date? 

https://soonaverse.com/collection/0xd62c81f880b324ad6b8ada6789a93f451096c8c2

Please set to 11 March 23

**Comment by adamunchained** [comment]
@theflyingrabbit - can you please enable ability to change available data on collection (future date only)? Previous date must be still in the future. In other words, sale didn't start yet.

Once done, assign back to me and I'll tweak front-end. This is pretty much similar to change what we did with https://github.com/soonaverse/soonaverse/issues/2276 where we have to update the NFTs as well. 

See nft.create.ts, line 102 when we set availableFrom based on collection.

**Comment by SeanTMartin** [comment]
This issue is persisting for the user. ticket community #220
