### ISSUE TITLE
Auctioned NFT listed under "on sale"

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1083]
Heyho,

User from discord ticket #community-220 reported the following:

Hello
I have Ape #745 on auction, but it don't show in this category. It is in "on sale". So nobody will find and see my auction Please help 😉✌🏼

![Screenshot_20230315_171726_MetaMask](https://user-images.githubusercontent.com/104099536/225386441-8233f4cd-11a5-4ac3-9695-4d5dc6cee248.jpg)

Could u pls check this?

Kind regards,
Bananu

**Comment by adamunchained** [comment]
This has been fixed. It was sync issue with search engine.
