### ISSUE TITLE
Enable decimal support on tokens

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#1084]
see https://github.com/soonaverse/soonaverse-dao/issues/1051

@theflyingrabbit - please enable support for decimals on backend:
- [ ] add decimals property on token object
- [ ] update all existing tokens with 6 decimals
- [ ] add ability to set decimals during token creation
- [ ] decimal needs to be correct set within token metadata when minted
- [ ] read decimals from token metadata when it's imported from Shimmer

This is purely visual function. Once implemented we'll add front-end support, please assign back.

Again I'm pushing this forward because today I had 4th project complaining about this :(

**Comment by MajishanIOTA** [comment]
Oh no, why did I not read this before ...

**Comment by humaint** [comment]
@adamunchained not sure how to test

**Comment by adamunchained** [comment]
@humaint - see my comment on https://github.com/soonaverse/soonaverse-dao/issues/1051
