### ISSUE TITLE
Error message "Invalid NFT" when depsositing on soonaverse 

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1087]
Hi there,

a member in discord (#bugissue-225) reported that he can't depsoit an NFT from firefly to soonaverse.

He gets this message:
<img width="739" alt="Screenshot_2023-03-17_at_1 18 39_AM" src="https://user-images.githubusercontent.com/104099536/225861737-0a49eb32-2a7a-46e8-814d-e857bdf68db3.png">

He also got back his NFT:
<img width="358" alt="Screenshot_2023-03-17_at_2 09 39_AM" src="https://user-images.githubusercontent.com/104099536/225862124-87cec94f-8681-43f2-aaac-e999b85c89d5.png">

Further details on his transactions:

Soonaverse name : Dag2thefuture

NFT ID : 0xf4033b6b9c435cf921ab3777c47d8b36da3739c36ce9e8dcd9099cee98d09d09

Tx ID : 0x9ef0a107ecf9ed0989e5a650a99452369ca4433459877c5b0ba398adc3e5256d
https://explorer.shimmer.network/shimmer/transaction/0x9ef0a107ecf9ed0989e5a650a99452369ca4433459877c5b0ba398adc3e5256d

Artifact #3089:
https://explorer.shimmer.network/shimmer/transaction/0x89c5bfd4d1305fedaa7679c5ddfa4343508b6a0c9740e1407e492e38f3471c11

Could u pls check this?

Thx and kind regards,
Bananu

**Comment by adamunchained** [comment]
@theflyingrabbit - could check why it was credited back? I noticed there is a credit without any reason. 
Order was not expired.
See below:

```
{
  "0x0d58b6d05e85577fc1c597c676e46be9e4d868ad": {
    "createdOn": {
      "__time__": "2023-03-17T08:18:05.195Z"
    },
    "isOrderType": false,
    "member": "0xdc1dbf6b44ebc20acbb2889f35455b44b74123c4",
    "network": "smr",
    "payload": {
      "amount": 167000,
      "ignoreWallet": false,
      "ignoreWalletReason": "",
      "invalidPayment": true,
      "nftId": "0xf4033b6b9c435cf921ab3777c47d8b36da3739c36ce9e8dcd9099cee98d09d09",
      "reconciled": true,
      "response": {
        "code": "",
        "message": "",
        "status": "error"
      },
      "sourceAddress": "smr1qz4mft38a7j43l9dvsxtg30k76yd2mqpek96ck3le38n8u8evcqkxwn4gsx",
      "sourceTransaction": [
        "0xb40f6f4028e72448ee27fceca0b0497cf0139161"
      ],
      "targetAddress": "smr1qrqqmy73j3dm85wrdzeucqpymtzrh6ykqhfeakke43ta6hsjzcymsvf66qw",
      "void": false,
      "walletReference": {
        "chainReference": "0x183482525fe974c4c77b5f5a7fa6db17f2a57c11175afcb6aa0810a659322006",
        "chainReferences": [
          "0x183482525fe974c4c77b5f5a7fa6db17f2a57c11175afcb6aa0810a659322006"
        ],
        "confirmed": true,
        "confirmedOn": {
          "__time__": "2023-03-17T08:18:16.587Z"
        },
        "count": 1,
        "createdOn": {
          "__time__": "2023-03-17T08:18:05.538Z"
        },
        "error": null,
        "inProgress": false,
        "milestoneTransactionPath": "milestone_smr/2948279/transactions/0x89c5bfd4d1305fedaa7679c5ddfa4343508b6a0c9740e1407e492e38f3471c11",
        "processedOn": {
          "__time__": "2023-03-17T08:18:08.548Z"
        }
      }
    },
    "shouldRetry": false,
    "space": "",
    "type": "CREDIT_NFT",
    "uid": "0x0d58b6d05e85577fc1c597c676e46be9e4d868ad",
    "updatedOn": {
      "__time__": "2023-03-17T08:18:16.587Z"
    },
    "wenUrl": ""
  }
}
```

**Comment by theflyingrabbit** [comment]
@adamunchained This nft was credited back, because the nft uri points to the root ipfs folder and not to the actual image.
See https://ipfs.io/ipfs/bafybeialpy7lrjfvoohg7sjtlydevzpfby2mbym4ruwxkze6wcx6pwgmvm/

**Comment by adamunchained** [comment]
> @adamunchained This nft was credited back, because the nft uri points to the root ipfs folder and not to the actual image.
> See https://ipfs.io/ipfs/bafybeialpy7lrjfvoohg7sjtlydevzpfby2mbym4ruwxkze6wcx6pwgmvm/
> 

Well this NFT was minted via Soonaverse and withdrawn. It was minted last year when didn't point the URI to an actual file but still to a directory. This applies to any minted NFTs prior December release.

Our system should support these. Ideally it detect these NFTs already existed in Soonaverse before and it just re-use inage that is most likely already in the storage. I don't we need to revalidate and redownload image from an URI.

**Comment by Travetown** [comment]
Same here:
https://explorer.shimmer.network/shimmer/addr/smr1zz2z056evqfwm7egw7hkz2jxr4jyf6u23mkq98uw0kpmnn9em3lcgy84zyf
https://explorer.shimmer.network/shimmer/addr/smr1zq8edszr6sdxd0rzzq0arcgdfw637kasr988mlwtjlmysml3ql07ymjzphc

**Comment by adamunchained** [comment]
@Travetown - can you try again? This should have been now fixed.

**Comment by Travetown** [comment]
> 

Yes, now it worked! Thanks a lot!
