### ISSUE TITLE
Token description is not editable 

### ISSUE THREAD

**Issue by epochzro** [soonaverse/soonaverse-dao#1088]
Editing the token info returns an error

**To Reproduce**
1. goto the token page
2. Click on 'Edit token info'
3. Click 'Save Changes'
4. See error "Token in invalid status."

**Expected behavior**
The updated text is saved

**Comment by adamunchained** [comment]
@theflyingrabbit - tokens should be editable in any status prior MINTED.

Let's change:
```assertTokenStatus(token, [TokenStatus.AVAILABLE]);```

**Comment by theflyingrabbit** [comment]
@adamunchained These are the editable fields
![image.png](https://images.zenhubusercontent.com/62d6b66bae090a211b5b8971/27fbb84d-2443-417b-bf90-a1a019f2c5f9)
Should we allow editing these even after the token is minted?

**Comment by humaint** [comment]
@adamunchained I'm trying to edit availabla token and getting
 ""Invalid params [{\"message\":\"\\\"name\\\" is not allowed\",\"path\":[\"name\"],\"type\":\"object.unknown\",\"context\":{\"child\":\"name\",\"label\":\"name\",\"value\":\"Pokemon\",\"key\":\"name\"}}]""

**Comment by adamunchained** [comment]
@humaint - fixed
