### ISSUE TITLE
[TLP]: Fish Buffet

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1089]
### Email

majishan.iota@gmail.com

### Company Name

No Limit Hold'em Fish Buffet

### Token Link

https://soonaverse.com/token/0x164a30a7fb6ad8f6d02a74528a29bb136298874a/overview

### Your Position

Founder / Co-Founder

### Name

Majishan

### Have you already done a public sale?

No

### Files and other information

```shell
Hey @adam_unchained, I created new FISH with 6 decimal places. New token ID needs to be linked to token in Soonaverse (New Token ID: 0x0879ead286b33e6520219d7b7690d27c0778d33f01cab14280e96de007784cad820200000000). All original FISH holders received a 1:1 of newly created FISH (Took me three days...uff). I hope this works out now. Also please leave trading suspended. I will consider opening trading in April. Thanks a lot for your help! If you have any questions don't hestitate to ask here or contact me in Discord!
```

**Comment by adamunchained** [comment]
I see, so you want us to relink this existing token to the new token ID right?

BTW - I think it's great you did that. 6 decimals makes your coin way more fair and future proof.

**Comment by MajishanIOTA** [comment]
Yes, please relink new token. I think so too, not sure why I didn't in the first place. Maybe lack of experience.

**Comment by adamunchained** [comment]
It has been updated.
