### ISSUE TITLE
[Payment Issue Token]: IOTA back to firefly wallet can not transfer

### ISSUE THREAD

**Issue by poorviv** [soonaverse/soonaverse-dao#1096]
### Discord Name

@WLTSAIJ#4980

### Soonaverse Profile Id

0xd37444E2E99bB5CA1D0168Eb88144e85A8d1b0c7

### Transaction Type

Buying

### Transaction Source

Token Launchpad

### Payment Problem

IOTA back to firefly wallet can not transfer

### Wallet Type

FireFly

### Wallet Version

1.7.1

### Payment Sent to Address

iota1qr4f2vfjgneegx4njqat3c23dx454m3agxswu8pv9cqpjs6vxtxtxvd3445

### Amount Sent

1700Mi

### Payment Message Id

b2a1f6a758c96251295ef56595141b5c72fca9f09b8b7236653d1b3388a54c00

### Comments

```shell
Hi, IOTA back to firefly wallet can not transfer. Please help check this payment transfer "Conflicting". Thanks.  

https://explorer.iota.org/mainnet/message/b2a1f6a758c96251295ef56595141b5c72fca9f09b8b7236653d1b3388a54c00
https://explorer.iota.org/mainnet/message/f27a1ba697d9d4bd1ff944b4f27c6c0c07a3dc8716e09b8a64552b7e436eea11
```

**Comment by adamunchained** [comment]
Based on above it seems Firefly is conflicting the transaction. Whats the issue on Soonaverse side?

**Comment by adamunchained** [comment]
closing for now, please free to re-open if still an issue
