### ISSUE TITLE
NFT removal

### ISSUE THREAD

**Issue by jeanmouloudcohen** [soonaverse/soonaverse-dao#1105]
Hi
Using the @screugneugneu account I wanted to remove this NFT
https://explorer.shimmer.network/shimmer/addr/smr1zzpyadjttt0qahz0uqrjj56je68lqxpn6xp7vzqmwwvt6m7l84weunrc4lm
but I never received it on my FireFly, my wallet works, it recorded transactions and received other NFTs later
here are the links of the transaction and where is this NFT Pharaoh #4161
https://explorer.shimmer.network/shimmer/transaction/0x4d387f29375bb6cfa9b4299ad86e1e5841cfd0e606c2fa96b8569f1c9860da60
https://explorer.shimmer.network/shimmer/addr/smr1qrch5jmn3un7yc9g9qglr38twhghjttk9acnch6cfgvy0kk9440q75uma70
THANKS

**Comment by theflyingrabbit** [comment]
@jeanmouloudcohen We have identified the problem, NFT Pharaoh #4161 should be in your wallet now.
