### ISSUE TITLE
Delete/reject old NFT collections

### ISSUE THREAD

**Issue by iotamorons** [soonaverse/soonaverse-dao#1106]
In reference to Discord #bugissue-248

After the launch of the Soonaverse, we added two NFT collections to our space. Only members with a special badge should be able to mint these NFTs, but we noticed that we had selected the wrong badge for the collection, so nobody could mint them. At that time, there was no way to add another badge to the existing collection, so we decided to create a new ones with the correct badge. Now, we are facing the problem that there are two 'dead' NFT collections which will never be released because those NFTs have already been minted in the other collection, as described. 

We kindly ask to delete/reject those two affected collections. (We renamed them with blank banners and a random name):

https://soonaverse.com/collection/0x9d6886b3144ae9d02bdb5fd80d0b1c0154fbe718 
https://soonaverse.com/collection/0x28e8ea243ff33d98e0417aafe292efcee0a1e909 

Thank you very much! :-)

**Comment by adamunchained** [comment]
done
