### ISSUE TITLE
Wrong floor price on collections

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1109]
Hi guys,

on EpochZero some users recognized that the floor price of the Pharaoh collection (https://soonaverse.com/collection/0x81a7845b52d0725c607c80a2c83d390334565b09) isn't displayed correctly. It seems to have cached the mint price of 750 SMR. 

![image](https://user-images.githubusercontent.com/104099536/230480712-a9ad26c2-04cc-425d-bab0-7b34d1d89090.png)

Other collections like Orbiis (https://soonaverse.com/collection/0xb7d1441a1f6136acb25f874086740c588d597878) match the floor price when u sort by price:
![image](https://user-images.githubusercontent.com/104099536/230480418-58f4e78a-9775-4a4c-b129-d2df87a3cff1.png)

Is there some sort of caching of floor price so that we maybe missed that 750 SMR trade before the "floor  price snapshot"?

Cheers,
Bananu

**Comment by theflyingrabbit** [comment]
@adamunchained As per our slack conversation, this is an algolia trigger issue. What we can do is increasing min instance count on the trigger and re upload records to algolia.

**Comment by adamunchained** [comment]
ok let's do that. Just do a simple re-update of NFTs (just those).
