### ISSUE TITLE
[Payment Issue NFT]: 

### ISSUE THREAD

**Issue by avaxdogukan** [soonaverse/soonaverse-dao#1110]
### Discord Name

@0xDogukan#9607

### Soonaverse Profile Id

0xe3cFD3c215FA6ED180A0Af6ED16d6E0aFbb25146

### Transaction Type

Buying

### Payment Problem

Did I transfer nft to my soonverse account, but nft was taken from my wallet, it didn't go to my soonverse account

### Wallet Type

FireFly

### Wallet Version

2.1.0

### Payment Sent to Address

smr1qqwm83955ag5sk68j7mfpggqdw6hznkaejrv9ckqt9tt9xxg9u3dqht3xhk

### Amount Sent

0.097

### Payment Message Id

0x28b2c240f719053f5f0b12b3deabed46c539015cad5b2a09a4efe6b784b1fe69

### NFT Id

0x28b2c240f719053f5f0b12b3deabed46c539015cad5b2a09a4efe6b784b1fe69

### NFT Collection Id

0xf8757e1cc7ed608efe7d2cc3fa1ea78f44015c5e56d15424516ca9349a2bdfae

### Comments

```shell
Did I transfer nft to my soonverse account, but nft was taken from my wallet, it didn't go to my soonverse account 
shimmer hesabım:smr1qp4afv37qzyqwm2007d738dsj37xfh6kknqzn26tvv35yw046nwcz73z8qa
soonverse hesabım:0xe3cFD3c215FA6ED180A0Af6ED16d6E0aFbb25146
pleasse help me
```

**Comment by avaxdogukan** [comment]
HELP ME MATEE

**Comment by adamunchained** [comment]
This issue has been fixed. You should be able to claim your NFT back within transaction log under the member profile.
