### ISSUE TITLE
[TLP]: MAJI Token

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1112]
### Email

majishan.iota@gmail.com

### Company Name

MAJI - Majishan

### Token Link

https://soonaverse.com/token/0x7694bc00ec19b041a6f5af16e8183060093c2cce/overview

### Your Position

Founder / Co-Founder

### Name

Majishan

### Have you already done a public sale?

No

### Files and other information

```shell
Hey @adam_unchained,

could I get MAJI Token Approved for trading please? 

Thanks in advance!

P.S: Happy Eastern from the other side of the world (:
```

**Comment by MajishanIOTA** [comment]
Hey, I need to edit the token too. It says token in ivalid status. I need to update yearly &weekly APR which are much higher than it says in token description.

**Comment by adamunchained** [comment]
Approved. Please see issue: https://github.com/soonaverse/soonaverse-dao/issues/1088

It'll enable update.
