### ISSUE TITLE
Price differs between collection and its "placeholder-NFT"

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#1115]
Discord: #community-268
https://discord.com/channels/892481940953915433/1096059558138499122/1096061143384072286

Hi guys,

The user in the above mentioned discord ticket reported that the price of his collection was set to 3 Mi (which all worked out well).
But when u go to the placeholder NFT attempting to mint one, the price falsely says 5 Mi instead of 3 Mi.

Collection: https://soonaverse.com/collection/0x2a0ee15d7424368e1425b38bb08bfa692f1f7e4b

Mint-Placeholder: https://soonaverse.com/nft/0x25610d14785bd9dfbc826fad1c03d3002b67610f

User is asking if u pls could fix this by setting the placeholder price to 3 Mi also.

Cheers,
Bananu

**Comment by CISULH** [comment]
hi  I wanted to change the price and the 5 miota remained. The sale is Saturday... if you could change this problem before the sale..

**Comment by CISULH** [comment]
Please can you help me? I need to make the change before tomorrow. I can't advertise because I don't know if the collection will be released at 3 or 5 miotas. THANKS

**Comment by adamunchained** [comment]
When you edit collection and update price it should update price on all NFTs, it didn’t?

**Comment by CISULH** [comment]
As long as I stayed on iota it didn't work. But yesterday I migrated to Shimmer and the problem was solved, the prices were all displayed at the same price. Thanks for your help. we can close the issue
