### ISSUE TITLE
Possibility to change the wallet address for "Space"

### ISSUE THREAD

**Issue by DigiMine22** [soonaverse/soonaverse-dao#1116]
There is an option for users to change their IOTA or Shimmer address in Soonaverse, but unfortunately this is not the case for Space. There are no change options there. Projects evolve and wallets also change due to security measures. Herewith it is requested that Soonaverse makes this change and also provides this possibility for Space. THX

**Comment by IOTAPUNKS** [comment]
We also have this problem and therefore very much welcome this proposal. Please make this change.
Thank you!

#OneOfUs

**Comment by adamunchained** [comment]
Lets get it done. We will allow change of the address. Guardian can set a new address and it’ll go for a vote by other guardians. Same way as other changes on space works.

**Comment by DigiMine22** [comment]
Thank you, we look forward to the necessary changes you make.

**Comment by IOTAPUNKS** [comment]
Good to hear. Thank you very much!

#OneOfUs
