### ISSUE TITLE
Voting

### ISSUE THREAD

**Issue by priceactionbars** [soonaverse/soonaverse-dao#1117]
VOTING Idea suggestion

Soonaverse represent a DAO structure and it means more demcoratic rules and shouldn't cost money to vote.My suggestion is you only let people invite to vote. After the person voted you or downvoted(not yet confirmed the vote by guardian of a space) you get a notification  to ACCEPT or REJECT the vote  if she /he is  the the RIGHT person you invited to verify(now you can see if she or he upvoted or downvoted you) you invited the person by a code  or transaction ID(same applies when you want to vote for a party in general in a country, you get an invitation card to vote every 4 year).After that, you can see that he/ she can't vote anymore after you accepted or rejected since it's locked and can't manipulate, because you invited her/him/  once. I find this more reasonable because letting everyone vote is like giving them all credit without verifying them.

**Comment by Travetown** [comment]
Oh, a long headline. 
And then I only invite the people I know agree with me? What about multiple accounts from one person? 
That's really only possible with KYC verified accounts. 
This difficulty is not limited to Soonaverse. It affects all DAOs in crypto.

**Comment by adamunchained** [comment]
@humaint

**Comment by priceactionbars** [comment]
> Oh, a long headline. 
> And then I only invite the people I know agree with me? What about multiple accounts from one person? 
> That's really only possible with KYC verified accounts. 
> This difficulty is not limited to Soonaverse. It affects all DAOs in crypto. 

Ask Chatgpt about my idea and he will tell you that's not a bad idea.  And there is no 1 perfect solution against manipulation. There will be always manipulation and KYC won't help this. 
You can add other securities on top of the invitation to secure you against bad actors.

If you want to let everyone pay to get KYC'ed then some bad actors will pay a lot of accounts...Even if you get scammed KYC won't do much or if someone will take action against you and sue you. But that cost too much money.

**Comment by humaint** [comment]
I see this as another voting/proposal option. It has it's advantages but it can't replace our current voting methods. Also it's bit complicated in terms of implementation.  @adamunchained I don't see it as a high priority request.

**Comment by adamunchained** [comment]
I agree, let's park this for now. Thank you @priceactionbars for great suggestion, let's revisit it in the future.
