### ISSUE TITLE
Can't airdrop our NFT holders-error

### ISSUE THREAD

**Issue by iotahouse** [soonaverse/soonaverse-dao#1118]
We tried to airdrop our NFT holders with HOUSE tokens, but it gives us constantly errors.

Can you fix this  as soon as possible and what the problem is
[airdropHOUSE.csv](https://github.com/soonaverse/soonaverse-dao/files/11241985/airdropHOUSE.csv)
 ?

**Comment by adamunchained** [comment]
What's the error?

**Comment by iotahouse** [comment]
Our mistake found, there was no error, we didn't put the "stake text" in the column.

Our apologies.
Kind regards
IOTA House
