### ISSUE TITLE
Conflicting NFT not found after claiming.

### ISSUE THREAD

**Issue by Machstemal** [soonaverse/soonaverse-dao#1120]
Thanks Adam @adamunchained,
well I claimed the NFT from my transaction list and then got the storage deposit back to my SMR address. But the NFT is nowhere to be found.
On Soonavers, @Meta maske is displayed in my user profile
"You won an NFT ef
You are the proud owner of a new NFT. Congratulations!"
when i click on it i get this page.
https://soonaverse.com/nft/not-found
![Screenshot 2023-04-19 093526](https://user-images.githubusercontent.com/96343106/233002621-f3fefb56-66b6-4292-8d07-7a585eb38152.png)

I've searched all the Firefly wallets I have. The NFT cannot be found.
What now?
Do I have to wait for the fix in the upcoming release or did something go wrong again?

Greeting Machste

_Originally posted by @Machstemal in https://github.com/soonaverse/soonaverse-dao/issues/1119#issuecomment-1514292790_

**Comment by adamunchained** [comment]
As mentioned in #1119 you should be able to claim it back. Try again from the transactional log please
