### ISSUE TITLE
[TLP]: Please fix validation problem with $ in front

### ISSUE THREAD

**Issue by DigiMine22** [soonaverse/soonaverse-dao#1123]
### Email

office@digimine.de

### Company Name

DigiMine

### Token Link

https://soonaverse.com/token/0x08667286764515d0cbe0e147361133185c76931b24e0b41d2463cad64329a4897f0100000000/overview

### Your Position

CEO

### Name

Alex

### Have you already done a public sale?

No

### Files and other information

```shell
If you import an already created token into Sonnaverse, then there is a validation problem that no trade allowed. The problem occurs when the token name is prefixed with a "$" character. Please fix this problem. THX
```

**Comment by adamunchained** [comment]
@theflyingrabbit - we should allow $ sign in symbol.

**Comment by IOTAPUNKS** [comment]
We are also affected by the problem. Unfortunately, tokens with $ ($PUNK) symbol are not accepted during deposit. 

https://discord.com/channels/@me/950440059746791455/1098712583323795589

**Comment by adamunchained** [comment]
This was fixed. This has been fixed.

**Comment by IOTAPUNKS** [comment]
Great, thank you!
