### ISSUE TITLE
Can't Save Profile Changes ("Nft is on sale")

### ISSUE THREAD

**Issue by TangleAccountant** [soonaverse/soonaverse-dao#1134]
I can't save my profile changes because it says my NFT is on sale. My NFT is not on sale. I don't have any other NFTs and you can't not have an avatar, so I have no way to make changes to my profile. Also, the error message should spell NFT with all capitalized letters.

![image](https://user-images.githubusercontent.com/78708402/234602130-e2f2d22e-8a4c-483d-af27-397d30931e5c.png)

**Comment by adamunchained** [comment]
@theflyingrabbit - can you check why the Avatar 1104 can't be set since it's not on sale?

I'm looking into the other issues.
