### ISSUE TITLE
Staking Reward Schedule .csv upload doesn't work

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1135]
Currently trying to upload staking reward schedule .csv file

After uploading I just get an empty page...

I tried different date formats, I know that YYYY-MM-DD worked before but it is not working this time

**Comment by humaint** [comment]
@MajishanIOTA can you attach the csv you wanted to upload

**Comment by MajishanIOTA** [comment]
Hey @adamunchained , sorry for the very late reply! I tried DD-MM-YYYY HH:MM:SS now with the same unpleasing result. Am I doing something wrong? I attached the .csv . Cheers&thanks in advance!
[soonaverse_airdrop_template (9).csv](https://github.com/soonaverse/soonaverse-dao/files/11572431/soonaverse_airdrop_template.9.csv)
