### ISSUE TITLE
Collection migration

### ISSUE THREAD

**Issue by SMRPUNKS** [soonaverse/soonaverse-dao#1137]
The migration now lasts more than 24 hours and the collection has started in the meantime.
It is not possible to buy NFT.

How long will this process take?

![1232123](https://user-images.githubusercontent.com/132101572/235246734-a30d076d-66c4-4afe-951c-ba0870621ed7.png)
![zzzzzz](https://user-images.githubusercontent.com/132101572/235246842-880bab2c-97e3-459d-aa21-df0560d926dc.png)
![fsfsfsfsfsfsf](https://user-images.githubusercontent.com/132101572/235247556-002804fb-4f57-4ed6-a8c6-96c47e66f4de.png)

Starts at Apr 28, 2023, 8:00:00 PM 

https://soonaverse.com/collection/0x7d1d7f2ba7f053bb86eb79eaf32bbf52b2c04a25

DISCORD: [http://discord.gg/wJqENXdaJ2](https://t.co/8cqGjwAdKZ)
https://twitter.com/ShimmerPunks

**Comment by adamunchained** [comment]
this has been fixed
