### ISSUE TITLE
Staking Pharaoh Epoch Zero

### ISSUE THREAD

**Issue by Chabal77** [soonaverse/soonaverse-dao#1139]
Hi, i wanted to stake a Pharaoh but it's stuck somewhere. Transaction 0xd985f39ca5fd696de831a3a517409f0904827b2b7de92ff294c380c16a99484e

**Comment by adamunchained** [comment]
@flyingrabbit-lab - another one https://github.com/soonaverse/soonaverse-dao/issues/1144

**Comment by flyingrabbit-lab** [comment]
Nft is credited back now!
