### ISSUE TITLE
Staking Pharaoh Epoch Zero

### ISSUE THREAD

**Issue by Gusio1** [soonaverse/soonaverse-dao#1140]
Hello.
I have sent a Pharaoh for staking. 
But it got lost on the way. 

Here is the transaction id: 
0xa365324957ebc5269b10bc2fc4581270f895f32452002fa7bb5e8fe94b76ad92

And here the link for the Shimmer Explorer of this Transaction: https://explorer.shimmer.network/shimmer/transaction/0xa365324957ebc5269b10bc2fc4581270f895f32452002fa7bb5e8fe94b76ad92

**Comment by adamunchained** [comment]
@flyingrabbit-lab - and another one https://github.com/soonaverse/soonaverse-dao/issues/1144

**Comment by flyingrabbit-lab** [comment]
Nft is credited back now!
