### ISSUE TITLE
Banner graphics cut off 

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1141]
A user indicated that they're having problems with getting the banner size right for their colllection because the currently documented banner size of 2350 x 1080 cuts off portions of the image and this is what they see. If this is not an intended, necessary thing, either the banner size should be updated in the documentation or it shouldn't be cut off.

![image-16](https://user-images.githubusercontent.com/38050901/235538262-5eee6558-dcdc-429e-9a4f-4a1dda852578.png)

**Comment by humaint** [comment]
@SeanTMartin I would update our doc based on my response on discord:

banner is set to "object-fit: cover" meaning:
The replaced content is sized to maintain its aspect ratio while filling the element's entire content box. If the object's aspect ratio does not match the aspect ratio of its box, then the object will be clipped to fit.

not ideal, but it's the same for all our banners. We can't change this as it would affect all existing spaces, collections, etc...

I would target the widest browser window breakpoint (browsers width 1900px +) = ratio of the banner img 37:8. For smaller screens it will cut the sides of the image but it stays perfect for your targeted browser resolution.

n3tsu is a good example, the main logo is centred so it doesn't matter if the banner is cropped
