### ISSUE TITLE
[Payment Issue NFT]: 

### ISSUE THREAD

**Issue by Deweypoka** [soonaverse/soonaverse-dao#1142]
### Discord Name

aleiota#1658

### Soonaverse Profile Id

0x51339e7aE0d36FCd53c694b51EF9BdB8E9Db624F

### Transaction Type

Selling

### Payment Problem

Lost Nft after staking

### Wallet Type

FireFly

### Wallet Version

V2.1.0

### Payment Sent to Address

smr1qpn8spc42t5vx23mp6pykgmeumlfcga4le82cwxs23v44r4fggm9v9zf3rx

### NFT Id

0xef9720397f8901802729c78445b342745cf57a8e59565f9b2f002521485bb779

### NFT Collection Id

0x041e76073026afab15dbae86eeb2c7dd6876c463ca39fe03f62fecf1d7b6b268

### Comments

```shell
Hey i was staking my pharao nfts from epoch zero and accidentaly i send two nfts to the same staking adress. The seecond nft never returned to my wallet
```

**Comment by adamunchained** [comment]
@flyingrabbit-lab - this seems to be related https://github.com/soonaverse/soonaverse-dao/issues/1144

**Comment by flyingrabbit-lab** [comment]
Nft is credited back now!
