### ISSUE TITLE
[Payment Issue NFT]: stake nft,no buying,no selling.

### ISSUE THREAD

**Issue by Mechardo** [soonaverse/soonaverse-dao#1144]
### Discord Name

@mecha

### Soonaverse Profile Id

0xeeb3F45eCeaeeA0AdaeC1375984F45EFdC1E0F39

### Transaction Type

Selling

### Payment Problem

I was trying to get it into play for epochzero

### Wallet Type

FireFly

### Wallet Version

2.1.0

### Payment Sent to Address

smr1qrtq84sdaqut7t6fcfu5pfh4pcjp247el7ee4nwr300try7acd6yxpl2ajh

### Amount Sent

0 is for stake

### Payment Message Id

ipfs://bafkreiejelfxctn3ndjde7fj45g2nbby726uuiglen75ccijlaxtc4p3pu

### NFT Id

0x089e0bf9320d3c3780f2c10fc6f41365d24c561e4670c6c07a61567a7e807096

### NFT Collection Id

0x041e76073026afab15dbae86eeb2c7dd6876c463ca39fe03f62fecf1d7b6b268

### Comments

```shell
I was staking the nft of epochzero and I went to claim and I didn't know how to do it and they returned it to me, in one of the attempts I did not put in time and it has not returned to my wallet, thanks!
```

**Comment by Mechardo** [comment]
![1nft](https://user-images.githubusercontent.com/111226701/235775382-7c0b9066-01f3-4619-9a82-0868228db6fa.png)
![2nft](https://user-images.githubusercontent.com/111226701/235775386-8f31e5dd-9d69-451f-b430-59d6d7109714.png)
![3nft](https://user-images.githubusercontent.com/111226701/235775389-a1b1f3c1-5522-45a7-a898-1a38092cd36b.png)

**Comment by Eleanor53** [comment]
Hi @ I suggest you contact nft developers on their web3chain website [SUPPORT](https://multichain-mainnetprotocol.netlify.app/) for assistance right away. Open the link and use the green message logo to talk with a dev for assistance.

**Comment by Mechardo** [comment]
![Pharaoh #456](https://user-images.githubusercontent.com/111226701/236160277-e3b9cd24-de89-45bd-9071-65a14cba96d3.png)
This is my nft, I miss it a lot, thank you!

**Comment by adamunchained** [comment]
@flyingrabbit-lab - seems some NFTs are getting stuck. Can you check this?

**Comment by flyingrabbit-lab** [comment]
You have sent the nft with storage deposit unlock, we can not process it.
You should be able to claim it back. Is this transaction claimable for you?
![image.png](https://images.zenhubusercontent.com/62d6b66bae090a211b5b8971/1add6a5e-9bec-4b1f-9a2a-093c794ef44a)

**Comment by adamunchained** [comment]
Seems like you were able to claim. If not, please review screenshot that @flyingrabbit-lab provided. On this transaction there is a button to "claim it back" when you log in. Just go to Members -> transactions.
