### ISSUE TITLE
[Payment Issue Token]: 

### ISSUE THREAD

**Issue by ThoKaWi** [soonaverse/soonaverse-dao#1145]
### Discord Name

Thokawi#4127

### Soonaverse Profile Id

0x8410708761868aafa7f18920310be1636a99d4c6

### Transaction Type

Staking

### Transaction Source

Staking Reward

### Payment Problem

I have now sent a NFT to the address generated by Sonnaverse to stake it (Pharaoh # 2520): smr1qz25nd9em362xeffnu3tm74la666a6r------ Now it's in my Fireflywallet as 'Sent' but doesn't show up anywhere and in Sonnaverse it says 'Processing' under the associated transaction.  Where is it? How can I get hold of it again?

### Wallet Type

FireFly

### Wallet Version

2.1

### Payment Sent to Address

smr1qr7jvna5fmlqcpw4vqdvjyxr2f9x85x5qpeyejg2ccxk5zltt5pju2gcm3p

### Amount Sent

0,1622 SMR + NFT 0xf1a9f2759d0acc8b4b279e20517dc1940dd6e3cd5962e08e9e41ff2dcbdf2525

### Payment Message Id

0xf1a9f2759d0acc8b4b279e20517dc1940dd6e3cd5962e08e9e41ff2dcbdf2525

### Comments

```shell
Sent NFT from Adress smr1qp7uee62qgrwukd5peahz6k5rtqy89vupe83gqvjwymtdwwnlp8kgquz3qu
to the sonnaverse adress smr1qz25nd9em362xeffnu3tm74la666a6ryu835qk9re99fm0gm0f4cjwpu5d6 to stake my NFT. 
The NFT is now sent, but not staked at Soonaverse.
```

**Comment by adamunchained** [comment]
@flyingrabbit-lab - another one https://github.com/soonaverse/soonaverse-dao/issues/1144

**Comment by flyingrabbit-lab** [comment]
Issue identified, will be credited back today.

**Comment by flyingrabbit-lab** [comment]
Nft is credited back now!

**Comment by ThoKaWi** [comment]
is credited back. Thx. 
But - tried to stake him again - sonnaverse 'Stake NFT' - copy address - sent deposit via firefly to this address. But it is shown 'Unclaimed'. No staking is possible. The same with my other Pharaos. Why ??

**Comment by flyingrabbit-lab** [comment]
> is credited back. Thx. But - tried to stake him again - sonnaverse 'Stake NFT' - copy address - sent deposit via firefly to this address. But it is shown 'Unclaimed'. No staking is possible. The same with my other Pharaos. Why ??

If I see it correctly, you have sent your nft with storage deposit return unlock. We can not accept anything with storage deposit return unlock.
https://explorer.shimmer.network/shimmer/transaction/0xcf829a6aeb051fb713012fdf51fbc5a8a8cc32197b97fb956ad8c1f54440a7d1

**Comment by ThoKaWi** [comment]
What have  i to do that you reject them ?

**Comment by flyingrabbit-lab** [comment]
When sending the nft pls gift the storage deposit.

**Comment by ThoKaWi** [comment]
But the nft is no more on my wallet - how ca i send it ?

**Comment by ThoKaWi** [comment]
The nfts were send to the following addresses:smr1qrqsfhaagu4f7t05va36clp8lnvvwf7yldty9j8wgwuxqr4p46wt7rjvk3j
smr1qz8qvz8lh3htj775ct46q4rftttmu9mfkk37vvfwh2p220hewxdtkc9w2m9
smr1qzkcavv2t3m3rrxefj638uselyqn8weztycl6eapcfwxfrx3txj7u3vrkm0
smr1qqc2dmgcfcqpm9y33ucvazfhnjlamfpummg4yh64kyefyyvxckxwjd9xhd6
smr1qq4antshavkv7gk8v3dsf8ng2a6zzqxzes7gtrdrq563vvrmm4vj67qltk7
smr1qzx02ak5lm8mq44zt8es4jk274dw7lttt50q95aduafvdtq9xwvz2w79ra7
smr1qp9khvd6cha3mxefa5tkfmcmwy4c0f09kgjv6wmfhhq4l9wvuxnsg69dj0u
smr1qrw5zpmr2e8qeemq9qt0jc9v2al36dqfnar2rzvknzeauwg5jjk85au4q5r
smr1qqktygrnsfpwu6t2l7yzjsyyt2qzmhg69emtqsmu8527ldk26ugmyyh9wkh
smr1qr8dm4y9dxsmlyr0s706gh9le4k6vpaz7zh29zvd0r5q0fdvdpyzxgmumf4
smr1qqrfqugzr63q9mna53fatz5fr385f40kug4z2y4aew4vch9xew3ws4us5zh
smr1qqjaac4qgwersfyj66zpssmuhp0l3qal97nflkvvm95xvjxuq5quwrvkmmz
smr1qzyhe9mf6hk93f43gwjhg8zyp606x02kve0l93dtg9j6mahuhvdkzhclrj9
smr1qp7peezpvlpyllflkh4wwumkvlmqyzrme4n04unmar8g2m6vkflvkmqd3cz

**Comment by flyingrabbit-lab** [comment]
Ah, I understand it now. We can not credit these back as you send it with storage deposit unlock and we don't have the funds to unlock them. You should see claimable credit transactions under your profile. Claim back these nfts via sending funds and then re stake them without storage unlock.

**Comment by ThoKaWi** [comment]
Where do i find 'claimable credit transactions' in my firefly wallet ?

For example:
Pharaoh 748 is laying on 
smr1qp7peezpvlpyllflkh4wwumkvlmqyzrme4n04unmar8g2m6vkflvkmqd3cz

If i send the given deposit - 169,1 glow - to this adresse - would that be the solution to get this nft back ?

**Comment by flyingrabbit-lab** [comment]
No, pls look under your soonaverse profile.
https://soonaverse.com/member/0x8410708761868aafa7f18920310be1636a99d4c6/transactions
After you login you should see claimable credits.

**Comment by ThoKaWi** [comment]
Hm, i find many transactions and some credits named 'Non Transferable Claim locked'
When i activate these: *Refund blocked funds  Total available tokens to refund"
But there are no claimable credits

**Comment by adamunchained** [comment]
Can you please provide screenshot?

**Comment by ThoKaWi** [comment]
![Bildschirmfoto 2023-05-10 um 16 03 09](https://github.com/soonaverse/soonaverse-dao/assets/132392255/4f9877bb-3e8c-4ea5-a7b7-588ac4ccfe9f)
![Bildschirmfoto 2023-05-10 um 16 03 34](https://github.com/soonaverse/soonaverse-dao/assets/132392255/402a0062-b89a-4cfb-84ef-4614155a4c19)

**Comment by ThoKaWi** [comment]
Hello Adam, 
tomorrow starts the staking of this Nft's. 
Please give me a hint whats to do, that the nfts can take part

**Comment by flyingrabbit-lab** [comment]
The UI is misleading, we will update it. For now, just hit Confirm and generate address and sent the requested tokens. This way the nft will be refunded.

**Comment by ThoKaWi** [comment]
Thanky. But:
The above shown pic is only guilty for the transaction 5/8/23 7:44. Pharaoh 2520 - which was still staked

When i activate all other "Non Transferable  Claim Locked"

![Bildschirmfoto 2023-05-10 um 20 45 32](https://github.com/soonaverse/soonaverse-dao/assets/132392255/48716efe-57ad-4f17-a131-1515a1ef4af8)

What can i do with the other 14  Pharaohs which i send to 
smr1qrqsfhaagu4f7t05va36clp8lnvvwf7yldty9j8wgwuxqr4p46wt7rjvk3j
smr1qz8qvz8lh3htj775ct46q4rftttmu9mfkk37vvfwh2p220hewxdtkc9w2m9
smr1qzkcavv2t3m3rrxefj638uselyqn8weztycl6eapcfwxfrx3txj7u3vrkm0
smr1qqc2dmgcfcqpm9y33ucvazfhnjlamfpummg4yh64kyefyyvxckxwjd9xhd6
smr1qq4antshavkv7gk8v3dsf8ng2a6zzqxzes7gtrdrq563vvrmm4vj67qltk7
smr1qzx02ak5lm8mq44zt8es4jk274dw7lttt50q95aduafvdtq9xwvz2w79ra7
smr1qp9khvd6cha3mxefa5tkfmcmwy4c0f09kgjv6wmfhhq4l9wvuxnsg69dj0u
smr1qrw5zpmr2e8qeemq9qt0jc9v2al36dqfnar2rzvknzeauwg5jjk85au4q5r
smr1qqktygrnsfpwu6t2l7yzjsyyt2qzmhg69emtqsmu8527ldk26ugmyyh9wkh
smr1qr8dm4y9dxsmlyr0s706gh9le4k6vpaz7zh29zvd0r5q0fdvdpyzxgmumf4
smr1qqrfqugzr63q9mna53fatz5fr385f40kug4z2y4aew4vch9xew3ws4us5zh
smr1qqjaac4qgwersfyj66zpssmuhp0l3qal97nflkvvm95xvjxuq5quwrvkmmz
smr1qzyhe9mf6hk93f43gwjhg8zyp606x02kve0l93dtg9j6mahuhvdkzhclrj9
smr1qp7peezpvlpyllflkh4wwumkvlmqyzrme4n04unmar8g2m6vkflvkmqd3cz

**Comment by adamunchained** [comment]
@ThoKaWi - apologize for the delay. We've just released a fix that will show the "claim" button within the modal. There was an UI issue that stopped showing it. It should be in production within next one hour.

You can go ahead and claim back all these transactions:

<img width="1326" alt="Screenshot 2023-05-12 at 6 55 06 AM" src="https://github.com/soonaverse/soonaverse-dao/assets/130610/b6798494-0898-41c2-95e4-56ea5b061337">

**Comment by ThoKaWi** [comment]
Hello Adamunchained, 
thank you very much. 
The list was shown as an example, how it looks like in my transaction. 
Thank you for changing this 7 transaction but the problem belongs as written before to 14 nfts.

the following have the same problem and i would be happy if you would release a fix with the 'claim'button too.

![Bildschirmfoto 2023-05-12 um 18 26 49](https://github.com/soonaverse/soonaverse-dao/assets/132392255/c95724fb-dd45-44d6-8ed7-7af96837e249)
![Bildschirmfoto 2023-05-12 um 18 27 13](https://github.com/soonaverse/soonaverse-dao/assets/132392255/47a0763c-844b-4315-a356-45a53ef2cf93)

![Bildschirmfoto 2023-05-12 um 18 28 04](https://github.com/soonaverse/soonaverse-dao/assets/132392255/e0e3b95b-f8ca-4395-91ae-17d5465782b8)

![Bildschirmfoto 2023-05-12 um 18 29 55](https://github.com/soonaverse/soonaverse-dao/assets/132392255/38402589-ab00-4dae-b19d-52b6bc9efb80)
![Bildschirmfoto 2023-05-12 um 18 30 36](https://github.com/soonaverse/soonaverse-dao/assets/132392255/260f3563-3e02-4162-b2df-a8a823b66947)
![Bildschirmfoto 2023-05-12 um 18 31 22](https://github.com/soonaverse/soonaverse-dao/assets/132392255/36fb8f60-e5e3-4b7d-9f2e-ed2e26bce5e6)

![Bildschirmfoto 2023-05-12 um 18 31 02](https://github.com/soonaverse/soonaverse-dao/assets/132392255/51871f3a-c359-4859-8fc4-26caaeb57479)
![Bildschirmfoto 2023-05-12 um 18 31 45](https://github.com/soonaverse/soonaverse-dao/assets/132392255/e32a04ea-3ab2-48d7-8929-a884e4ad2da7)

**Comment by adamunchained** [comment]
We didn't change transaction. It was just an UI issue. You should see same for other transactions if they're claimable.

**Comment by ThoKaWi** [comment]
You are right - sorry. 
But there is one exception:
Nft 1102 is still missing. 
![](https://user-images.githubusercontent.com/132392255/238028305-c95724fb-dd45-44d6-8ed7-7af96837e249.png)

Could it be the following - i'm not able to claim ..?

![Bildschirmfoto 2023-05-12 um 20 40 37](https://github.com/soonaverse/soonaverse-dao/assets/132392255/ee118857-24d2-4e47-82f6-8b378ffddda3)
![Bildschirmfoto 2023-05-12 um 20 41 07](https://github.com/soonaverse/soonaverse-dao/assets/132392255/900c5c97-a183-4a8e-94cf-1fa783ecb57e)
![Bildschirmfoto 2023-05-12 um 20 42 44](https://github.com/soonaverse/soonaverse-dao/assets/132392255/e75d6497-0514-477e-9625-1fdbfd4afa47)

**Comment by ThoKaWi** [comment]
When i want to confirm i get the info 'transaction already confirmed. 
On the other hand i'm not sure whether this is the transaction of the missing 1102

**Comment by flyingrabbit-lab** [comment]
We are fixing it now, soon you will be able to claim 1102 again.

**Comment by flyingrabbit-lab** [comment]
You should be able to claim now.

**Comment by ThoKaWi** [comment]
It worked. I now have all my pharaohs back and was able to stake them all for 52 weeks. I would like to thank you very much for your support. Help and support

**Comment by ThoKaWi** [comment]
It worked. I now have all my pharaohs back and was able to stake them all for 52 weeks. I would like to thank you very much for your help and support

**Comment by adamunchained** [comment]
great!
