### ISSUE TITLE
[Payment Issue NFT]: 

### ISSUE THREAD

**Issue by kAruZo18** [soonaverse/soonaverse-dao#1151]
### Discord Name

kAruZo#8726

### Soonaverse Profile Id

0x9C341B6d2BD15Cf391396f071EA0fc251DCd3925

### Transaction Type

Buying

### Payment Problem

Try to stake 2 Pharaoh NFT and don´t gifted the storage deposit

### Wallet Type

FireFly

### Wallet Version

Firefly Shimmer 2.1.0.

### Payment Sent to Address

smr1qp9ryqfrjr3d660w00p6c8gju0kd3j3wn3rt3u3atmmka7287eku5v2p7al and smr1qzhd2fxjr2lpnr3hv62qf7tzjf6djamtf3esaul64ku6qnmma9gkjksxljv

### Amount Sent

Pharaoh NFT 1277 + 3526

### NFT Id

0xfb9ce594129c96570c78055237f563b50ba5e3ba3cc6084e56039d18b0591fa5 and 0x39c413794256eb4a2832355a4086b8eb62e5137fbc0bfc09be23cfe9f1a1b7a5

### NFT Collection Id

0x041e76073026afab15dbae86eeb2c7dd6876c463ca39fe03f62fecf1d7b6b268

### Comments

```shell
Hey,

Try to stake 2 Pharaoh NFT and don´t gifted the storage deposit. Thank you for your support.
```

**Comment by adamunchained** [comment]
You can go to members -> Transactions and claim it back. Click "Claim locked" on the transaction.
