### ISSUE TITLE
[Payment Issue Token]: 

### ISSUE THREAD

**Issue by Myhouses07** [soonaverse/soonaverse-dao#1154]
### Discord Name

@AutoFlowIn#4661

### Soonaverse Profile Id

0x582EF1D2aA6BA24E9EE9ebfeCBbf8B309335ed4c

### Transaction Type

Selling

### Transaction Source

Token Exchange

### Payment Problem

Even I send IOTA to appeared address for selling iota to swap shimmer but stuck in the indicated wallet and never came back in wallet even not trading properly.

### Wallet Type

TanglePay

### Wallet Version

1.5.4

### Payment Sent to Address

iota1qrqwd50n273fk60nhpstzqya7jguy35ywn4cu3tvruezvylrf0ths5wv26l

### Amount Sent

40 Mi

### Payment Message Id

6b08127cab521a4e60feda3f24d13c88159c088810f959c75f392bb2fabe42c7

### Comments

```shell
plus, I cannot see any history related to 40mi orders from soonaverse page on “orders”.

please take a look into it and help me to find 40 mi.
```

**Comment by adamunchained** [comment]
There was a delay on the network and it has caused the funds to be stuck.  40 Mi should be refunded to original address now.
