### ISSUE TITLE
New Discord handles

### ISSUE THREAD

**Issue by epochzer00** [soonaverse/soonaverse-dao#1159]
Discord handles no longer include the # sign, this causes an issue when trying to update your user profile as Soonaverse forces the # in the format logic.

The end result is our scripts are no longer able to verify Discord/Soonaverse users

**Comment by adamunchained** [comment]
Issue has been fixed. Sorry for the delay, we've been heavily focused on open sourcing effort so bug fixing was slightly delayed.
