### ISSUE TITLE
Initial connection to TanglePay wallet results in an error

### ISSUE THREAD

**Issue by zmxzoe** [soonaverse/soonaverse-dao#1160]
Every time I connect to the TanglePay wallet for the first time, I encounter an error. However, when I refresh the page and connect again, it works fine.
![image (1)](https://github.com/soonaverse/soonaverse-dao/assets/57786465/0f79c4ba-d08f-473a-ad54-3b1af5b51890)

**Comment by adamunchained** [comment]
Hi @zmxzoe - this is fixed.
