### ISSUE TITLE
TanglePay wallet is unable to support SoonVerse NFTs with withdrawing and selling

### ISSUE THREAD

**Issue by zmxzoe** [soonaverse/soonaverse-dao#1161]
1When clicking "Withdraw NFT," only the MetaMask option appears.
2TanglePay does not appear when trying to sell NFTs.

https://github.com/soonaverse/soonaverse-dao/assets/57786465/b222aedb-8f65-4a5f-89a7-5caa680efed4

![image (35)](https://github.com/soonaverse/soonaverse-dao/assets/57786465/6b9be768-92c6-45b5-b654-b27198599a49)

**Comment by adamunchained** [comment]
You can just go on your profile. Validate your TanglePay address as your SMR address. Once you do that you'll be able to withdraw the NFT.
