### ISSUE TITLE
Award Info menu only displaying one token.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#1165]
When creating a new award, only one token is displayed in the Award Info menu when clicked, preventing users from funding awards with other tokens.
On Soonaverse:
![image](https://github.com/soonaverse/soonaverse-dao/assets/38050901/78ec57c3-737a-4864-9f53-995cd1488ae6)

On Wen:
![image](https://github.com/soonaverse/soonaverse-dao/assets/38050901/e41b6eb4-8867-4c0f-a1af-31f39e8164a5)

**Comment by adamunchained** [comment]
being fixed in https://github.com/soonaverse/soonaverse-dao/issues/1170

PR ready for deployment once new index created on build-5/core:  https://github.com/soonaverse/app/pull/14
