### ISSUE TITLE
displaying issue / refreshing issue

### ISSUE THREAD

**Issue by celarium3945** [soonaverse/soonaverse-dao#1168]
**Describe the bug**
on different pages, often displayed data are missing 

**To Reproduce**
1. Go to 'my profile'
2. Click on 'IOTA/SMR'
3. Go to 'my profile'
4.  data are no more present. see screenshot :

**Expected behavior**
whatever page we came from data should be always well displayed

**Screenshots**
![image](https://github.com/soonaverse/soonaverse-dao/assets/103221824/003b4340-b426-416d-ad91-91b1eb1362a0)

**Desktop (please complete the following information):**
 - OS: laptop windows[
 - Browser  : microsoft edge

Other info : I often been disconnected

**Comment by siouxWaits** [comment]
Same behaviour on Windows pc / Firefox browser.

**Comment by adamunchained** [comment]
FYI - we've delivered few performance fixes over past few days. 

Please keep reporting further issues under here so we can investigate and fix further.

**Comment by adamunchained** [comment]
Closing as most performance issues should be fixed. Feel free to re-open this issue if otherwise.
