### ISSUE TITLE
LOVE Rewards through Award - no tokens to choose from

### ISSUE THREAD

**Issue by Bambi666** [soonaverse/soonaverse-dao#1170]
Hello there,

I would like to create an award giving out LOVE to our Bambiota - Holders. Unfortunately when creating the award and choosing the rewarding token, no tokens show up. Just one type of thing to select from which is a purple book, not sure what it means. I will attach
a screenshot!

![awarderror](https://github.com/soonaverse/soonaverse-dao/assets/121830123/02402aba-e2ab-4af9-8193-5fc64b95ba88)
 
Searching function also doesn't work, just shows this book.
 
Looking forward for your reply and help.

Love,

Bambi

**Comment by adamunchained** [comment]
@flyingrabbit-lab - can you fix please build-5/core to support .getAllTokens(). Right now subsequent query runs into no index issue. See my change in this PR: https://github.com/soonaverse/app/pull/14

**Comment by adamunchained** [comment]
This has been fixed and released into prod.

**Comment by Bambi666** [comment]
Hey Adam,

it is possible now to choose a token but only some and my LOVE token is not showing up, also without search function not to be found...

Bambi

**Comment by adamunchained** [comment]
Your token have to be minted. Non minted tokens can't be used for awards.

**Comment by Bambi666** [comment]
Okay, I will do normal airdrops then :)

Much Love <3

Bambi
