### ISSUE TITLE
Current state of Soonaverse

### ISSUE THREAD

**Issue by ILLUMINATIOTA** [soonaverse/soonaverse-dao#1171]
Hello Soonaverse-team,

we are a liitle worried about the current state of Soonaverse. We have several bugs we would like to report. 

1. Token Prices/Price change: For MIOTA/SMR and SOON/SMR trading pair no price or MCAP is showing up in Token exchange section.
2.  Price change of tokens: % wise price change isn't showing up properly, somethimes even in unreal number >100%
3. A lot of times we have to refresh pages to see the actual space, sometimes space showing and clicking on it leads to another space
4. Member list: The member list isn't sorted by latest members anymore, it is just random
5. Not only that but the search function for members isn't working anymore
6. Everything in general seems a bit buggy now

We are sure this is due to the change of Soonaverse going open source now and will resolve within the upcoming weeks!

Kind Regards,

ILLUMINATIOTA

**Comment by adamunchained** [comment]
1 - this is just related to no trading. I can see those values right now. Can you clarify?
2 - well it can be above 100%. Why is that an issue?
3 - can you provide an example please? 
4/5 - working on a fix. See subsequent comment. 
6 - we are on it. See: https://github.com/soonaverse/soonaverse-dao/issues/1168 please report more issues regarding performance there.

**Comment by adamunchained** [comment]
@flyingrabbit-lab 

Can you please investigate 4-5:

This seems to be related to function onMemberScroll() in data.service.ts:
- first it looks like handler functions are not supporting paging. I get an error. 
- second when algolia ids are passed in to filter the result "searchIds" are ignored.

**Comment by ILLUMINATIOTA** [comment]
1. They were showing some days, some days they don't. They are showing now, you are correct.
2. Above -100% or in a mathmatical correct way below -100% is what we meant to say. Other tokens daily change percentage was just not correct, for example a token dropped by a lot but was showing high green numbers. We will make sure to take a screenshot next time.
3. Maybe this is a cookie-related issue and on our end. So you click on a space and it is only partly showing, sometimes the banner is missing, sometimes the space is empty and when clicking on it it leads to an empty space page. Also sometimes the space which a collection belongs to shows another space and when clicking on it it leads to the false space. Again, this might be on our end, not sure.

Thanks for fast reply and working on it!

**Comment by adamunchained** [comment]
1. They only show if there was trading today & yesterday. If there isn't any trading on those days they'll not show.
2. Please do and share it here so we can investigate, I would love to figure it out.
3. I think it might be network related. If it ever happens again, please try to record your screen with network tab open (how to open network tab in Chrome: https://developer.chrome.com/docs/devtools/network/#:~:text=%23%20Open%20the%20Network%20panel&text=Open%20DevTools%20by%20pressing%20Control,The%20Console%20panel%20opens.&text=You%20might%20prefer%20to%20dock%20DevTools%20to%20the%20bottom%20of%20your%20window.&text=Click%20the%20Network%20tab.)

**Comment by ILLUMINATIOTA** [comment]
1. What I meant is they were being traded and had buy/sell orders but MCAP, price and price change weren't showing up
2. I attach screenshot, this is from today. IOTA hasn't gained 80% vs SMR in the last 24 hours but it shows this high percentage
3. Will do

![IOTApricesoonaverse](https://github.com/soonaverse/soonaverse-dao/assets/124702141/b817e10b-a752-44b4-9c9c-93caeb8c70e0)

**Comment by adamunchained** [comment]
4-5 - Have been fixed. Thanks @flyingrabbit-lab

**Comment by ILLUMINATIOTA** [comment]
![Screenshot 2023-07-24 173122](https://github.com/soonaverse/soonaverse-dao/assets/124702141/15471bbe-de8a-4d5c-ae65-7857758741b2)

This is what we meant, only parts of the space shwoing, this resolves though every time after refreshing once or twice.

**Comment by ILLUMINATIOTA** [comment]
This is also new, seen this for the first time today. Orderbook is showing wrong (or current marketprice)

![fishorderbook](https://github.com/soonaverse/soonaverse-dao/assets/124702141/9501fe56-8830-4cec-9e42-464fb0f91d8b)

**Comment by ILLUMINATIOTA** [comment]
Often the graph doesn't show as in this example.

**Comment by adamunchained** [comment]
> This is also new, seen this for the first time today. Orderbook is showing wrong (or current marketprice)
> 
> ![fishorderbook](https://user-images.githubusercontent.com/124702141/255668483-9501fe56-8830-4cec-9e42-464fb0f91d8b.png)

@flyingrabbit-lab - can you check getPriceChangeLive @build-5/library function? it seems to incorrectly responds. Looking at last 24h of data it seems very incorrect. See screenshot with history:

<img width="1438" alt="Screenshot 2023-07-24 at 10 38 51 AM" src="https://github.com/soonaverse/soonaverse-dao/assets/130610/631be391-bc03-46f0-a7b5-defa9e0535a6">

@ILLUMINATIOTA - on it. Thank you!

**Comment by adamunchained** [comment]
> > 4-5 - Have been fixed. Thanks @flyingrabbit-lab
> 
> Search function still not quite working. Try to search for 'Satan' in ILLUMINATIOTA section, 'Samanta' showing up. We had to remove them from space and then rejoin, so we could find them and make them guardian again. Also there is a bug showing number of guardians for our space is -132. Attached screenshot.
> 
> ![Screenshot 2023-07-24 174640](https://user-images.githubusercontent.com/124702141/255642707-c431dbc7-d729-4243-8b89-ed8d7acd98d6.png)

We’ve just released another fix on this. It should behave better.

**Comment by adamunchained** [comment]
We've just deployed last improvement that should fix most issues. If there are further please let us know. If you can try to do that through a new issue as this issue is now very hard to track.
