### ISSUE TITLE
FISH Token NFT mint

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1172]
Good day Adam and Soonaverse Team,

I am currently waiting for the mint of FISH Token NFT (https://soonaverse.com/collection/0x6e9c642b5a3a5d8f4af69dfea2d726c9ebeb056e). This hasn't started minting yet. As sale starts in two days, I am a little worried I didn't leave enough time for minting process. Are my worries and concerns reasonable or will it be done by then?

Majishan

![Final](https://github.com/soonaverse/soonaverse-dao/assets/126873967/d1358f49-2168-4ea6-b99c-8384d26fd53a)

**Comment by adamunchained** [comment]
Does it show minting in progress status?

**Comment by MajishanIOTA** [comment]
Shows 'Minting (777 NFTs left...)'

**Comment by adamunchained** [comment]
We're looking into it and we'll try to fix it on Monday. There seems to be an issue with your image types for some reason and it fails to mint them.

**Comment by adamunchained** [comment]
@MajishanIOTA - this has been fixed! Collection is minting now. It was due image sizes.

**Comment by MajishanIOTA** [comment]
Nice, thank you Adam & Team :)
