### ISSUE TITLE
NFT was bought, Collection didn't have approval

### ISSUE THREAD

**Issue by Bambi666** [soonaverse/soonaverse-dao#1175]
Hello there,

I have an unusual bug here, I am sorry I am a little mad at this one, this collection was meant to be for myself only. I then decided against it and didn't give it approval but somehow someone found it in 'Pending' section and still bought it. This NFT had high personal value and is now in the hands of some random on the internet. NFTs shouldn't be available for buying if collection didn't get approval. 

Collection: https://soonaverse.com/collection/0x47f13050e277aefc4803d60e22f2132027f7fea5

![Screenshot 2023-08-01 084757](https://github.com/soonaverse/soonaverse-dao/assets/121830123/0be22087-3557-4e38-a08b-52fd18e17124)

**Comment by Bambi666** [comment]
I also just saw that the 69 IOTA didn't even arrive. Absolute catastrophic. Someone bought the NFT and I want to have it back. What happens if I 'Reject collection' now, will it get burned/ not visible?

**Comment by adamunchained** [comment]
I'll reject the whole collection. We will investigate why user was able to purchase pending collection and fix this.

**Comment by Bambi666** [comment]
I don't want it to be rejected only, this needs to be deleted.

**Comment by adamunchained** [comment]
We're not able to delete data. It's a policy. Although if it's rejected nobody can't find it anywhere so it has nearly same effect.
