### ISSUE TITLE
SMR address of space could not be changed, although it displays that the change is confirmed

### ISSUE THREAD

**Issue by AdrienAO** [soonaverse/soonaverse-dao#1176]
**Describe the bug**
SMR address of space could not be changed, although it displays that the change is confirmed

**To Reproduce**
Change SMR address and follow the process

**Expected behavior**
New SMR address is shown.

**Comment by AdrienAO** [comment]
Space we tried it with: https://soonaverse.com/space/0x68aa52ba60370573bfb9dc54630c4b9d6cd404bf/overview

**Comment by adamunchained** [comment]
I was not able to re-reproduce this. Are you sure it was just not correctly refreshed?

**Comment by AdrienAO** [comment]
I tried it again. It stated successful again, but the SMR address is still the same from the very start. If you check the space: https://soonaverse.com/space/0x68aa52ba60370573bfb9dc54630c4b9d6cd404bf/overview

And the address that hasn't changed: smr1qp8wt3cxa8re9gla9p6tjez7vgn5arycuu2zdxrkk82vxmhqwke5ctguw58
Wanted to change to this one: smr1qpghrh3lu57kpxuyucqv2c5dekvutu4sec2fqv8vqtd8wsraatekcdp7lk7

**Comment by flyingrabbit-lab** [comment]
@AdrienAO When updating the space's validated address, after the funds are received a proposal is created that has to be voted on. Your previous attempts timed out, and for your last one I see an active proposal
https://soonaverse.com/space/0x68aa52ba60370573bfb9dc54630c4b9d6cd404bf/proposals
Once that proposal has at least 60% "Yes" votes, the validated address will be changed.

**Comment by AdrienAO** [comment]
@flyingrabbit-lab Thanks! We were not aware of this - now it worked.

Maybe it would make sense to add a note that explains this process? There was no hint suggesting this.
