### ISSUE TITLE
Oops, it's in another universe

### ISSUE THREAD

**Issue by MajishanIOTA** [soonaverse/soonaverse-dao#1177]
There may be some black hole on Soonaverse absorbing some NFTs :(

This page shows up when looking at some NFT, the NFT just disappears and 'Oops, it's in another universe'. Sometimes even when clicking an NFT, NFT doesn't show up at all. Just this page.

![Screenshot 2023-08-01 124046](https://github.com/soonaverse/soonaverse-dao/assets/126873967/92b20872-1ffb-4067-883e-763d6a33c4e6)

**Comment by adamunchained** [comment]
It means NFT has been withdrawn to Tangle and it's not longer in Soonaverse.

**Comment by MajishanIOTA** [comment]
Adam, I know this is the case for withdrawn NFTs, however I am talking about available collections

FISH Token for example

or this one: https://soonaverse.com/collection/0x1b4cdc19b457578d995a49cfde27b770bbab006d

**Comment by adamunchained** [comment]
The issue happens after browser tab goes into offline mode. We'll look into this.
