### ISSUE TITLE
Full text search

### ISSUE THREAD

**Issue by nicole-obrien** [soonaverse/soonaverse-dao#220]
**Is your feature request related to a problem? Please describe.**
When trying to find an item in one of the lists, whether that is a space or a member etc. The user is only able to search by the start of the string they are trying to find. The user might not know the exact item they are searching for.

**Describe the solution you'd like**
The solution is to allow the user to search for a string that is contained by the item they are looking for. i.e. if I am searching for cheerful_nicole, I want to be able to search for nicole. Or if I want to locate all spaces containing the word DAO then I just enter DAO and many spaces would show.

Something like this would just need to be added to the search function.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Describe alternatives you've considered**
Regular expression?

**Additional context**

**Comment by humaint** [comment]
@adamunchained can we make this high priority?

**Comment by humaint** [comment]
examples what should work when implemented:

To find the Iota Whales, I first tried "IOTAWh" then "IOTA_Wh" then just "Wha", before remembering it's called "2,799 Whales". This is probably costing sales.

**Comment by adamunchained** [comment]
Yes this will be in next sprint together with advanced filters!
