### ISSUE TITLE
Date+time picker is not ideal for mobile

### ISSUE THREAD

**Issue by lazylefteye** [soonaverse/soonaverse-dao#233]
First of all, I had no issues to connect via Metamask to soonaverse.

Creating a Space was easy. 

I would recommend a clear indicator where someone can see "Create an account". I had some times to figure out, that "Join us" was the actual account creation button.

Once I wanted to create a proposal, the design to chose the time was a bit off (see picture). It would be nice to have a dynamic site.
![Designissue](https://user-images.githubusercontent.com/65918138/149211124-2c803cb7-9734-4171-a487-81c17f1a3ef4.jpeg)

Also, I don't know if that's an issue but, if i want to create a space, while i have no account, such an error appears, if I want to chose an avatar:
![Avatar thing](https://user-images.githubusercontent.com/65918138/149211314-da2af949-df33-4fe9-a6e2-761ae8fb2074.jpeg)

It shouldn't be possible to create a Space, if you have no account, except, if you show an error "No account created yet".

**Comment by adamunchained** [comment]
stale issue, it should be kept under discussion (idea/future enhancement) until we start to work on it.
