### ISSUE TITLE
[FEATURE REQUEST] Add sort by "size", sort by "trend"

### ISSUE THREAD

**Issue by PauliskoSpeed** [soonaverse/soonaverse-dao#260]
The number of DAOs is growing quickly and users might feel overwhelmed on the discover spaces page (https://soonaverse.com/discover/spaces). Sorting by "time" (oldest or recent) is already a very helpful metric when browsing for DAOs, but quite limited. 

My proposal is to extend the sorting function by
1) sort by **size** 
With size describing the total number of DAO members. 
2) sort by **trend**
With trend describing the total number of _new_ DAO members within a certain timeframe (e.g. 2 weeks). 

People browsing for new DAOs to join would have an easier time finding "large" or "trending" DAOs. 

<img width="1238" alt="Screenshot 2022-02-13 at 21 08 27" src="https://user-images.githubusercontent.com/33250723/153773703-ba66c004-d3b9-41e6-bd69-ad1b4a7a8a89.png">

Thanks and GN

**Comment by humaint** [comment]
@adamkundrat let's do the size sorting
