### ISSUE TITLE
Voting results are presented differently.

### ISSUE THREAD

**Issue by Travetown** [soonaverse/soonaverse-dao#262]
During a vote, the main page will show a different result than the vote page.

<img width="1014" alt="Bildschirmfoto 2022-02-14 um 12 54 19" src="https://user-images.githubusercontent.com/66588710/153859725-e79619b3-78cc-461c-9485-eb5465619d9b.png">

<img width="496" alt="Bildschirmfoto 2022-02-14 um 12 54 38" src="https://user-images.githubusercontent.com/66588710/153859765-3105e4e2-2ad0-4d16-9232-b70c908cc0fd.png">

**Comment by adamkundrat** [comment]
@Travetown - yeah on the proposal it's based on votes and total available votes. On the space, it it's based on total votes and people that voted.

I agree it's confusing and we should make it consistent. We'll fix this as part of our NFT release next week.

**Comment by humaint** [comment]
@adamkundrat can we just change the logic of the "space" one?

**Comment by adamkundrat** [comment]
you mean the proposal one right?

**Comment by humaint** [comment]
based on total votes and people that voted makes more sense to me

**Comment by adamkundrat** [comment]
@Gundavri - please apply same logic to calculate results that is in proposal-card! 

Please this must be properly tested! Be very careful. It's highly used.

**Comment by adamunchained** [comment]
voting will be refactored and fixed with Shimmer integration.
