### ISSUE TITLE
Better Info for Badges in Profile

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#336]
**Describe the bug**
Currently the badge info shows like this in the profile
![image](https://user-images.githubusercontent.com/44786846/156612927-1d24464c-b5ff-40ac-8d8a-53c2592fd011.png)

It was confusing for some people that the badge says Active and what that means. We know that that is that the Award is still active but for a member this is less meaningful and sometimes confusing. It would be better to put some other information here or just say 

> Awarded on:

**Comment by humaint** [comment]
working on design

**Comment by adamunchained** [comment]
stale issue, hasn't been raised again. We'll be re-doing this as part of Shimmer integration anyways.
