### ISSUE TITLE
Strange navigation / 404 errors

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#369]
**Describe the bug**
Using the "back" function leads to 404 pages

I am in https://soonaverse.com/dashboard

I inter a space:
![image](https://user-images.githubusercontent.com/77154511/156738343-f26f7b35-8710-4e6a-bcd9-8f4455c5acc3.png)

https://soonaverse.com/space/0x4975800395e33687ef0a2ee92257b161fc5f48c4/overview

From here I have the button "back discover"
![image](https://user-images.githubusercontent.com/77154511/156738504-dc5fae4a-6965-4e41-8c19-9445159d80dd.png)

which leads me back to discover spaces instead of dashboard:

![image](https://user-images.githubusercontent.com/77154511/156738621-c96dbdbe-004b-4e36-a2f2-c48a8c692f45.png)

From here I use the sidebar icon to "My overview"

I enter a space: 
https://soonaverse.com/space/0xa046b738993076ed7e83f07b555d774e6ab19501/overview

And here the back button states "back space" instead of "back dashboard"
![image](https://user-images.githubusercontent.com/77154511/156739021-ab43fbcb-7ca4-4db3-8b8f-67aea77e5b9d.png)

Using the back space button here leads to 404 error

![image](https://user-images.githubusercontent.com/77154511/156739114-f5811733-ba53-4693-9727-1e6e8f25e0b9.png)

Going back from here to "dashboard" and entering another space produces the same issue - I get the "back space" button which leads to 404 error

Browser Firefox 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamkundrat** [comment]
@humaint - could you investigate this one pls?

**Comment by humaint** [comment]
low prio, it seems quite random = should be fixed with My Overview update

**Comment by adamunchained** [comment]
stale issue, closing
