### ISSUE TITLE
Guardian approving his own award doesn't show XP

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#386]
**Describe the bug**
As a guardian if I create and approve an award then participate it doesn't immediately show the correct XP for me
![image](https://user-images.githubusercontent.com/44786846/156971476-43da2332-3cfb-470f-b9bc-5c9dc16fc60a.png)

**Comment by adamunchained** [comment]
We are moving away from XP. Closing as irrelevant.
