### ISSUE TITLE
Emoji's not allowed in description of a new space, but it just says "internal error"

### ISSUE THREAD

**Issue by buckminsterwatts** [soonaverse/soonaverse-dao#389]
Emoji's not allowed in description of a new space, but it just says "internal error"

It needs to say the error is the emoji so that it can be fixed, or the space can allow emojies.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
stale and this is not planned atm.
