### ISSUE TITLE
Enter XP for Award by XP per Badge instead of Total XP for Award

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#475]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **centercirclesolutions** March 11, 2022</sup>
Most people think in terms of how many XP do I want for each badge, not how much in total for the award. We should change the Award process to have XP entered for a single badge then show a calculated total based on the number of badges specified. This would be more intuitive for users.

XP: 2 (entered)     x     Badges:  100 (entered)     Total XP: 200 (calculated)</div>

**Comment by adamkundrat** [comment]
As part of this, please implement https://github.com/soonlabs/soonaverse-dao/discussions/351

**Comment by Debos24** [comment]
Yes - I have messed this up multiple times, i finally understood it the 5th time. Could be much more clear

**Comment by humaint** [comment]
@Gundavri pls update creating award section according to following: 

- first input will be XP per badge
- second input Number of badges

the last row calculates the Total XP = not editable, it will simply takes xp per badge * number of badges and shows the value

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A43121

![SCR-20220416-llk.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/e872c668-eec4-4031-bcda-9c8fdbb6fbc3)

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/475?planning-poker) with ZenHub @Gundavri
