### ISSUE TITLE
History should include amount and space name

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#514]
**Describe the bug**
![image](https://user-images.githubusercontent.com/44786846/160493477-6e7da6c6-5d57-406f-8a55-392ec5ff01bb.png)

**Comment by adamkundrat** [comment]
Do you see it by looking at previous item in the timeline? Royalties are on collection.

**Comment by centercirclesolutions** [comment]
If its just for the latest that's ok, but the more the consistent the better

**Comment by humaint** [comment]
I will think about showing transaction history as part of this issue

**Comment by humaint** [comment]
@Gundavri apologies for another change, pls update according to design + add amount and recipient when royalty and owner bill line (+ link to the space/member)

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3207%3A34290

![SCR-20220408-hq6.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/8b096bd4-9f51-41c1-8bd7-072bb7d6e094)

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/514?planning-poker) with ZenHub @Gundavri
