### ISSUE TITLE
NFT Marketplace Specific Member(s) Visibility

### ISSUE THREAD

**Issue by Teach91** [soonaverse/soonaverse-dao#531]
It is not visible on the marketplace that NFTs can only be bought by specific members. Or I can't find it.

Sales for specific members should not be displayed in the open marketplace.

![image](https://user-images.githubusercontent.com/102695831/160919151-28308fc9-8cc6-434b-85f5-24e0ff5317ed.png)
![image](https://user-images.githubusercontent.com/102695831/160919177-4521f42e-19db-4766-b1fa-af3ea8bebebc.png)

**Comment by Teach91** [comment]
Likewise, you could introduce another section in the profile in addition, where you also get the offers displayed (see image).
![image](https://user-images.githubusercontent.com/102695831/161078641-c64594ce-8392-4836-a0ff-f2e8f1a3add2.png)

This would solve the problem. Then you would have to hide the offers from the open marketplace for NFTs.

**Comment by Teach91** [comment]
a division into offers received and offers made would be useful

**Comment by humaint** [comment]
@Gundavri pls add new badge to the NFT that it's available only for specific users + implement logic when to show

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3405%3A36126

![SCR-20220416-lg0.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/6797d8f3-4912-4146-bacc-3309430633f5)

**Comment by humaint** [comment]
+ add a new box to the NFT detail only for this restriction 

https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=1934%3A33496

![SCR-20220416-liw.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/91c1b3ac-f563-46e7-ad8d-75d90e87bcfa)

**Comment by Gundavri** [comment]
@humaint Can you please fix the first link?

**Comment by humaint** [comment]
it has been a while since designing this one, I've found the badge here 
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=3775%3A41342

**Comment by Gundavri** [comment]
@humaint Currently we don't have this filter implemented 
![image](https://user-images.githubusercontent.com/51381939/190173537-406a0e20-30d7-436a-9953-871035566f94.png)

**Comment by humaint** [comment]
@Gundavri pls just add the badge and logic for NFT cards (similar as we have for other badges)

we will implement filters later
