### ISSUE TITLE
Change wording- Replace you are not allowed member to purchase NFT language with proposed below

### ISSUE THREAD

**Issue by gmanredmond** [soonaverse/soonaverse-dao#534]
Instead of this message below, maybe we can change the wording to something like this.  This NFT is currently involved in a transaction.   Thoughts?

![image](https://user-images.githubusercontent.com/63729477/160941858-b3c9ba2f-1f64-471e-9dd4-e5ad5fe8d27e.png)

**Comment by humaint** [comment]
@adamkundrat not sure when do you show this error but it should say rather something like "Transaction is pending. Try again later".

**Comment by adamunchained** [comment]
this part of #531
