### ISSUE TITLE
You have currently another order in progress

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#539]
**Describe the bug**
When i try to buy something on soonaverse i get the following message: "You have currently another order in progress"

**To Reproduce**
buy something with my account https://soonaverse.com/member/0x910cc0ec4ac0c3f7f39ca3ba57c6a6781951e029/activity

**Expected behavior**
buying should work

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/161137390-b886dc90-8993-4d46-8611-b7acb144a2f0.png)

**Desktop (please complete the following information):**
 - OS: w11
 - Browser chrome
 - Version latest

**Additional context**
i can create auctions, but cant mint new nfts like soonanaut. i can bid on existing auctions.
think the last thing that worked was to reserve a fixed price sell, but didnt buy.
the message appears since 2h already.

**Comment by adamunchained** [comment]
This has been fixed in new release.
