### ISSUE TITLE
'Available' shows 0 while second hand NFT's are available

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/soonaverse-dao#547]
**Describe the bug**
On a collection with second hand NFT's available 'Available' shows 0

**To Reproduce**
1. Go to 'https://soonaverse.com/collection/0xc1b9e4721c5b517509e062b9950226e9603b5864'
2. Scroll down
3. Click on 'Available'
4. There are NFT's available on the market

**Expected behavior**
Available should show the number of available NFT's as the sum of non-minted, on-auction and second hand open sale NFTs

Additional suggestions:
- 'Price starts at' should show the lowest price of any available NFT, either from minting or open market
- The on-auction filter is not available in a collection

**Screenshots**
![23053c16-65aa-4d4e-92fd-90d08bc09ab5](https://user-images.githubusercontent.com/99087735/161249678-6ac6eaa2-4b88-4667-8734-19949482e843.jpeg)

**Device:**
OsX (Chrome) and Android

**Comment by adamunchained** [comment]
@humaint - here we show available in the collection. How do we want to show available for re-sell?

**Comment by humaint** [comment]
working on destgn

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=4780%3A47386

once the mint is over we will show banner and change the available box to show how many NFT are on sale/auction

**Comment by humaint** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/547?planning-poker) with ZenHub @adamunchained @Gundavri

**Comment by humaint** [comment]
figma here https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=4780%3A47386&t=eixFM00qpg42Cinf-1

**Comment by adamunchained** [comment]
@humaint - can you provide a new link? above one does not work.

**Comment by humaint** [comment]
no longer issue, we don't use available badge. You can always see remaining NFT when collection on sale.
