### ISSUE TITLE
NFTs are gone away after upload MetaData and check some NFTs on multiple section

### ISSUE THREAD

**Issue by tccflash** [soonaverse/soonaverse-dao#568]
I uploaded 364 NFTs via CSV in the multiple tab of a SFT collection. After I uploaded all and the CSV was successfully loaded, I want to check my collection. Every time I check 3-15 NFTs the whole collection was lost. The field was empty and I have to reupload them. Only the counter goes up. See Screenshot below. 

**To Reproduce**
1. Create a new SFT Collection2. 
2. Upload some jpg
3. Upload the MetaData via CSV
4. Check some NFTs
5. After Check some NFTs (in my case between 3-15) all NFTs should be lost. --> Empty place

--> If you are quick enough you can generate the collection without checking and that should work. But I think that's not the goal of it all.

**Expected behavior**
Love to check my collection before gererate/publish.

**Screenshots**
<img width="1161" alt="Bildschirmfoto 2022-04-03 um 22 08 28" src="https://user-images.githubusercontent.com/46502426/161447906-1eef8e60-39a3-4868-bbcd-359c3446ea8a.png">

Screenshot ist after the NFTs were lost from alone.

**Desktop (please complete the following information):**
 - OS: [Newest MAC OS]
 - Browser Chrome
 - Version : Newest Mac Version

**Comment by adamkundrat** [comment]
This seems to happening. @Gundavri - can you please try to investigate this again?

**Comment by adamunchained** [comment]
This has been improved but I'll leave this open for little longer to see if the issue appears again.

**Comment by adamunchained** [comment]
Feedback from one of the users:

```I soldiered through and got it done. There are a few little bugs in there, but got through it in the end. Things like uploading a csv before downloading a template causes the upload to fail also when you change the window size the NFTs disappear from the UI. Managed to get there in the end though. Thanks for your help```

- disable upload CSV prior clicking the download template
- fix disappearing NFT once for all

**Comment by tccflash** [comment]
Ok @adamunchained. I don´t get it. I have to prepare many uploads for my project now. Everything I tried, it is everytime the same. Latest after I checked the 20th NFT all are gone and I have to reupload it now completly. Last time it was enough to reupload the CSV. 

Also I don´t understand what the user means with disable uplad CSV prior clicking the download template?
