### ISSUE TITLE
Display error when closing and reopening Checkout during the purchase process.

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#569]
**Describe the bug**
When purchasing NFT, after the order is generated and before it is completed, if you close and reopen Checkout, the display will be incorrect.

**To Reproduce**
1. Go to '[some kind of collection(May be " Generated " type)](https://soonaverse.com/collection/0xdb47fa3d6cdc14910933d0074fba36a396771bfa)'
2. Click on '[any available NFT except the first one](https://soonaverse.com/nft/0x56dbe5aeea3319921b6400c062cfc2f0581745e0)'
3. Click on 'Buy now' and Click "Confirm and Lock".
4. Metamask sign it and Order created. 
5. Let the time begin to dwindle. 
6. Close the Checkout.
7. Reopen the Checkout.
8. **You will notice that NFT becomes the first NFT of this collection and the price has changed**.

**Expected behavior**
Checkout should display information about the purchased NFT.

**Desktop (please complete the following information):**
 - OS:WIN10
 - Browser Chrome

**Smartphone (please complete the following information):**
Not tested

**Additional context**
Null.

**Comment by Gundavri** [comment]
@csxiong Can you please attach the video?

**Comment by csxiong** [comment]
> @csxiong Can you please attach the video?

I can't reproduce the problem now because I'm hitting issue #635

**Comment by csxiong** [comment]
> @csxiong Can you please attach the video?

Hi Gundavri, i made a screen-capture video to reproduce the issue. check this.

https://user-images.githubusercontent.com/86828398/166392523-1028a478-738f-4500-ba27-b870590f8851.mp4
