### ISSUE TITLE
'NFT is locked' is missleading

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#584]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/582

<div type='discussions-op-text'>

<sup>Originally posted by **tector** April  5, 2022</sup>
Today i wanted to take part in NFT Sale..

This time i was ready... my wallet was ready... i was on time...

> i clicked on BUY..
> checked the box...
> confirm the transaction in metamask..
> then i got the message 'NFT is locked' -> i thought it was locked for me, so that i can pay for it.. but seems it was locked for somebody else...
> 
> tried again maybe 5 times.. then every NFT was sold...

See my twitter post:
https://twitter.com/_tector/status/1511375998989869060 
(i also wrote that in discord support channel)

The point is:
- the message 'NFT is locked' is missleading: i thought it is locked FOR me, so that i can pay for the NFT while it is locked...
- the error message comes AFTER the transaction signing - but the NFT should be locked (for me) BEFORE transaction signing -> that would be a much nicer user experience, because you get the error before signing which is less disappointing then...</div>

**Comment by adamunchained** [comment]
Someone else can be buying the NFT. When someone else tries to by CLASSIC nft for example it gets locked for 4 minutes so nobody else can buy it. Others still see the button but if they hit order it'll throw them an error that order is locked.

Ideally, we should show lock button over it or something similar.

**Comment by humaint** [comment]
in this case, there the card button should be disabled, same as on this screen
![SCR-20220414-o3k.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/1b7e59a4-c294-40f3-893c-9a02d1dec50f)

if you open the NFT detail, it should use the same alert banner, see screen:
![SCR-20220414-o3d.jpeg](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/f5f4b2f8-9de1-4e0f-8a16-6b9b6163766b)

text should say:
"NFT is pending other member's transaction"

be carefull about the member who is actually buing the NFT, he should be able to see buy now button

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/584?planning-poker) with ZenHub @Gundavri

**Comment by adamunchained** [comment]
You know when NFT record is locked when "lockedBy" is not NULL
