### ISSUE TITLE
Unbinding and rebinding of account binding address

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#588]
### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/586

<div type='discussions-op-text'>

<sup>Originally posted by **csxiong** April  5, 2022</sup>
Given that the soonaverse uses the evm address generated by metamask as the user's identity, there is a need to unbind and rebind the binded iota address in the following cases:
- The user's seed or private key has been lost or stolen.
- After a user's wallet has been in use for too long, a large number of temporary addresses are created, resulting in a degraded wallet experience and the need to recreate a new wallet account.
- Users want to sort out their addresses.

It is therefore recommended to be able to unbind and rebind existing binding addresses.

When address unbundling is performed, some checks are needed to avoid new problems. These include:
- Check if the user now has an order that is being sold, and if so, give an error message and abort.
-  Other scenarios not yet considered....
</div>

**Comment by adamkundrat** [comment]
@humaint - please prepare UI with @Filip356258 and let's get this done this/next sprint.

**Comment by humaint** [comment]
@adamunchained do we want to allow unbinding address also for guardians/spaces?

**Comment by adamunchained** [comment]
Yes but the process there would be different. We can’t allow “one” guardian to just remove address because they could highjack the space. We need to introduce “actionable” proposals for that. Result of a proposal can trigger action within Soonaverse. These actions will support even custom SC spaces can plugin. Few examples:
- remove or add guardian
- remove wallet from the space
- and more.
