### ISSUE TITLE
Notification does not show sold NFTs

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/soonaverse-dao#590]
**Describe the bug**
Notification does not show any sold NFTs

![image](https://user-images.githubusercontent.com/99087735/161943241-3f4bf111-4e5e-41ee-a2c2-39297e6863f6.png)

**To Reproduce**
1. Sell NFT on auction or open marke
2. Click on '![image](https://user-images.githubusercontent.com/99087735/161943289-e4f6a695-91f3-424c-9897-eb3b181151b1.png)'
3. Notice that there are no notifications about the sale. Only other notifications (bids, your own buys, etc)

**Expected behavior**
Notification for sale

**Screenshots**
![image](https://user-images.githubusercontent.com/99087735/161943693-c15815ba-5a3d-4ad9-8bb7-68a350d537b2.png)
![image](https://user-images.githubusercontent.com/99087735/161943694-4c287da2-b9d1-46ed-bf8f-0f4fcc20ef50.png)
![image](https://user-images.githubusercontent.com/99087735/161943695-d2f564ed-277d-4742-818a-08afbabf74b8.png)
![image](https://user-images.githubusercontent.com/99087735/161943696-f0a05a49-b720-49d9-9619-6f8f80f87ee1.png)

**Devices:**
Mobile and OsX (Chrome)

**Comment by humaint** [comment]
@adamkundrat there is no need for design. Just simply add notification with a link to your sold NFT.

**Comment by adamunchained** [comment]
As discussed in other issue, let's review all our notifications and deliver this holistically.
