### ISSUE TITLE
Enable NFT voting

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#595]
This feature is on our roadmap and let's get it out in it's simple form. It provide utility for the NFT and opens many opportunities for creators to upsell NFTs.

- add voting type on the proposal (number of NFTs from collections)
  - user can select multiple collections
- total number of NFTs = voting weight
- show collection on the proposal (same way we show badges)

This is a relatively simple change. We have got all the UI components. 

@humaint - you want to do something special here?

---
In the future:
- I can see us enabling voting based on NFT Sets
- Voting based on a property / stats (i.e. rarity based weight)
- Much more.

### Discussed in https://github.com/soonlabs/soonaverse-dao/discussions/592

<div type='discussions-op-text'>

<sup>Originally posted by **alpharhoking** April  6, 2022</sup>
Hey there, first want to thank you for the great work you've been doing.

Not sure how it aligns with your future plans but I'd like to suggest that while creating new proposal, under "Voting type" you include an option of "Current holders" were we could choose our NFT collections.

The point of this is to open proposals for voting only to our holders. As a project, iotapes will be creating a treasury and we would love to have this option on Soonaverse instead of doing other options via snapshots.

Cheers,
Alpha Rho / iotapes.</div>

**Comment by adamkundrat** [comment]
@humaint - assigned back to me to do.

**Comment by csxiong** [comment]
I suggest that this proposal be considered carefully. From my point of view, the proposal has the following problems:

- Spaces may release multiple collections, and each NFT sells for a different price and consequently generates a different amount of contribution, so it may not be reasonable to judge based on the number of NFT's alone.
- To my mind, space's computation points (XP) would be more appropriate to be used as voting weights. And the proposal skips the usage of XP completely, which would make the utility of XP weaker, thus compromising the original design of the whole architecture.

I would therefore like to propose an alternative option for consideration.
- When the collection is created, the author can set the appropriate XP value for NFTs in the collection.
- At proposal initiation, a snapshot time can be set by the proposal initiator.
- When the snapshot time is up, soonaverse can automatically complete the NFT snapshot of this space and the snapshot of XP obtained by other means, and can make the list public.
- When voting on the proposal begins, the snapshot is used as the weight of the vote based on the XP of the snapshot.

I can't assess the difficulty of implementing a snapshot mechanism, but I think this option would make a little more sense and would be a relatively minor adjustment to the existing mechanism.

**Comment by csxiong** [comment]
Here I would like to add a not-so-professional graphic to explain how my scheme ties together the current functions. Feel free to correct me at any time.

![soonaverse](https://user-images.githubusercontent.com/86828398/162120563-6d47b444-8130-47cc-8f65-b08ec0858cb2.png)

**Comment by adamkundrat** [comment]
Thanks @csxiong for the feedback and proposal above. Let me think about this and come back to you once this issue is going to get closer final specification.

We actually have another big item to figure out and it’s the legal side of this. We’re currently working on that.

**Comment by adamunchained** [comment]
Waiting for new Hornet participation plugin. Once ready we will fully adopt it and support onchain voting as defined by participation plugin.
