### ISSUE TITLE
NFT PNG displays animation preview

### ISSUE THREAD

**Issue by pxdg2** [soonaverse/soonaverse-dao#608]
**Describe the bug**
I own an NFT that is a PNG image. It displays fine on its own page:
https://soonaverse.com/nft/0x8b1d5e17c5335df51e2cf606644aefe3213d8b9a
But in my NFT overview it displays as if it was an animation, with that "Play" symbol instead of its preview:
https://soonaverse.com/member/0x614730e13933fb20bfb91825a03511acfeacf274/nfts

**To Reproduce**
see links

**Expected behavior**
To see the image preview like on my other NFTs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X 12.2.1
 - Browser Firefox
 - Version 98.02

**Smartphone (please complete the following information):**

**Additional context**

**Comment by centercirclesolutions** [comment]
Looks like this is also happening for jpg images as well
https://soonaverse.com/collection/0x8162a7f08de007825ad232def386d10b1704f961
https://soonaverse.com/collection/0x3415dfaf760ef10604ca14a718508af5db9a02b8
