### ISSUE TITLE
Inaccurate display of order prices

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#627]
**Describe the bug**
When the order price exceeds 1G and the actual amount of the order is accurate to a single digit, the order amount is only displayed to two decimal places in G. This creates a payment obstacle for users who do not use the deep link but use manual payments.

**To Reproduce**
1. Create an order with a price of 1111Mi.
2. You will see that the order price is shown as 1.11G.
3. If the user is unable to make a deep link payment (e.g. using another computer to make the payment), he will have to guess what the actual amount is, which may result in multiple failed payments.

**Expected behavior**
Please show the actual price of the order in full and precise detail.

**Comment by adamunchained** [comment]
I think we need to improve how we distinguish Mi/Gi overall. This has been raised few times. @humaint / @Filip356258 - please have a chat about this.

**Comment by humaint** [comment]
@humaint I don't think this needs any major design change, this is just a simple rounding issue when displaying the value - we cant show 1.11 Gi when price is actually 1.111 Gi

**Comment by humaint** [comment]
i would just remove the rounding functionality when showing Gi instead of Mi

**Comment by adamunchained** [comment]
this has been resolved in new release as we no longer show units and always MIOTAs with 6 decimals.
