### ISSUE TITLE
Add API Endpoint for Space Members

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#631]
**Describe the Endpoint**
A user needs to have a full list of their members for a space. Please provide an API endpoint for this.

**Comment by adamunchained** [comment]
Lets expose the list of space members within soonaverse-lib

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/631?planning-poker) with ZenHub @boldizsar-a-mezei
