### ISSUE TITLE
The list of members of a space does not automatically show the remains at the bottom

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#633]
**Describe the bug**
check this space [Rasa NFT Park](https://soonaverse.com/space/0x1c38f9a01e1399d42c970a3f27a8cbbc4e6a4ba6/members)
It has more than 100 members, but only 50 can be displayed. When the page is pulled to the bottom, it does not automatically fetch and display the next batch of members.

**To Reproduce**
It can be reproduced without a detailed description.

**Expected behavior**
All members are displayed properly.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Edge, Chrome

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/633?planning-poker) with ZenHub @Gundavri

**Comment by adamunchained** [comment]
This must be a simple issue with infinetscroll angular module.

**Comment by adamunchained** [comment]
This is fixed in upcoming release. It works in wen.soonaverse.com
