### ISSUE TITLE
Re-open checkout does not work

### ISSUE THREAD

**Issue by humaint** [soonaverse/soonaverse-dao#635]
![SCR-20220416-l1z.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/4b953676-417f-4fee-96c8-fc048c11109c)

- try to buy NFT
- lock the transaction
- refresh the page
- clcck open checkout at the popup

->it should open the popup again, not it doesnt do anything

**Comment by humaint** [comment]
@Gundavri you can open the checkout popup based on these steps?

try to buy NFT
lock the transaction
refresh the page
clcck open checkout at the popup
->it should open the popup again, not it doesnt do anything

**Comment by adamunchained** [comment]
<img width="2340" alt="Screen Shot 2022-05-03 at 4 46 51 PM" src="https://user-images.githubusercontent.com/130610/166599028-c842f255-4007-412d-97ac-f0d19122cfe9.png">

This might be related.  It's an issue with logic. I'll fix this.

```    let nft: Nft | undefined = await firstValueFrom(this.nftApi.listen(t?.payload.nft));
    const collection: Collection | undefined = await firstValueFrom(this.collectionApi.listen(t?.payload.collection));
    if (collection?.placeholderNft) {
      nft = await firstValueFrom(this.nftApi.listen(collection.placeholderNft));
    }```

**Comment by Gundavri** [comment]
@adamunchained I'm getting the same errors 
![image](https://user-images.githubusercontent.com/51381939/168604135-5484ca6b-a1c4-4582-952e-3776ec9812e7.png)
