### ISSUE TITLE
Reputation chart axis 

### ISSUE THREAD

**Issue by WillHawkMuc** [soonaverse/soonaverse-dao#657]
**Describe the bug**
The x-axis of the reputation chart shows a wrong max. value.
In that example the total reputation is 41, while the chart shows 30 as maximum value.

**To Reproduce**
Open Profile 'AxolotlAffe' and check chart vs. reputation value

**Expected behavior**
Show correct max. value on axis

**Screenshots**
![19-04-_2022_09-37-53](https://user-images.githubusercontent.com/75979295/163951586-5fa60844-7fa9-47d4-8652-75e076ffe3d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/657?planning-poker) with ZenHub @Gundavri
