### ISSUE TITLE
Enable proposal donut chart

### ISSUE THREAD

**Issue by humaint** [soonaverse/soonaverse-dao#660]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A34483

![SCR-20220420-f8j.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/ec19b575-57bf-4a1d-956f-2e67f0dab463)

**Comment by humaint** [comment]
use tooltip when more options available, see here https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A34483

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/660?planning-poker) with ZenHub @Gundavri
