### ISSUE TITLE
Spanish bug

### ISSUE THREAD

**Issue by sexypotato-wagmi** [soonaverse/soonaverse-dao#661]
Hi guys, there's a bug in the spanish version. More than a bug is related to design/UX.

![Soonaverse bug](https://user-images.githubusercontent.com/100204340/164239252-fb3e866a-8313-4853-9141-d9b9f6b9226d.JPG)

**Comment by humaint** [comment]
@Gundavri  pls make sure that the text fits the button = it needs to be wider in this case
