### ISSUE TITLE
Proposal don't show results

### ISSUE THREAD

**Issue by tccflash** [soonaverse/soonaverse-dao#678]
I created a new proposal. After some people voted, there are no results displayed yet.

![image](https://user-images.githubusercontent.com/46502426/164996118-7abd84d5-cda6-47d7-b08e-75860224c843.png)

**Comment by adamunchained** [comment]
Can you please provide more information about the proposal? Which one had this issue?

**Comment by tccflash** [comment]
Hi Adam. Here is the direct link to the proposal. Hope that helps.

https://soonaverse.com/proposal/0x743d012062f424319a6a45d9dfe15a52b19d1ee9/overview

**Comment by adamunchained** [comment]
Proposals will be reworked with Shimmer integration.
