### ISSUE TITLE
Faulty Language Settings 

### ISSUE THREAD

**Issue by WillHawkMuc** [soonaverse/soonaverse-dao#680]
**Describe the bug**
Web site language settings prefer browser default (German) while dropdown has different preselection (English)

**To Reproduce**
* Open website in browser with German default setting
* Check Language dropdown

**Expected behavior**
* Language dropdown shows same language as website

**Screenshots**
![25-04-_2022_10-15-32](https://user-images.githubusercontent.com/75979295/165049314-64bd62b5-e418-42de-9f48-e646e20433b2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Latest

**Comment by Gundavri** [comment]
@adamunchained @WillHawkMuc I could not repeat even after changing my browser default to German. Maybe you have google translate turned on?
