### ISSUE TITLE
Proposal participation requirement does not change to match voting type 

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#683]
If I do a proposal with XP Reputation - Space, and I don't have any XP in the space, when go to the proposal it says this 
![image](https://user-images.githubusercontent.com/38050901/165245057-e36758a7-9a2b-4fdb-a998-265bc1aa34da.png)
This is the wrong error. I'm part of the space, I just dont have XP.

**Comment by adamunchained** [comment]
Proposals will be moving on chain.
