### ISSUE TITLE
Missing `CollectionID` attribute in IPFS metadata

### ISSUE THREAD

**Issue by coodos** [soonaverse/soonaverse-dao#692]
# Missing Collection Identifier

The IPFS metadata is missing collectionId

**To Reproduce**
1. IPFS metadata for any NFT take ([this moonaco captain](https://ipfs.soonaverse.com/ipfs/QmVwHVi2pFsYSV1Uj1cq9rWkeAUzMmvzua1DNbV4HbnnuM)) for example
2. The metadata lacks an identifier for the collection

**Expected behavior**
Collection identifier shall be present

**Comment by adamunchained** [comment]
I don't think I can prioritize as hotfix. It's been there since launch. We'll add it in our working branch and release probably by 20th of May (part of our sprint release).

Is this a blocker for your sale? When is it again?

**Comment by coodos** [comment]
Our sale is on 12th May, but we can add it as a property to our Metadata if that works

**Comment by adamunchained** [comment]
oh actually I think that's a great workaround for now.

**Comment by coodos** [comment]
Awesome thanks Adam!

**Comment by adamunchained** [comment]
Add "collectionId" to the IpfsService pls. Thanks!
