### ISSUE TITLE
Design for "Edit token" functionality

### ISSUE THREAD

**Issue by Gundavri** [soonaverse/soonaverse-dao#693]

**Comment by Gundavri** [comment]
Currently, I think there is not a design for editing token but there is a functionality for it in the backend.

**Comment by Gundavri** [comment]
@humaint

**Comment by humaint** [comment]
@adamunchained

I'm not sure ... what are the limitations for edit? (who, when and what you can edit?

**Comment by adamunchained** [comment]
they should be able to edit textual details such as description and titles.

**Comment by donohawitz** [comment]
@Gundavri 
token detail (guardian view) / edit button –> https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3404%3A36629
token detail edit –> https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=4319%3A45678

**Comment by humaint** [comment]
@Gundavri 
edit token button = https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=3404%3A36791

edit screen = https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=4319%3A45678
