### ISSUE TITLE
Dark Mode - Some Text Really Hard To Read

### ISSUE THREAD

**Issue by jpeeling13** [soonaverse/soonaverse-dao#695]
**Describe the bug**
On some pages, the text is really hard to read when using dark mode

**To Reproduce**
1. Go to a space
2. Click on an active Award
3. Observe the text below for the Award description

**Screenshots**
![soonaverse_award_text_nonreadable](https://user-images.githubusercontent.com/9746778/167424572-1e15de54-c35f-4ad5-b92f-1c48c47d980f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Browser [e.g. brave]

**Additional context**
Could be other places, this is just an example

**Comment by humaint** [comment]
![SCR-20220510-mra.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/6ac89b28-8738-402f-a9f6-bdf6da92e930)

https://www.figma.com/file/bCO54KioJBPG00LUX4yBLi/Soonaverse-%E2%80%94-WebApp-(Darkmode)?node-id=2736%3A42931

pls fix according design @Gundavri

**Comment by humaint** [comment]
![SCR-20220511-i98.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/a3f3727d-f6f5-43eb-9cc6-573cc5cd0752)

icons should be fixed as well
