### ISSUE TITLE
Cannot buy NFT, checkout window never changes

### ISSUE THREAD

**Issue by soonaverseHelp** [soonaverse/soonaverse-dao#698]
**Describe the bug**

When buying any NFT, the order is created but the checkout window never changes over to give the IOTA address to send the iota to.  It stays on the By checking this box, you agree with[Terms and Conditions](https://docs.google.com/document/d/1ng67fXTdINhmgkLpnbS_SkiDlZSsDAqrd13cbwXQCcQ) and Confirm and Lock screen. 

**To Reproduce**
1. Go to buy any NFT 
2. Click on "Confirm and Lock" and "Sign" for Metamask after signing with metamask, order is created popup is seen.
4. See error - No error on screen - just stuck on this screen without changing

**Expected behavior**
to see the IOTA address to copy and send to pay with a wallet

**Screenshots**
![image](https://user-images.githubusercontent.com/105317920/167720168-5a1494e5-2813-4be0-b982-797a61bb4167.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] Version 101.0.4951.54 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
Is this on wen.soonaverse.com or production? 
Can you share the link to the NFT please?

Thanks

**Comment by iota77** [comment]
production - anytime I try to buy an NFT on soonaverse.com

Example: 
https://soonaverse.com/nft/0x2e8dcb6b705b53583432b6cc2ff942d3a75b4ebe

**Comment by adamunchained** [comment]
this should have been fixed with new release
