### ISSUE TITLE
Confusing alert - Can't buy an NFT

### ISSUE THREAD

**Issue by jpeeling13** [soonaverse/soonaverse-dao#699]
**Describe the bug**
When I try to purchase a certain NFT, I get an alert/notification popup saying that I'm not allowed to purchase it but there's no further explanation as to why. Also, the grammar is slightly wrong, as it should just say "You are not allowed to purchase this NFT" or maybe "You are not a member that is allowed to purchase this NFT".

**To Reproduce**
1. Go to a space and find a collection where another user is selling an NFT that they own
2. Try to buy it
3. See strange alert message (maybe? don't know reliable conditions to make this happen)

**Expected behavior**
A clear and concise description of why exactly you can't purchase the NFT

**Screenshots**
<img width="1309" alt="confusing_alert" src="https://user-images.githubusercontent.com/9746778/168309772-7bed9ada-12c4-45d0-9425-1204f301afd7.png">

**Comment by adamunchained** [comment]
This is due restriction on sales for this NFT. Let’s improve language and disable buy now button if restricted sales to another member.

**Comment by adamunchained** [comment]
@humaint - do we still need to action this one?

**Comment by humaint** [comment]
@adamunchained wording updated:

"You are not allowed to purchase this NFT as it is reserved for another user."
