### ISSUE TITLE
Item isn't shown  on the marketplace

### ISSUE THREAD

**Issue by sagelev** [soonaverse/soonaverse-dao#700]
There is an error on the marketplace. I'm the owner of the NFT genso #4852. It can't be found on the marketplace. With different filters either. A total of 7 of my NFTs are missing
![Screenshot_6](https://user-images.githubusercontent.com/24626767/168466796-3e84233c-cd06-413b-9c9c-862aa9021bd8.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/24626767/168466797-30bdc358-b059-44de-b9eb-c8419482e094.jpg)
.

**Comment by centercirclesolutions** [comment]
Will this be addressed with the new filtering functionality

**Comment by sagelev** [comment]
No it isn't.
I'll send you 3 screenshots to point out the problem
![Screenshot_10](https://user-images.githubusercontent.com/24626767/170039090-18f20ab5-e7c4-408c-8b76-3723b59e4e61.jpg)
![Screenshot_11](https://user-images.githubusercontent.com/24626767/170039097-e9cb3d89-f397-4bb9-a217-166faa2dcfab.jpg)
![Screenshot_12](https://user-images.githubusercontent.com/24626767/170039107-9e896c67-456a-40b9-8369-e52fd8d420ce.jpg)

.

**Comment by adamunchained** [comment]
We've done further tweak on the indexation of the results. Please have a look but it seems your records are now appearing. Feel free to re-open if this is still an issue.

**Comment by sagelev** [comment]
Great work! Thanks a lot !!! @adamunchained @centercirclesolutions
