### ISSUE TITLE
Error message: Some of the NFTs are faulty while uploading 70 SFT (NFT)

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#701]
**Describe the bug**

Trying to upload ~70 badges after the CSV is uploaded it gives this error:
![image](https://user-images.githubusercontent.com/7383572/168601082-f8225fa6-21d4-41b6-a027-8eda7df9973a.png)
The error says `'-invalid media'`

The issue is that the files are uploaded in a `different order` (so not 1-70, but randomly) and the exported CSV had the filenames in the upload order of the files.

The issue was that the user prepared a CSV file with the `media` column with the names in alphabetical order

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/701?planning-poker) with ZenHub @Gundavri

**Comment by Gundavri** [comment]
There is probably some other problem. Changing order should not produce this bug according to the code and it doesn't when I test it.

**Comment by adamunchained** [comment]
Ok @antonionardella - any chance you could provide more detailed steps to reproduce? You can test this in our test account on wen.soonaverse.com

**Comment by adamunchained** [comment]
stale issue, closing. If it's still happening feel free to re-open.
