### ISSUE TITLE
Uploaded NFTs (SFT mode) disappear

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#702]
**Describe the bug**
After correctly uploading NFTs, the list of uploaded files disappears if one looks at the preview or is not quick enough to upload the CSV file.

**To Reproduce**
1. Upload ~70 NFTs
2. Click on the preview
3. File list disappears

**Desktop (please complete the following information):**
 - OS: Windows 11 and GNU/Linux (Manjaro
 - Browser Firefox, Chrome and Chromium
 - Version 100, 101

**Additional context**
Video available here for download:
https://cdn.discordapp.com/attachments/917930917710925864/974683262662373476/Soonaverse_-_Google_Chrome_2022-05-13_14-35-27.mp4

Here in the SoonLabs Discord:
https://discordapp.com/channels/892481940953915433/917930917710925864/974683266382725180

**Comment by adamunchained** [comment]
This has been fixed in upcoming release finally. It’ll come out by EOW.
