### ISSUE TITLE
Rounding NFT price causing transactions to fail

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#704]
Rounding the cost of an NFT has caused transactions to fail. Current example in support:
Displayed Cost of NFT: 1.07GI
Actual Price: 1067.300 mi

This makes the user to send an incorrect amount of funds, 1.07Gi, when it actually costs 1067.300mi. Thus, the transaction fails and the funds are returned to the user.

Expected outcome:
The user is always given the exact number of funds required rather than rounding.

**Comment by adamunchained** [comment]
We should switch to Mi everywhere on the purchasing flows (checkout modals) and only use that. Mi/Gi is confusing. Please adjust.

**Comment by adamunchained** [comment]
This has been fixed in upcoming version. We no longer use Mi/Gi units.
