### ISSUE TITLE
The language versions of Simplified Chinese and Traditional Chinese are not displayed properly

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#712]
**Describe the bug**
Currently, when selecting Simplified Chinese or Traditional Chinese in the interface, the website does not display the corresponding language version properly. Also, at the selection, the ZH-CN and ZH-TW strings need to be optimized because they are too long.

**To Reproduce**
1. Go to 'www.soonaverse.com'
2. Click on 'Language selection' Switch.
3. Choose 'ZH-CN' or 'ZH-TW'
4. The interface is still in English.

**Expected behavior**
- I hope to be able to switch and display both languages correctly.
- At the language switch, Simplified Chinese can be displayed as '简中', Traditional Chinese can be displayed as '繁中', this will solve the problem of too long strings.

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser : Chrome

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/712?planning-poker) with ZenHub @Gundavri

**Comment by Gundavri** [comment]
@adamunchained I checked and cookie changes according to the language. ZH-CN: 'cn' and ZH-TW: 'tw'. But the names of the build folders are still zh_CN and zh_TW. Do we have some kind of map in the firebase where we can change it or should I name the build folders the same as cookie?

Also, I renamed labels in the language-change component as it was written in this description but it seems odd that only those labels are in their own native languages. Should not we do the same for other languages as well?

**Comment by adamunchained** [comment]
Have you seen the scripts/build.sh? We run this.

```
#!/bin/sh
mv ./dist/soonaverse ./dist/localized
cp -r ./dist/localized/en/* ./dist/
mv ./dist/localized/pt-BR ./dist/localized/pt_BR
mv ./dist/localized/pt-PT ./dist/localized/pt_PT
mv ./dist/localized/zh-CN ./dist/localized/zh_CN
mv ./dist/localized/zh-TW ./dist/localized/zh_TW
```

**Comment by Gundavri** [comment]
@adamunchained Yes I wrote those 4 lines but I want to know how does firebase map cookie value to the built files. If I just change folder names to exactly what the cookie is, like this:
mv ./dist/localized/pt-BR ./dist/localized/br
mv ./dist/localized/pt-PT ./dist/localized/pt
mv ./dist/localized/zh-CN ./dist/localized/cn
mv ./dist/localized/zh-TW ./dist/localized/tw

**Comment by adamunchained** [comment]
It’s little blackbox to be honest. The best is to read their documentation how i18n works and use the firebase emulator to test. I’ll move this now to next sprint as the freeze is today and we ran out of time.
