### ISSUE TITLE
Token Chart axis labelling problem

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#716]
Token chart X and Y axis are unlabeled, and the numerical boundaries for the X axis look incorrect. User can't tell what '15' in this example would mean, even if it is correct.
![image](https://user-images.githubusercontent.com/38050901/169416209-10439567-2b34-474a-afad-8427ff954040.png)

**Comment by adamunchained** [comment]
this has been changed
