### ISSUE TITLE
Token Descriptions in Token Creation ambiguous

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#719]
The user isn't given an indication about where these descriptions will be seen, how they are different from one another, or whether they are just supposed to put down the same info twice. Really difficult to know what to do with the Short description box unless you have already gone through and tested the token creation process to understand what it means and where it goes.

![image](https://user-images.githubusercontent.com/38050901/169622445-39663e76-1ce4-4613-bea7-ea0535594fef.png)

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=4026%3A43001

@Gundavri can you pls add these additional hints underneath the labels
