### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by cubensos** [soonaverse/soonaverse-dao#721]
### Email

johngixxer@protonmail.com

### Company Name

Crypto Freaks

### Your Position

Founder / Co-Founder

### Name

Harri Hart

### Have you already done a public sale?

No

**Comment by gmanredmond** [comment]
"I apologize for the delayed response. Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required."

**Comment by shonuffy** [comment]
@cubensos Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.
