### ISSUE TITLE
Group transactions around the NFT on Transactions page

### ISSUE THREAD

**Issue by basvansambeek** [soonaverse/soonaverse-dao#722]
It would be good to group all transactions around a single NFT. Now I have 3 lines for payment, royalties and bill to the owner. 

The way I see this is to group those together on a background with the same color, and put the NFT it pertains to in front of it (Collection name and NFT number to keep it light). The next group of transactions would have a slightly different shade background, alternating between two colours per NFT.

That way you keep the transaction history linear, but also make it clear what NFT it's about. (I sometimes have new IOTA tokens in Firefly, with no clue where they came from. It messes up my administration.)

**Comment by humaint** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/722?planning-poker) with ZenHub @adamunchained @Gundavri

**Comment by adamunchained** [comment]
This is technically very challenging to implement. Individual transaction are independently queried and we would have to apply grouping logic on the client side. We can't apply grouping on the client side as there could be significant amount of transactions. We need to retrieve these transactions in batches hence particular batch might not have all transactions for us to group.

I'll close this for now as non priority. We can re-open once we see this as an urgent item to implement.
