### ISSUE TITLE
Internal Error Proposal

### ISSUE THREAD

**Issue by DirtyDreamer** [soonaverse/soonaverse-dao#723]
**Describe the bug**
The internal Error is trown when a new proposol is safed

**To Reproduce**
1. Go to proposels
2. Click on new proposel
3. Fill in all fields
4. Click on create proposel

**Expected behavior**
A new proposel should be added to the groupe

**Desktop (please complete the following information):**
 - OS: Windoes
 - Browser chrome
 - Version Version 101.0.4951.67

**Comment by adamunchained** [comment]
Can you please provide more information? Inputed fields or screenshot? thank you!

**Comment by DirtyDreamer** [comment]
[image: image.png][image: image.png]
4 Answers maybe thats causing the error

Am Fr., 27. Mai 2022 um 18:39 Uhr schrieb Adam ***@***.***>:

**Comment by DirtyDreamer** [comment]
No i get the same one with 3 options

Am Mo., 30. Mai 2022 um 20:07 Uhr schrieb Sexy AI ***@***.***>:

**Comment by adamunchained** [comment]
Proposals will be reworked with Shimmer.
