### ISSUE TITLE
Giveaways Purchasable by anyone

### ISSUE THREAD

**Issue by LordSciFi** [soonaverse/soonaverse-dao#724]
**Describe the bug**

**To Reproduce**
1. Go on a collection for giveaways
2. Click on the NFT which is free to claim for user X
3. Purchase the NFT which should be only purchasable by user X (instead of him)

**Expected behavior**
Only the person who is allowed to purchase/claim the giveaway should be able to claim it.

**Screenshots**
![image](https://user-images.githubusercontent.com/79095057/169823425-4a3c8afd-5ea6-428a-a6dc-f8a051a1fb8d.png)

**Desktop (please complete the following information):**
 
 Not sure on what it was tested but probably it is not browser or desktop dependent.

**Smartphone (please complete the following information):**
 
 Probably neither Smartphone/device dependent.

**Additional context**
Based on what BeeBro gave as feedback in your general chat:
https://discord.com/channels/892481940953915433/908575339951833129/978261744961093702

Soonaverse users can buy (for 1 MITOA) an NFT giveaway that is not supposed to be theirs.

**Comment by adamunchained** [comment]
this has been fixed, please see announcement for further details: https://discord.com/channels/892481940953915433/947920161195851797/978480873160712232
