### ISSUE TITLE
Magic Voodoo Dolls - REKT?

### ISSUE THREAD

**Issue by LordSciFi** [soonaverse/soonaverse-dao#725]
**Describe the bug**
Based on this issue:
https://github.com/soonaverse/soonaverse-dao/issues/724

Our NFT collection got REKT. Some people are buying up all the super rare NFTs from our collection which were supposed to be airdroped to one of the exclusive holders of an LMVD once we sold 22% of the entire collection.

We can't proceed with this step and fulfill what we promised because our NFTs got stolen or unrightfully claimed.

**To Reproduce**
Please see this bug: https://github.com/soonaverse/soonaverse-dao/issues/724

**Expected behavior**
We'll no one should be able to claim things that don't belong to them.
Also, we ask you kindly to help us regain control over our NFTs which belong to the CULT and their members and will be airdropped to them. We know how startup life is and we completely understand that such things can happen, please let's just be in touch to fix this. We're more than happy to give an interview for a blog post afterwards on how smoothly you've reacted and managed this whole situation. Let's keep pushing Soonaverse to the moon, LFG!

You can reach me on discord: Lord_SciFi | Magic Meme Money#9875

**Screenshots**
Example of a user which unrightfully claimed a lot of our special and super rare LMVDs:
![image](https://user-images.githubusercontent.com/79095057/169828094-b0e16f21-4949-4761-b0d5-647930154c77.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
this has been fixed, please see announcement for further details: https://discord.com/channels/892481940953915433/947920161195851797/978480873160712232
