### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Owlcity1234** [soonaverse/soonaverse-dao#726]
### Discord Name

LuxArt#9410

### Soonaverse Profile Id

0x9Ebe31860dEe061b6d3670a5b80c89285d2B9780

### Payment Action

Sold NFT - Fixed Price

### Payment Problem

I sold and NFT and did not get a payment or royalties.

### Wallet Type

FireFly

### Wallet Version

1.4.2

### NFT Id

0xffd5e40f14dec76f8098e3b324b568020c3209f6

### NFT Collection Id

0x0521f18038972fe3549453f15a6845d18159e14b

### Comments

```shell
I sold this NFT named - lighthouse https://soonaverse.com/nft/0xffd5e40f14dec76f8098e3b324b568020c3209f6
I only received the 5.2 MI commission amount the rest 69.8 MI did not reach my wallet
Please fix this
Thank you

Regards
LuxArt
```

**Comment by adamunchained** [comment]
we had delays on our Hornet nodes. This should be now finalized.
