### ISSUE TITLE
Transactions tab under My profile only shows outgoing transactions, not incoming

### ISSUE THREAD

**Issue by basvansambeek** [soonaverse/soonaverse-dao#730]
**Describe the bug**
I only see transactions of stuf fi bought, not what I sold.

**To Reproduce**
1. Go to 'My profile'
2. Click on 'Transactions'
3. Scroll down to 'search for sold NF3'
4. Don't see them

**Expected behavior**
I expect to see the NFT is sold, since I have quite a few, I was expecting to easily learn why there are more tokens in Firefly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 100.0.2

**Comment by adamunchained** [comment]
yeah very good point, we identify as well and it'll be fixed as part of the: https://github.com/soonaverse/soonaverse/issues/946 (coming out next sprint)
