### ISSUE TITLE
[Minor] - Card on home needs to be modified

### ISSUE THREAD

**Issue by MiKeF05** [soonaverse/soonaverse-dao#732]
On the home website the card in the center needs to be modified in German language.

![image](https://user-images.githubusercontent.com/71659397/170123760-71483ce2-acda-4891-944d-645a8753a7da.png)

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/732?planning-poker) with ZenHub @Gundavri
