### ISSUE TITLE
[TLP]: mexaverso

### ISSUE THREAD

**Issue by mexaverso** [soonaverse/soonaverse-dao#735]
### Email

atencion@powerclasswifi.com

### Company Name

PowerClass

### Your Position

Founder / Co-Founder

### Name

Armando Rosales

### Have you already done a public sale?

No

### Files and other information

```shell
Tokens Terms & Conditions:
https://mexaverso.github.io/
```

**Comment by gmanredmond** [comment]
"I apologize for the delayed response. Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required."

**Comment by mexaverso** [comment]
Thank you so much. Ill be pleased to work along with you if anything needed.

Best regards!
Armando
http://mexaverso.mx

**Comment by shonuffy** [comment]
@mexaverso Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.

**Comment by mexaverso** [comment]
I have just applied to the KYC applicant badge as instructed. I added this note: "Can the name of the token still be changed to "Mexitoken"? If so please issue "Mexitoken" instead of "Mexicoin" If not please go ahead with "Mexicoin".
Thanks

**Comment by shonuffy** [comment]
Shouldn't be an issue as the token hasn't been created yet

**Comment by shonuffy** [comment]
Badge approved

**Comment by mexaverso** [comment]
Hi. I´ve purchased the TLP KYC NFT.
Purchase Message ID ( https://explorer.iota.org/mainnet )
ddd1c1e3df56b801134fe10403b0e652228df715c335faa5b6d79ff00b8f98d3
I look forward to take the following step :D

Best Regards
@ Mexaverso&ThePurpleCow
Armando Rosales - email: mexaverso@gmail.com

**Comment by shonuffy** [comment]
Thank you. Your information has been forwarded to Driftwood, they will be contacting you directly via the email you provided.

**Comment by mexaverso** [comment]
Please terminate all active awards in Mexaverso ("The Mexaverse") space since Im now designing new mechanics for Mexitoken distribution/airdrops. There are 3 active awards please terminate them all immediately.

**Comment by shonuffy** [comment]
You haven't configured a token so there is nothing to "terminate"

**Comment by shonuffy** [comment]
Awards can't be cancelled or deleted

**Comment by mexaverso** [comment]
ok

**Comment by mexaverso** [comment]
Hi. Where can I get informed of soonaverse launchpad tokens technical info? So I can figure out some features to offer to my potential purchasers for example token as access key, etc. Is any documentation available? or who can i ask for technical info?

**Comment by mexaverso** [comment]
Hi. Take a look at the Terms & Conditions of Mexitoken if you want. They will maybe be useful. The thought is that every one of us operates within a lawful jurisdiction and that these tokens will be used in the context of DAOs which consider collective decisions. ¡Regards!

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@mexaverso

**Comment by shonuffy** [comment]
@mexaverso Please apply for this badge. https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/participants

**Comment by mexaverso** [comment]
Listo! (Done :D )
Shouldn´t my token be shown in https://wen2.soonaverse.com/tokens/launchpad ? ( i don´t see it). When you say ..."to test out the system to learn how to configure your token set up and launch strategy does that mean that I shall see other token´s configuration or shall I wait to my token to be shown? Thanks!

**Comment by shonuffy** [comment]
No, wen2 is a testnet. It where you practice the set up. 

You can now configure your token at Soonaverse.com. Please remember when configuring your token that you cannot mint the token if you want to use airdrop / launchpad. If you mint it you have to wait until we deliver support for airdrop/launchpad minted tokens.
