### ISSUE TITLE
Enable current distribution export on token page

### ISSUE THREAD

**Issue by humaint** [soonaverse/soonaverse-dao#736]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/Soonaverse-%E2%80%94-WebApp?node-id=2736%3A37761

![SCR-20220525-id8.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/2bdb3084-4dca-405d-8490-f7de82c0e28c)

**Comment by adamunchained** [comment]
@Gundavri - for the export, you simply get records from distribution table and generate CSV with following:

EthAddress (field uid), tokenOwned
