### ISSUE TITLE
Pending members, do not appear.

### ISSUE THREAD

**Issue by Bioquad** [soonaverse/soonaverse-dao#742]
**Describe the bug**
Pending members do not appear.

![Problema membres pendents](https://user-images.githubusercontent.com/106176115/170538570-625b802c-9897-43fd-b1eb-68f57a7dc80f.png)

**Comment by adamunchained** [comment]
It's an issue with the counter. It would keep increasing when the same member tries to request to join multiple times. It'll be fixed as part of the https://github.com/soonaverse/soonaverse-dao/issues/764
