### ISSUE TITLE
Transaction export does not work (CSV) and Transactions not complete

### ISSUE THREAD

**Issue by MyMonk089** [soonaverse/soonaverse-dao#744]
**Describe the bug**
When I click on export the transactions, it keeps spinning and nothing happens. Furthermore my list of transactions ends on 04/18/22 but there are many transactions later on till today.

**To Reproduce**
1. Go to 'transactions' of MyMonk089
2. see missing transactions
3. Click on 'export CSV'

**Expected behavior**
Full transaction history shown and when clicking on export CSV open up a new window with the folders of storage to select path where to save the CSV.

**Screenshots**
<img width="778" alt="Bildschirmfoto 2022-05-27 um 10 21 56" src="https://user-images.githubusercontent.com/60474745/170660853-497be8a3-9f31-4f29-a41c-b18a8a415375.png">
<img width="196" alt="Bildschirmfoto 2022-05-27 um 10 22 09" src="https://user-images.githubusercontent.com/60474745/170660855-8319c07c-7dc8-43f2-8e13-6bb85e984b8b.png">

**Desktop (please complete the following information):**
 - OS: Mac Monterey 12.4
 - Browser Chrome
 - Version Version 102.0.5005.61

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/744?planning-poker) with ZenHub @Gundavri

**Comment by MyMonk089** [comment]
Just claimed the FEE Token and this transactions are visible in the list. Could it be, that only the transactions of the first sales on Soonaverse are displayed and not the transactions when I sell one of my NFTs to somebody else later on? 
For me it is important that all sales are displayed because of tax reasons if the NFT holding is less than 1 year. ;-)


![Bildschirmfoto 2022-05-31 um 12 37 57](https://user-images.githubusercontent.com/60474745/171154957-223d4a0e-2f53-46df-9531-83b990a99d30.png)

**Comment by adamunchained** [comment]
Yes there were two issues:
- incorrectly set previous owner on certain transaction. This has been hot fixed: https://github.com/soonaverse/soonaverse/issues/977
- we also don't include transactions for NFTs you sold or previously owned. This will be fixed in next sprint: https://github.com/soonaverse/soonaverse/issues/946

**Comment by centercirclesolutions** [comment]
Also it is hard to determine what transactions are for stuff you sold or stuff you bought

**Comment by humaint** [comment]
@centercirclesolutions can you pls retest this in wen.soonaverse.com

**Comment by humaint** [comment]
@centercirclesolutions can you pls retest this in wen.soonaverse.com

**Comment by centercirclesolutions** [comment]
It finally completed but too over 30 minutes. I have 32 pages of transactions
