### ISSUE TITLE
Purchase reversed

### ISSUE THREAD

**Issue by mexaverso** [soonaverse/soonaverse-dao#745]
I see my purchase of $Soon tokens reversed
 
¿Why?
Can I still purchase the tokens

Transaction references:
Original purchase:
https://explorer.iota.org/mainnet/message/d2e80a37ede104471875fdced0a709e37988defd917888a4d90c6e7fab2dd416
Reverse:
https://explorer.iota.org/mainnet/message/b0606367b95e9a4b0e3f7a253dd33a8e45f4cb88c7f0899f71d3b5e5a3366b4a

Thanks

**Comment by adamunchained** [comment]
Please read https://soonlabs.medium.com/adjusting-our-approach-to-funding-b6a7bc588518

**Comment by mexaverso** [comment]
Thanks adamunchained
