### ISSUE TITLE
Token trading - contrast in dark mode not good

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#750]
![image](https://user-images.githubusercontent.com/77154511/171102076-ebfa4bb5-cdb1-4759-b201-56eff9f686a7.png)

**Comment by humaint** [comment]
working on design

**Comment by humaint** [comment]
https://www.figma.com/file/bCO54KioJBPG00LUX4yBLi/Soonaverse-%E2%80%94-WebApp-(Darkmode)?node-id=3462%3A20203

**Comment by humaint** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/750?planning-poker) with ZenHub @adamunchained @Gundavri
