### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by valuefold** [soonaverse/soonaverse-dao#751]
### Discord Name

@valuefold#3799

### Soonaverse Profile Id

0xa6caaca8912c3bb5868c54dbc62b5f57e6196cac

### Payment Action

Other (Please describe in comments)

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

FireFly

### Wallet Version

1.6.0.

### Payment Sent to Address

iota1qzyyd4mc6n5qvjrjaym3d6x3fmsnexv8htf22zazmz98n4tv67f8wuxp0l5

### Amount Sent

1.27 Mi

### Payment Message Id

52549ecebd56e0d0c2e825b673b04872e602053ffe8776556d3556de04d2fcad

### Comments

```shell
$FEE token purchase. Payment made but not received back (after couple of hours)
```

**Comment by adamunchained** [comment]
We don't refund IOTAs to claim tokens. It behaves same way as NFT transfers or NFT Giveaways that typically happens for 1Mi.
