### ISSUE TITLE
Can't send the proper amount for token bid to buy FEE token

### ISSUE THREAD

**Issue by zarte13** [soonaverse/soonaverse-dao#752]
**Describe the bug**
It doesn't let me send the right amount of tokens
it always says invalid amount when I send iotas to the window
I tried sending 10 mi
and sending the weird amount
and neither worked

**To Reproduce**
1. Open Token Buy bid for FEE token
2. Select an amount (ex. 10 mi)
3. Send the selected amount (10 mi) via firefly to the address 
4. Doesn't work
5. Send the amount via the firefly deep links button
6. Doesn't work either

**Expected behavior**
Should be able to bid on the token

**Screenshots**
![image](https://user-images.githubusercontent.com/34402486/171299397-65520b16-268f-475b-b519-376ebe2d4162.png)

![image](https://user-images.githubusercontent.com/34402486/171299412-42f7b73e-f3e9-4622-a514-4b6eb6803b6e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (Chromium based)
 - Version Vivaldi 5.2.2623.48 (Stable channel) (64-bit) 
 - Firefly version 1.6.0

**Comment by adamunchained** [comment]
It seems UI incorrectly rounds prints the amounts within the UI. UI must show the decimals correctly if exists. 
Make sure the amount prints the 6 decimal exactly as they're coming from the "order" transaction. Use 2-6 digits number formatting. 

This must be also correctly passed into deep-link-firefly component.

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/752?planning-poker) with ZenHub @Gundavri
