### ISSUE TITLE
[Payment Issue]: Refund not sent.

### ISSUE THREAD

**Issue by robw5507** [soonaverse/soonaverse-dao#754]
### Discord Name

@Rw.#4451

### Soonaverse Profile Id

0x6e127f0ff3BEd69DFb8c450e0FA6b3e495A3Ae2B

### Payment Action

Purchase NFT from Collection

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

FireFly

### Wallet Version

1.6.0

### Payment Sent to Address

iota1qp8azs6qv253y7ja5792hfanrfe0vdtn8kg06tm0cyatq22r9evlgpcy535

### Amount Sent

180 Mi

### Payment Message Id

05b6543ae67b57e33cbcfd44b8810c6698876be782c6f4c154ee1177945623ff

### Comments

```shell
Payment was sent as a deposit to purchase Soon Tokens.
```

**Comment by adamunchained** [comment]
Transaction re-processed and have now cleared. We'll be improving re-processing process into the future. This happens in some edge cases where hornet node does not correctly respond to our requests. It tells us it made the transfer but in reality it didn't :)

**Comment by robw5507** [comment]
Thanks for the reply..I still don't see any transaction in my firefly
wallet.

**Comment by adamunchained** [comment]
It goes back to address validated on your profile. Please see the transaction here: https://thetangle.org/message/d5056e766b6f86e6bf5b4cd362c50e76d66f36b120cf187a4ddb778822e40a55

**Comment by robw5507** [comment]
Got it. Ty
