### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by ghost** [soonaverse/soonaverse-dao#757]
### Email

admin@terrafried.com

### Company Name

UST DAO

### Your Position

Founder / Co-Founder

### Name

Nodoshi Skintamoto

### Have you already done a public sale?

No

### Files and other information

```shell
Hi, this is a radical proposal. I am from the terra.money agora forum and setting up a DAO was suggested for recovery of funds from Terraform Labs which you may or may not know recently lost 40 Billion. What ideally I would like to do is airdrop people who still hold UST or LUNA an amount I work out later. I am not interested in the token becoming a currency or anything I just want it to trigger votes and to be only given to those who have a right to vote. Is this possible ? 

im currently working out of https://terrafried.com really liked your approach to the DAO and it took me a while to find one that didnt want to turn voting into an economy :) our idea is to make the DAO a legal entity and take legal action in singapore and elsewhere. There is backing for this idea. What do you think?

thanks so much for your help

Nodoshi Skintamoto

obviously these devs are no longer alive.

```

**Comment by gmanredmond** [comment]
"I apologize for the delayed response. Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required."

**Comment by shonuffy** [comment]
Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.
