### ISSUE TITLE
Price of NFT showing in Giota is not accurate.

### ISSUE THREAD

**Issue by cht168** [soonaverse/soonaverse-dao#762]
**Describe the bug**
I want to purchase an NFT, Iotoapes to be precise. https://soonaverse.com/nft/0x33ae0ffcfe28b8708fc6f94efd177c50223b5403
It is listed as 2.39Gi. When I send 2.39Gi from Firefly, the message is "We received invalid amount, try again" and it return to my wallet.
I know I'm sending exactly 2.39Gi, but I think the seller might set the NFT to something like 2391Miota and it's only shown as 2.39Gi, so I get the error message because of this. 

**To Reproduce**
1. Go to '(https://soonaverse.com/nft/0x33ae0ffcfe28b8708fc6f94efd177c50223b5403)'
2. Click on 'Buy Now'
3. Send 2.39Gi
4. See error message "We received invalid amount, try again"

**Expected behavior**

**Screenshots**

![wae](https://user-images.githubusercontent.com/102916375/171866716-bbd06995-9f01-4360-ab1f-c316f652b6e2.PNG)
![feed](https://user-images.githubusercontent.com/102916375/171866737-463e377b-9a39-4615-9de2-7a2f8f66a253.PNG)
![fee](https://user-images.githubusercontent.com/102916375/171866770-73543da5-96ac-49ea-b0d4-56466f8be3d0.PNG)

**Comment by adamunchained** [comment]
Checkout modal should always show price in Mi with all decimals. Please fix.

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/762?planning-poker) with ZenHub @Gundavri

**Comment by adamunchained** [comment]
We should no longer show Gi / Ti / Pi but show everything across the system in Mi. This will make it consistent with new networks we are adding such as SMR / RMS.

Fix the system to show IOTA’s everywhere in Mi with up to 6 decimals. On trading page it should stay fixed at 6 decimals as it is right now.
