### ISSUE TITLE
Join Spaces - Bug on counter logic "Pending Approvals"

### ISSUE THREAD

**Issue by m3rlin5ky** [soonaverse/soonaverse-dao#764]
**Describe the bug**
It is possible to create multiple  "Pending Approvals" by trying to enter a space multiple times
-> counter keeps counting the same person/member

**To Reproduce**
1. Go to the FEE space
2. Click on Join Space
3. Repeat step 1. and 2.
=> The counter keeps counting the same soonaverse member multiple times.

**Comment by adamunchained** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/764?planning-poker) with ZenHub @boldizsar-a-mezei
