### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by milkteawu** [soonaverse/soonaverse-dao#765]
### Discord Name

milkteawu#8280

### Soonaverse Profile Id

@milktea / 0x1eFF7D6051185aDABD747a7b7E26d22078c9Cb8b

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.2

### Comments

```shell
I sold some $Fee and the Ask was 100% fulfilled, but I didn't get IOTA.
My firefly wallet and Profile>Transaction neither show this order.
There are 5 asks, and first 4 of them is correct, but the fifth ask(10.00Ki 1,000FEE 10.00Mi) occur this problem.
I should receive 10 Mi but I get nothing.
```

**Comment by adamunchained** [comment]
I believe this has now been resolved: https://thetangle.org/message/779dd785f8d20d1f42f67a22981ab8fd8ae84c8cd2c072bb8683a491a9652e22

Sry about the delay, we are working on a fix to avoid this.
