### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by Ronaldvdb** [soonaverse/soonaverse-dao#769]
### Email

aya@aya-nature.com

### Company Name

Aya Nature

### Your Position

Founder / Co-Founder

### Name

Ronald van den Boogaardt

### Have you already done a public sale?

No

### Files and other information

```shell
Great greetings,

The Aya Nature token is created to help nature. Non profit. We buy land and convert it back to a place where plants, animals and fungi can thrive.

𝐀𝐘𝐀 𝐧𝐚𝐭𝐮𝐫𝐞 #𝐍𝐅𝐓𝐦𝐚𝐫𝐤𝐞𝐭𝐩𝐥𝐚𝐜𝐞
https://soonaverse.com/space/0xf075693c8ffca0589bd0bc5122c24222037ee675/overview
𝐀𝐘𝐀 𝐧𝐚𝐭𝐮𝐫𝐞 𝐍𝐅𝐓 𝐰𝐞𝐛𝐬𝐢𝐭𝐞
https://aya-nature.one/aya-nature-nft/ 
𝐃𝐢𝐬𝐜𝐨𝐫𝐝 𝐃𝐞𝐧
https://discord.gg/BrBKcKGdXg 
𝐓𝐰𝐢𝐭𝐭𝐞𝐫
https://twitter.com/AYAnatureNews 
𝐈𝐧𝐬𝐭𝐚𝐠𝐫𝐚𝐦
https://www.instagram.com/ayanatureart/ 
𝐘𝐨𝐮𝐭𝐮𝐛𝐞
https://www.youtube.com/c/We1Charity
𝐅𝐚𝐜𝐞𝐛𝐨𝐨𝐤
https://www.facebook.com/AyaNatureCentre


𝐃𝐨𝐧𝐚𝐭𝐢𝐨𝐧𝐬
Torus Foundation
Subject: AYA
NL05 TRIO 033 847 0875

Infinite Love,
Rising Sun
Aya Nature
```

**Comment by adamunchained** [comment]
We'll be opening up token launchpad / trading for any token very soon. Please stay patient. No need for approval.

**Comment by gmanredmond** [comment]
"I apologize for the delayed response. Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required."
