### ISSUE TITLE
The NFT page does not display all the properties completely.

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#772]
**Describe the bug**
When the properties of an NFT exceed a certain number, the bottom part of the properties will be covered and not displayed properly. check this：
https://soonaverse.com/nft/0x2b915e191d6be771244de8ba83ad1d76d7e88fda

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Chrome
 - Version:  101.0.4951.67

**Comment by humaint** [comment]
@Gundavri increase/remove the max-height of the collapsible property box

**Comment by humaint** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Public-Master-61a51a3547b2090011dce2d2/issues/soonaverse/soonaverse-dao/772?planning-poker) with ZenHub @adamunchained @Gundavri
