### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Hectorcubi** [soonaverse/soonaverse-dao#773]
### Discord Name

@Hector#0634

### Soonaverse Profile Id

0xbA33B27dEA777C7b0e3bB49788AD93ae89D68E0D

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.2

### Payment Sent to Address

iota1qqa6qtt3tcjd0ld4h8vfnulrsd7xyys6fnm2vt5zy3wy3uvktr6uv9lcdwv

### Amount Sent

160

### Comments

```shell
Hello 

I have a problem with soonaverse exchange. I exchanged my 10000 FE for 160 iota and the iotas do not appear anywhere. The FEE token has also disappeared and the transaction appears as completed but I have not obtained the corresponding funds. I would like to have my IOTAS in my firefly. 

Thank you
```

**Comment by Hectorcubi** [comment]
![image](https://user-images.githubusercontent.com/107147292/172699348-91988fd3-b1ab-4d77-8925-86b86e401826.png)
![image](https://user-images.githubusercontent.com/107147292/172699447-20cb2013-4bb3-42b2-8a5f-1cc6904f1166.png)
![image](https://user-images.githubusercontent.com/107147292/172699504-16f9ffb7-52af-4e0b-8cf6-f27a01970e13.png)

**Comment by adamunchained** [comment]
We are having some delays on few nodes, this seems to be now completed. See here: https://thetangle.org/message/7995359afcb7588e983d1782390e7498e3f39e2e2997e6492bb412659a4baa09
