### ISSUE TITLE
Update Tangle Listener

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#774]
## TangleListener updates for Stardust
- Implement TangleListener as a Hornet INX PLugin
- Add the ability to populate a variety of collections for different Networks
  - Shimmer Testnet: milestone_rms
  - Shimmer Net: milestone_smr
  - Current testnet (devnet): milestone_atoi 
- Include invalid and doublespend transations in `transactions_conflict` sub-collection under the milestone

## TangleListener Repo's
[INX TangleListener](https://github.com/soonaverse/inx-tanglelistener)
[Mainnet TangleListener](https://github.com/soonaverse/tanglelistener)

## Items for future work
- Currently using `ReadMilestoneCone` to get all blocks in the milestone. This may not scale to 1000bps and the reccomendation is to use `ListenToLedgerUpdates` instead
- Integrate redis KV store to only import addresses that we are using

**Comment by centercirclesolutions** [comment]
Current structure for firestore

```
type MS struct {
    MilestoneIndex uint32    `firestore:"milestone"`
    Complete       bool      `firestore:"completed"`
    Completed      time.Time `firestore:"completedOn,serverTimestamp"`
    Created        time.Time `firestore:"createdOn,serverTimestamp"`
    NodeId         string    `firestore:"listenerNodeId"`
    Transactions   int       `firestore:"transactionCount"`
}

type FSTX struct {
    Created            time.Time `firestore:"createdOn,serverTimestamp"`
    BlockId            string    `firestore:"blockId"`
    Milestone          uint32    `firestore:"milestone"`
    Processed          bool      `firestore:"processed"`
    Payload            string    `firestore:"payload"`
    InclusionState     int32     `firestore:"inclusionState,omitempty"`
    InclusionStateText string    `firestore:"inclusionStateText,omitempty"`
    ConflictReason     int32     `firestore:"conflictReason,omitempty"`
    ConflictReasonText string    `firestore:"conflictReasonText,omitempty"`
}
```

Values for Inclusion state and ConflictReason:
```
    BlockMetadata_LedgerInclusionState_name = map[int32]string{
        0: "NO_TRANSACTION",
        1: "INCLUDED",
        2: "CONFLICTING",
    }


    BlockMetadata_ConflictReason_name = map[int32]string{
        0:   "NONE",
        1:   "INPUT_ALREADY_SPENT",
        2:   "INPUT_ALREADY_SPENT_IN_THIS_MILESTONE",
        3:   "INPUT_NOT_FOUND",
        4:   "INPUT_OUTPUT_SUM_MISMATCH",
        5:   "INVALID_SIGNATURE",
        6:   "TIMELOCK_NOT_EXPIRED",
        7:   "INVALID_NATIVE_TOKENS",
        8:   "RETURN_AMOUNT_NOT_FULFILLED",
        9:   "INVALID_INPUT_UNLOCK",
        10:  "INVALID_INPUTS_COMMITMENT",
        11:  "INVALID_SENDER",
        12:  "INVALID_CHAIN_STATE_TRANSITION",
        255: "SEMANTIC_VALIDATION_FAILED",
```

**Comment by centercirclesolutions** [comment]
@adamunchained do we need `inclusionStateText` and `conflictReasonText` ?

**Comment by adamunchained** [comment]
> @adamunchained do we need `inclusionStateText` and `conflictReasonText` ?

what is this for?

**Comment by centercirclesolutions** [comment]
You've already answered this and I have not included the text. Only have the int representation of these
