### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by LunarBuddies** [soonaverse/soonaverse-dao#776]
### Email

post@miota.no

### Company Name

Lunar Buddies

### Your Position

CEO

### Name

Marius

### Have you already done a public sale?

No

### Files and other information

```shell
like to create a meme token.
```

**Comment by terrafried** [comment]
apparently they just ignore you for weeks if you post here

**Comment by gmanredmond** [comment]
> apparently they just ignore you for weeks if you post here



> Edit

I will be reaching out to you this week. To gather further info.

**Comment by shonuffy** [comment]
@LunarBuddies Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.
