### ISSUE TITLE
[marketplace][important] - The rounded price in Gi creates problems

### ISSUE THREAD

**Issue by imClement** [soonaverse/soonaverse-dao#777]
- Classic NFT Collection 
- NFT uploaded through .csv (multiple)

**The Problem**

The price displayed to  the users is incorrectly rounded to Gi with 2 decimals but it doesn't reflect the real price so their amounts (based on the rounded amount) are always returned as incorrect. 

Eg:
The price in  IOTA:  1436000000 
The rounded price in Gi:  1.44

**Comment by adamunchained** [comment]
We are completely changing representation of IOTAs across the system to be aligned with Shimmer.

This will be part of #762
