### ISSUE TITLE
Token Launchpad Form - Token Supply Form Field issue

### ISSUE THREAD

**Issue by Moonshot7161969** [soonaverse/soonaverse-dao#778]
**Describe the bug**

The minimum price in the Token supply form field is currently set at 0.01 

It needs to be allowed to set it to 0.00 (at least temporarily) due to legal/tax issues. This is an urgent issue, and without that we can't proceed with the application.

@adamunchained 
![Soonaverse - Invalid Price](https://user-images.githubusercontent.com/95666308/173262024-f943956d-b344-491e-9632-8ba4abffff45.PNG)

**Comment by adamunchained** [comment]
ah! That make sense. We'll schedule to improve it for the next release. It should really be part of "schedule sale" function.

**Comment by adamunchained** [comment]
@humaint - I think there are two challanges:
- Many times price needs to be set prior the SALE. Sometimes just 1h before the scheduled time.
- Sometimes price can be 0 and stay zero.

I'm thinking we should remove setting of the price within the token creation. It'll be part of "Schedule Sale" function and price can be change anytime until xx minutes before actual sale.

thoughts?

**Comment by Moonshot7161969** [comment]
> @humaint - I think there are two challanges:
> 
> * Many times price needs to be set prior the SALE. Sometimes just 1h before the scheduled time.
> * Sometimes price can be 0 and stay zero.
> 
> I'm thinking we should remove setting of the price within the token creation. It'll be part of "Schedule Sale" function and price can be change anytime until xx minutes before actual sale.
> 
> thoughts?

Yes, this would be the ideal solution. When an IPO in a stock market is about to be listed, the sponsor and/or market maker is negotiating the opening price of the security hours and minutes up to the actual launch.

**Comment by adamunchained** [comment]
This will be done part of the https://github.com/soonaverse/soonaverse/issues/1275
