### ISSUE TITLE
Not matching trade?

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#779]
@adamunchained commented on [Mon Jun 13 2022](https://github.com/soonaverse/soonaverse/issues/1064)

Not matching trade? See below
<img width="619" alt="Screen Shot 2022-06-13 at 6 28 46 AM" src="https://user-images.githubusercontent.com/130610/173364504-eb8f08f6-6dd2-4641-abf6-b66c9c3c8d46.png">

**Comment by adamunchained** [comment]
@humaint - can you think about how to improve the UI and explain this rule so ppl don’t think our system is not matching?

**Comment by csxiong** [comment]
There is a way to possibly alleviate this problem. It is that when the buyer pays, the system charges an extra 1Mi as a refund deposit, and if the buyer has less than 1Mi left after the purchase, then the deposit is refunded to him along with the balance, and his order is ended at the same time.

**Comment by adamunchained** [comment]
@csxiong - partial fulfilment are very important for us. It increase chance to match bids / asks so we would not want to eliminate those.

Asking additional 1 Mi is not enough as there could be xx fulfilment. Although, I do see us utilizing Storage Deposit  in Stardust upgrade to get around this.

**Comment by adamunchained** [comment]
@humaint - FYI @csxiong suggested following under each grouped line
![unknown-1](https://user-images.githubusercontent.com/130610/173398799-3835e33f-631d-475f-beec-7dcc7fd48e29.png)

I'm not sure if I'm big fan of this as I've not seen it on many other exchanges and it might make it unnecessary complex. Also, I do think we have other higher priorities in #775 we should prioritize first.

**Comment by csxiong** [comment]
> @csxiong - partial fulfilment are very important for us. It increase chance to match bids / asks so we would not want to eliminate those.
> 
> Asking additional 1 Mi is not enough as there could be xx fulfilment. Although, I do see us utilizing Storage Deposit in Stardust upgrade to get around this.

The trade matching system is designed in such a way that for a specific token, it processes orders synchronously, not asynchronously. It is sorted by timestamp and then forms a sequence to be handled one by one for matching, so there is no situation where one order will be matched by multiple opposite orders at the same moment as you said. So I still think 1Mi is sufficient.

**Comment by adamunchained** [comment]
How so? I've used various exchanges that would do partial fulfilment. Very commonly on an exchange you would see your bid or your ask being partially fulfilled. 

The difference on exchange is that partial fulfilment is just deposited within the exchange. Instead Soonaverse process transaction directly on tangle. This means we have to respect 1 Mi rule. Each buy goes into isolated wallet and those funds are distributed to sellers as the buy is being fulfilled. It does not go into a big pot like it would go on an exchange. 

No allowing partial fulfilment means we would have to wait for ask / bid to pair not just on a price (less or equal) but also pair on exact "quantity". This would reduce liquidity significantly.

**Comment by csxiong** [comment]
> How so? I've used various exchanges that would do partial fulfilment. Very commonly on an exchange you would see your bid or your ask being partially fulfilled.
> 
> The difference on exchange is that partial fulfilment is just deposited within the exchange. Instead Soonaverse process transaction directly on tangle. This means we have to respect 1 Mi rule. Each buy goes into isolated wallet and those funds are distributed to sellers as the buy is being fulfilled. It does not go into a big pot like it would go on an exchange.
> 
> No allowing partial fulfilment means we would have to wait for ask / bid to pair not just on a price (less or equal) but also pair on exact "quantity". This would reduce liquidity significantly.

Note that I did not say that an order cannot be partially fulfilled; I emphasized that it will not be partially fulfilled in an asynchronous manner by multiple opposing orders, but rather partially fulfilled in order of their timestamps. In this case, only the last order to be matched will trigger it for refund processing.

**Comment by adamunchained** [comment]
Right, I see what you're saying. So we do actually settle the refund at the end. 

```
if (update.type === TokenBuySellOrderType.BUY && update.status === TokenBuySellOrderStatus.SETTLED) {
    await creditBuyer(update, purchases, transaction)
}
```

Only once the buy is settled (fully fulfilled) we would refund. If I'm not mistaken there were some other scenarios where we might need more then one 1Mi (although that might been specific to paying out royalties). I can't recall. Let us finish shimmer integration (https://github.com/soonaverse/soonaverse/issues/1001) + support for any royalty on trading / launchpad https://github.com/soonaverse/soonaverse/issues/890 and we revisit this. We'll need to start mapping out all the logic as part of this as well..I would like to invite you private FAB500 group and give you access to our code within next few weeks if you're interested.

**Comment by csxiong** [comment]
> Right, I see what you're saying. So we do actually settle the refund at the end.
> 
> ```
> if (update.type === TokenBuySellOrderType.BUY && update.status === TokenBuySellOrderStatus.SETTLED) {
>     await creditBuyer(update, purchases, transaction)
> }
> ```
> 
> Only once the buy is settled (fully fulfilled) we would refund. If I'm not mistaken there were some other scenarios where we might need more then one 1Mi (although that might been specific to paying out royalties). I can't recall. Let us finish shimmer integration (https://github.com/soonaverse/soonaverse/issues/1001) + support for any royalty on trading / launchpad (https://github.com/soonaverse/soonaverse/issues/890) and we revisit this. We'll need to start mapping out all the logic as part of this as well..I would like to invite you private FAB500 group and give you access to our code within next few weeks if you're interested.

Yes, I am interested in participating and hope to be of some help.

**Comment by adamunchained** [comment]
Above has been massively improved due Shimmer and it's much less concern.
