### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by priceactionbars** [soonaverse/soonaverse-dao#782]
### Email

priceactionbars@gmail.com

### Company Name

IOTA robot club apes

### Your Position

CEO

### Name

pab

### Have you already done a public sale?

No

**Comment by gmanredmond** [comment]
Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required.

**Comment by priceactionbars** [comment]
Thank you, I also want to say, that I would like to change the token supply of ape token to 1 00 000 000 000 (11 zero's) and the price per token should be 0.1 Mi instead 1 Mi. There seem to have been a "potential parsing error' like Ziggy said from discord support, that's why I wasn't abele to add more zero's to the token supply so I deleted some zero's from the token supply and it succeed.

Hopefully you can change it.


Kind regards

**Comment by gmanredmond** [comment]
Acknowledged. The team is looking into it.

**Comment by shonuffy** [comment]
@priceactionbars Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.

**Comment by priceactionbars** [comment]
I applied for the badge applicant on SOONAVERSE under the name: @IotaApes

**Comment by shonuffy** [comment]
Approved

**Comment by shonuffy** [comment]
Yes, correct. You do it on your own.

**Comment by priceactionbars** [comment]
I confirm I bought the badge of 250Mi



Kind regards

**Comment by priceactionbars** [comment]
Dear Shonuf
We've  done every step regarding KYC process and participated for the the last complete KYC badge.
Can you confirm that you've received and will unlock the token capability on the platform ?

Kind regards
IotaApes

**Comment by shonuffy** [comment]
We have not received confirmation from Driftwood, so you will have to wait until that comes through.

**Comment by priceactionbars** [comment]
I received confirmation since friday.
Okay, I'll wait then when they confirm it to you too. Probably they forgot it. 

Thank you for your respond

kind regards

**Comment by priceactionbars** [comment]
Dear Shonuf

I'll let you now that they send me a message around 14:28 that they have send you(soonlabs) a notification regarding KYC verification. 

Can you confirm it's now fixed and can now unlock token capability on soonaverse?


Kind regards

**Comment by priceactionbars** [comment]
Can you recheck it? they have said to me they already send a message since 3 days ago regarding the verification. 



Kind regards

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@priceactionbars

**Comment by priceactionbars** [comment]
Hey shonuff

I am a bit confused what you mean to set up our token...? 

Our token was already processed. When we get the award tomorrow, will it be just a one click to launch? Or will it be automatically launched on 28 september with othet projects, So we don't have to do anything?



Kind regards

**Comment by shonuffy** [comment]
Are you sure this wasn't in wen2.soonaverse.com? That is a test server and doesn't impact your mainnet account.
