### ISSUE TITLE
Does not allow CSV import correctly to NFT collection multiple

### ISSUE THREAD

**Issue by Randpic** [soonaverse/soonaverse-dao#784]
When it comes to uploading a collection of 500 NFT, almost every time the process is not finished. Because it doesn't let you load the .CSV files correctly with the NFT properties.

The page always freezes and crashes. I have tried it in other browsers and the same thing happens in all.

It's been more than 2 days, approximately 6 hours each day and I haven't been able to finish the process, it always fails in the same way, when uploading the .CSV, it freezes and crashes on the NFT display page.

**Comment by adamunchained** [comment]
This should be fixed in upcoming release, if you still have an issue let us know. We have done a lot of improvements on browser usage that might have been causing this.
