### ISSUE TITLE
issue in the book order

### ISSUE THREAD

**Issue by celarium3945** [soonaverse/soonaverse-dao#785]
![image](https://user-images.githubusercontent.com/103221824/173440602-1eed6704-3e2b-4022-8757-2544a9148270.png)

the 8250 fee ask should have been executed
the 142.xx bid also
did I miss something?

**Comment by adamunchained** [comment]
You did not. We're looking at it right now and working on a fix. Please see #783

I hope the fix will come out within next few hours.

Thank you for reporting this.
