### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by chriscsc** [soonaverse/soonaverse-dao#786]
### Discord Name

chaeツ#1840

### Soonaverse Profile Id

0x47bfefba9bcdb3e811708c01cfd2cb1579441847

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.2

### Comments

```shell
Hi, I had 5 FEE sell orders got filled 100% on soonaverse , but I only received 4 transactions to my iota wallet. The 19.2 Mi transactions is missing.
```

**Comment by chriscsc** [comment]
The five orders got filled 100%
![SCR-20220614-jtu](https://user-images.githubusercontent.com/3703735/173508430-07259afc-d12e-4739-9eaa-4b011e0fb6a4.png)

Only received 4 in my firefly wallet
![SCR-20220614-k4k](https://user-images.githubusercontent.com/3703735/173508507-19a9da59-cd25-44b0-81ca-2c82b9a7fbf0.png)

Many conflicting transactions shown in iota explorer, that 19.2 Mi never arrives, not sure what's going on :/ [https://explorer.iota.org/mainnet/addr/iota1qrtu8xkts2ff9rs0hp9xzgqezfx5mawzsxys04thmrw6r7w2awkm7k3mg9k](url)
![SCR-20220614-k56](https://user-images.githubusercontent.com/3703735/173508612-1015aa50-3a91-4d74-8143-243e19418eee.png)

**Comment by adamunchained** [comment]
@chriscsc we have improved payment re-processing to avoid these conflicts on tangle. These issues started to appear on partially fulfilled sales. We have released hot-fix for this tonight. Your payment should also be processed now.
