### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by bonifatius5** [soonaverse/soonaverse-dao#789]
### Discord Name

@staniol#5488

### Soonaverse Profile Id

0x366b354931c4a112866850F3E17DB1cAC2171515

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.2

### Payment Sent to Address

iota1qpa0l9gmdagrnct0s0n67vfdm5k252vulc6ql0mpztw9kk6ncgfevvq394k

### Amount Sent

684 Mi

### Comments

```shell
SOON Token Sale

Hello guys,

I participated in the SOON Token sale. Two minutes after the start I bought a total of 900 SOON for 684.00 mi. I immediately sent the 684.00 to the following address:

iota1qpa0l9gmdagrnctOs0n67vfdm5k252vulc6q/Ompztw9kk6ncgfevvg394k

The confirmation date is 14 Jun 2022, 18:02:32. 

But the purchase is not completed yet and the SOON tokens are not credited!

please follow up and let me know when I will receive the credit.

Otherwise, I expect a refund of my 684.00 Mi.

Many thanks and greetings
```

**Comment by adamunchained** [comment]
<img width="1741" alt="Screen Shot 2022-06-15 at 9 54 18 PM" src="https://user-images.githubusercontent.com/130610/173994105-d893910f-59bf-4a81-b0c2-a3fe03d2553f.png">

You can see $SOON tokens on your profile. After the sale is finished, it will turn into "token owned".

**Comment by bonifatius5** [comment]
Ok. Thanks for the quick reply. Then I wait until the period is over.
