### ISSUE TITLE
The discounted price after mint is displayed incorrectly

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#793]
**Describe the bug**
If an NFT sets a discounted price, it displays the discounted price normally before Mint. But when after Mint, it will treat the discounted price as the original price and then discounted again to display.

**To Reproduce**
1. Go to 'https://soonaverse.com/nft/0xa58b2685cfb41b465ee329ad8e09a7386433d381'
2. Click on 'Generated NFT'
3. You can see the right mintprice if you have a discount
4. Minting....
5. After Minting, you'll find the price is wrong.

**Screenshots**
![微信截图_20220620080232](https://user-images.githubusercontent.com/86828398/174505610-53333116-b0d2-4dbe-b96d-e95cb09a5c14.png)
![image](https://user-images.githubusercontent.com/86828398/174505623-17e274a9-7c0f-416d-ada0-1a05d6db818d.png)

**Comment by adamunchained** [comment]
Let's make sure on complete page we calculate final price based on the original price not the price that's coming in transaction record (that price is already discounted).

**Comment by adamunchained** [comment]
Fixed in upcoming release
