### ISSUE TITLE
Purchase prices for P2P (reserved for a person) sales are not taken into account.

### ISSUE THREAD

**Issue by Travetown** [soonaverse/soonaverse-dao#794]
If an NFT is reserved by one person for another person, the actual purchase price will not be taken into account, but rather the last price achieved via the marketplace.
This certainly makes sense in the case of sales (swap) for 1 MI, but has disadvantages when dealing with real sales as in this example.

<img width="831" alt="Bildschirmfoto 2022-06-20 um 07 51 38" src="https://user-images.githubusercontent.com/66588710/174533878-dcc33580-ce57-41da-93d0-8e21c31c0084.png">
<img width="940" alt="Bildschirmfoto 2022-06-20 um 07 58 54" src="https://user-images.githubusercontent.com/66588710/174534708-a37ed51d-8fec-4e5e-89b8-cbd88d4f8a56.png">

Perhaps it would be better to be able to select a swap (with 1 MI) as an option and then continue as we are doing now. All other sales reserved for a specific person should be accounted for at the true purchase price. (also in the data center).

**Comment by adamunchained** [comment]
@humaint - as part of the upcoming release we no longer support "transferring NFTs". They can just do that on Shimmer by sending another member the NFT directly. 

I want to slightly change the feature below:
<img width="736" alt="Screen Shot 2022-08-05 at 9 58 50 AM" src="https://user-images.githubusercontent.com/130610/183125535-c7ac1e14-ac98-4624-b6e8-a6b41dbae385.png">

to instead allowing user to specify particular user that can purchase it only. Technically, logic will be same (they can still use it for transfer) although we will start to track the price and it'll be included in the history.

Any comments?

**Comment by humaint** [comment]
@adamunchained transferring NFTs has been removed already right?

**Comment by adamunchained** [comment]
Not yet, I’ll be removed once Shimmer migration is complete for NFT. Although I would like to keep it for above.

**Comment by adamunchained** [comment]
This has been now removed as members can just transferred via wallets.
