### ISSUE TITLE
Token price incorrect at checkout

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#796]
User is given a price at checkout that results in an invalid amount error when the matching amount is sent, so they cannot buy tokens. Unclear if this is related to any rounding so made a new issue.

![unknown-7](https://user-images.githubusercontent.com/38050901/175093614-e43bad6b-9057-407f-9187-18f979aa1385.png)

![unknown-8](https://user-images.githubusercontent.com/38050901/175093627-bc6139ef-e141-4359-b133-fc067612b654.png)

**Comment by adamunchained** [comment]
In upcoming release we have clean up all the units and how they show. This is fixed.
