### ISSUE TITLE
New TanglePay icon to recognize FIAT Support

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#798]
See below:

![Fiat](https://user-images.githubusercontent.com/130610/175201352-927f48c1-1191-481b-9f6c-4b6d66850ad1.png)

just re-assign if all good

**Comment by humaint** [comment]
@adamunchained where do you want to put this?

**Comment by adamunchained** [comment]
I was thinking in the pop-ups button where we show pay with firefly / tanglepay

**Comment by humaint** [comment]
![SCR-20220624-eth.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/b0606ddf-0d8e-45c7-9844-affae4c93597)

you want to add another button or just update the logo?

is there any difference in the link?

**Comment by adamunchained** [comment]
Just update the logo. Everything stays the same. Link is same.

**Comment by Gundavri** [comment]
@humaint @adamunchained Dark version of those logos would be great because of the way they are currently almost not visible.
