### ISSUE TITLE
Claim tokens not working on Mobile

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#799]
**Describe the bug**
^^^ Need I say more?

**Comment by humaint** [comment]
https://www.figma.com/file/7ER3oGXPRXHCEoUGuUfSLl/Responsive?node-id=3351%3A23269

Member tokens + claim process added to responsive design

**Comment by humaint** [comment]
![SCR-20220810-k72.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/e2dbb4c9-825c-4ec8-8e58-45b84840ce64)

buy / trade buttons should not be visible when browsing my tokens on mobile, see design
https://www.figma.com/file/7ER3oGXPRXHCEoUGuUfSLl/Responsive?node-id=3351%3A23269
