### ISSUE TITLE
Percentage of vote mismatch between Proposals page and proposal overview page

### ISSUE THREAD

**Issue by cometax** [soonaverse/soonaverse-dao#802]
**Describe the bug**
The percentages shown on the proposal page does not match the actual voting percentage. See attached picture which shows 99.40% yes, 0.60% No and on the actual proposal it shows 25% No 75% Yes.

https://soonaverse.com/space/0xf8785326be124a1dbebb21f6bd2649c63186cd4d/proposals (shows 99.4% yes)
https://soonaverse.com/proposal/0xf8548726258a206c3b0d69506d0b1d4521133844/overview (shows 75% yes)

If the 99.4%, 0.6% refers to just the number of people that have voted (which i do not believe is the case since only a few have voted so far), I believe the way the information is being presented is misleading. It should clearly state Participation %.

**To Reproduce**
1. Go to 'https://soonaverse.com/space/0xf8785326be124a1dbebb21f6bd2649c63186cd4d/proposals (shows 99.4% yes) and note the percentage
2. Go to 'https://soonaverse.com/proposal/0xf8548726258a206c3b0d69506d0b1d4521133844/overview (shows 75% yes)' and note the percentage
3. See mismatch

**Expected behavior**
Both pages should show the same percentage

**Screenshots**
![2 github](https://user-images.githubusercontent.com/29169645/175978585-830e325e-e00b-4398-afe6-e5f764823132.png)
![1 github](https://user-images.githubusercontent.com/29169645/175978589-92a5eaa0-950c-4dd4-8040-8342ea30ff79.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Edge
 - Version: 103.0.1264.37

**Comment by adamunchained** [comment]
I agree! It should be consistent.

We'll be redoing our voting mechanics to fully run on Shimmer therefore for now we will not be touching our legacy logic and it'll be working correctly in upcoming release.
