### ISSUE TITLE
[TLP]: ADVANCE TOKEN

### ISSUE THREAD

**Issue by michaelqtodd** [soonaverse/soonaverse-dao#804]
### Email

michaelqtodd@gmail.com

### Company Name

Life Trees

### Your Position

Founder / Co-Founder

### Name

Michael Todd

### Have you already done a public sale?

No

### Files and other information

```shell
Hi my wife Dr Yoriko Todd and I started this business Life Trees about 3 years ago. We are sending Moringa, Neem and Chia from Kenya to Europe. 
We wish to expand to other supply and create a network called Advance.
We want to create a token to reward our members and distributors.
We also want to use IOTA to create a new and better supply chain and use the TLIP that has been agreed to between IOTA and East Africa Trade Mark Board
I am @michaelqtodd on Twitter my wife is @DrYorikoTodd
Thank you
```

**Comment by gmanredmond** [comment]
Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required.

**Comment by shonuffy** [comment]
@michaelqtodd Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.

**Comment by michaelqtodd** [comment]
OK thank you very much I understand
Michael


Connect with me anywhere online at about.me/michaelqtodd anytime please. I
will do my best to connect back.

**Comment by michaelqtodd** [comment]
I hope this is correct

**Comment by michaelqtodd** [comment]
Hi I paid the 250 Mi what should I do now please

**Comment by shonuffy** [comment]
NFT ownership confirmed. Your contact information has been sent to Driftwood, they will be contacting you via the email information you provided in this request.

**Comment by michaelqtodd** [comment]
Thank you!


Connect with me anywhere online at about.me/michaelqtodd anytime please. I
will do my best to connect back.

**Comment by dossy88** [comment]
Your vita is very suspicious.....

**Comment by michaelqtodd** [comment]
> Your vita is very suspicious.....

Hi what is vita please. I 100% assure you there is nothing at all suspicious about me. We are sending organic food from Kenya to Europe and using the IOTA TLIP process. We hope to add a token to our supply chain model. How long does this process take?

**Comment by michaelqtodd** [comment]
Still no verification is it normal to take over 6 weeks? Happy to wait.
Regards
Michael


Connect with me anywhere online at about.me/michaelqtodd anytime please. I
will do my best to connect back.

**Comment by shonuffy** [comment]
What are you specifically referencing when you say verification? Are you talking about the Driftwood?

**Comment by shonuffy** [comment]
We are currently holding tokens from listing on the service until the Shimmer network goes live.

**Comment by michaelqtodd** [comment]
Yes Driftwood. I have never had a reply from them. Thanks for your reply. I
will wait for Shimmer.

**Comment by shonuffy** [comment]
They were sent your information July 10th. I can follow up with them.

**Comment by michaelqtodd** [comment]
Thanks I messaged them today and they approved me straight away. They said
they had overlooked sending me the approval message. All good.

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@michaelqtodd

**Comment by michaelqtodd** [comment]
I got a message on Twitter that I had been given permission to make an NFT
but it still says pending. Who should I contact about that please. I tried
a few people in Discord  61593fbb0b1e2a060317e455bf317e0e0b58c08
<https://t.co/RnJIB9hJDY>

**Comment by shonuffy** [comment]
Please configure the token and send me the link to it.

**Comment by michaelqtodd** [comment]
OK will organise all of this tomorrow. Thank you. Have been studying how to
stop Americans and Canadians from buying it

**Comment by shonuffy** [comment]
our platform does this automatically
