### ISSUE TITLE
[TLP]: tsywt by FB

### ISSUE THREAD

**Issue by DanielTrauth** [soonaverse/soonaverse-dao#808]
### Email

mail@senseering.de

### Company Name

senseering Gmbh

### Your Position

Founder / Co-Founder

### Name

Daniel Trauth

### Have you already done a public sale?

No

### Files and other information

```shell
Hi, I am the founder of the former Industrial IOTA Lab Aachen and the father of the first Industrial IOTA Data Marketplace (https://www.youtube.com/watch?v=y-X3mCyta0c) together with RWTH Aachen University. I am founding a new project, which is still secret, and at the request of Holger Köther of IF I would like to test sonnaverse. We are planning a DAO, a token, an API and an NFT sale. To convince my investors and co-founders, I would like to do a general rehearsal once. For this I have created the project and space and token named tsywt by FB
```

**Comment by gmanredmond** [comment]
Applications will begin to be processed after our token sale. We will follow up with you if any additional information is required.

**Comment by DanielTrauth** [comment]
I thought the TLP helps with the token sale? Or am I wrong?

**Comment by shonuffy** [comment]
@DanielTrauth Here are next steps in the KYC process. 

Please go to the Soonaverse and apply for the KYC applicant badge. Make certain to make it clear in your application who you are or give me that information here. (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview).

I will issue this badge to you so, you can access the TLP KYC NFT (250 Mi, which is used to pay to our vendor).

Once the NFT is purchased you must contact me here to inform me the transaction is complete. I will verify ownership of the NFT by you (make sure you are the Guardian of your space) and then I will initiate the KYC process by sharing your email address with our vendor, Driftwood Group.

A representative from Driftwood Group will communicate with you via email to outline what documentation is needed. They will provide you with a secure link for uploads. It is important to note here that none of this is shared or stored in a location that can accessed by anyone from the Soonaverse.

Upon receiving all of the supporting documents, Driftwood Group will complete the screening process, and generate an encrypted ID for the KYC'd individual(s).

We will be notified of the status of the results using the encrypted ID.

You then need to apply for a KYC approval badge, (https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/overview) which will unlock the Token creation capability on the platform.

**Comment by shonuffy** [comment]
@DanielTrauth Did you want me to keep this request open?

**Comment by DanielTrauth** [comment]
Hi @shonuffy, 

basically yes. our investor is hesitant. we will probably need some more time and then start again. close it! Tahnks.

**Comment by shonuffy** [comment]
Thank you @DanielTrauth. You are obviously always welcome in the Soonaverse. We would love to support senseering in any way we can. Take care.
