### ISSUE TITLE
Transaction export button stuck on 'Exporting CSV'

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#809]
The export button gets stuck on 'Exporting CSV' and the icon spins, but no csv file is ever generated.

![image](https://user-images.githubusercontent.com/38050901/177183252-91b7cc1b-8f03-430c-ba2c-20938cc4da03.png)

Disabling adblocker makes no difference.

**Comment by adamunchained** [comment]
This has been fixed in wen.
