### ISSUE TITLE
Impossible to find out who an NFT is listed for.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#811]
An individual NFT's page on the Soonaverse doesn't indicate who can purchase it - even to the one who listed it. This is an especially acute problem for those following the giveaway procedure of listing NFTs to giveaway winners for 1mi. The one listing the NFTs has no way to track what NFT can be purchased by what user and the recipients have no choice but to search through every NFT it could be in the lister's profile and try to execute a purchase on each and every one. This is especially unfeasible for large giveaways of say 25, 40, or 100.

It should be visible who can purchase an NFT from the NFT page and, if possible, the tile itself for easy recognition. Crappy paint example below.

![image](https://user-images.githubusercontent.com/38050901/178083297-297e5667-f5c3-48e2-aaf4-a667aa99013d.png)

**Comment by adamunchained** [comment]
closing as a stale issue. No one has even added further comments on it for over 6 months. 

Please feel free to re-open if you feel otherwise.
