### ISSUE TITLE
[TLP]: SNO TOKEN

### ISSUE THREAD

**Issue by fanyinan2008** [soonaverse/soonaverse-dao#812]
### Email

fanyinan2008@gmail.com

### Company Name

SnowMan Finance

### Your Position

Founder / Co-Founder

### Name

Scott Fan

### Have you already done a public sale?

No

### Files and other information

```shell
SnowMan is the first leverage yield protocol in the IOTA ecosystem.
Website: https://www.snowman.one/#/home
Twitter: https://twitter.com/SnowMan_Finance
```

**Comment by shonuffy** [comment]
Hi @fanyinan2008 could you please apply for the KYC application badge  (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview). After its approved you will need to purchase the TLP KYC NFT (https://soonaverse.com/collection/0x779f686073adfd2c2962e1d4d749f13e179f8e0b), then our KYC vendor Driftwood will contact you.

**Comment by shonuffy** [comment]
Your badge has been approved. Please notify me here that you have purchased the NFT and I will verify and send your information to our KYC vendor.

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@fanyinan2008

**Comment by shonuffy** [comment]
@fanyinan2008 Can you please apply for this badge so I can give you access to the feature? https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/participants

**Comment by fanyinan2008** [comment]
Hi, thank you for your Email, I have applied.
Thanks. Regards

shonuffy ***@***.***> 于2022年9月27日周二 01:10写道：
