### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by MarlonMorales0** [soonaverse/soonaverse-dao#813]
### Email

marlon.morales@iota-plus.com

### Company Name

IOTAplus AG

### Your Position

Founder / Co-Founder

### Name

Marlon Morales

### Have you already done a public sale?

Yes

**Comment by shonuffy** [comment]
Could you please apply for the KYC application badge (https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/overview). After its approved you will need to purchase the TLP KYC NFT (https://soonaverse.com/collection/0x779f686073adfd2c2962e1d4d749f13e179f8e0b), then our KYC vendor Driftwood will contact you.
