### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by TFTIzaac** [soonaverse/soonaverse-dao#814]
### Email

izaac@thefanstogether.io

### Company Name

The Fans Together

### Your Position

Founder / Co-Founder

### Name

Izaac Marshall

### Have you already done a public sale?

No

### Files and other information

```shell
The Fans Together is the DAO bringing power back to sports fans and giving them a say through the use of web 3 DLT technology.
```

**Comment by shonuffy** [comment]
Your badge has been approved. Please notify me here that you have purchased the NFT and I will verify and send your information to our KYC vendor.

**Comment by shonuffy** [comment]
@TFTIzaac Do you want me to keep this request open?

**Comment by TFTIzaac** [comment]
> 

Hi Shonuff, sorry for the late reply, yes please. We have purchased the NFT.

**Comment by shonuffy** [comment]
Thank you

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@TFTIzaac

**Comment by shonuffy** [comment]
Can you please apply for this badge. https://soonaverse.com/award/0x061823d158d44ddc1703e9844586962e0e34801c/participants
