### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by TheGoldenRat** [soonaverse/soonaverse-dao#817]
### Email

shimmer.inu@gmail.com

### Company Name

Shimmer Inu Foundation

### Your Position

Founder / Co-Founder

### Name

GoldenRat

### Have you already done a public sale?

No

**Comment by TheGoldenRat** [comment]
KYC NFT purchased

**Comment by shonuffy** [comment]
Congratulations, you will be issued the KYC applicant award on September 26. This will give you time to set up your token and launch once Shimmer goes live on the 28th. 

Please go to wen2.soonaverse.com to test out the system to learn how to configure your token set up and launch strategy. Any mistakes you make on the mainnet CANNOT be reversed. Again, we highly recommend you go through this test run before you set up your token for the launch. 

Also, based on the updated guidance of our legal advisory, Native tokens cannot be purchased by users in the United States and Canada without a legal opinion that you are not a security. 

Thank you for going through our set up process and good luck

**Comment by shonuffy** [comment]
@TheGoldenRat

**Comment by TheGoldenRat** [comment]
Thanks.

**Comment by shonuffy** [comment]
@TheGoldenRat You are good to go
