### ISSUE TITLE
RMS instead of SMR shown on purchase pages of Wen test Soonaverse

### ISSUE THREAD

**Issue by craftingstudio** [soonaverse/soonaverse-dao#818]
When viewing any page where sending SMR tokens is required:

https://imgur.com/gallery/BVdQf4g

You're told to send "RMS" which is the address structure, not the coin, the better way to phrase would either be

"Send 0.x SMR to x address"
or
"Send 0.x SMR from a RMS address to x address"

**Comment by adamunchained** [comment]
thank you! This still very unfinished and it'll be improved.
