### ISSUE TITLE
[TLP]:

### ISSUE THREAD

**Issue by calosan24** [soonaverse/soonaverse-dao#819]
### Email

apeegyptianart@gmail.com

### Company Name

Ape Egyptian Art

### Your Position

CEO

### Name

Cayetano

### Have you already done a public sale?

No

**Comment by shonuffy** [comment]
Your badge has been approved. Please notify me here that you have purchased the NFT and I will verify and send your information to our KYC vendor.

**Comment by shonuffy** [comment]
@calosan24 Do you want me to keep this request open?

**Comment by calosan24** [comment]
Hi, How can I prove that I have bought the NFT?

**Comment by shonuffy** [comment]
@calosan24 Please respond to let me know this still an active request

**Comment by adamunchained** [comment]
closing due inactivity
