### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by MF080961** [soonaverse/soonaverse-dao#821]
### Discord Name

Mifer#4141

### Soonaverse Profile Id

0x3649f1ebd3dc05c3716608ea467bfa76f5bae42b

### Payment Action

Purchase NFT from Collection

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.4.

### Payment Sent to Address

iota1qpdxvh2t02zcee0sk2m653h0n8n2kt5hmz92k4dyhy5gh5yy9hmcw3tmm84

### Amount Sent

190

### Payment Message Id

7c7f2ac8f57993da21fea2b10a9f41acc2a49890cdf94c519facd803c0e486cf

### NFT Id

nn

### Comments

Airdrop calim
I can not claim my Soon token ouf of the NFT drop, all which is displayed in My soon account is the amount of token i bought 	2.711,91 SOON , but my Cumulative SOON Token Airdrop amount  of 636,88 i do not see displayed to claim- I am not a tec guy, i need help -- I am runing a window 11 on explorer. Thanks for helping me out, my email adress is mferlings@aol.com
```

**Comment by adamunchained** [comment]
@TangleAccountant - can you check if this person didn't get airdrop but should have?

**Comment by TangleAccountant** [comment]
This person got their airdrops. It looks like they've claimed a total of 820.41 SOON tokens in airdrops:

![image](https://user-images.githubusercontent.com/78708402/186426161-2c18fc66-b341-4777-83b3-f01c155e9058.png)

They also paid 1,482 MIOTA during the launchpad event to acquire 1,950 SOON tokens:

![image](https://user-images.githubusercontent.com/78708402/186426468-737ad4b6-b06d-4267-b9ac-3830ababb4f1.png)

820.41 + 1,950.00 = 2,770.41 SOON tokens in total. And this is the total on their profile:

![image](https://user-images.githubusercontent.com/78708402/186426669-54c98169-9d27-4394-b556-a5ec3610d94e.png)

**Comment by MF080961** [comment]
Thanks you so much. It is my mistake, which made you waste our time. I am sorry for that

But you cleared it up, I was not able to do!

Again thank you and sorry

 

Von: TangleAccountant ***@***.***> 
Gesendet: Mittwoch, 24. August 2022 15:10
An: soonaverse/soonaverse-dao ***@***.***>
Cc: Michael Ferlings ***@***.***>; Author ***@***.***>
Betreff: Re: [soonaverse/soonaverse-dao] [Payment Issue]: (Issue #821)

 

This person got their airdrops. It looks like they've claimed a total of 820.41 SOON tokens in airdrops:

 <https://user-images.githubusercontent.com/78708402/186426161-2c18fc66-b341-4777-83b3-f01c155e9058.png> 

They also paid 1,482 MIOTA during the launchpad event to acquire 1,950 SOON tokens:

 <https://user-images.githubusercontent.com/78708402/186426468-737ad4b6-b06d-4267-b9ac-3830ababb4f1.png> 

820.41 + 1,950.00 = 2,770.41 SOON tokens in total. And this is the total on their profile:

 <https://user-images.githubusercontent.com/78708402/186426669-54c98169-9d27-4394-b556-a5ec3610d94e.png>
