### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by HellGuerra** [soonaverse/soonaverse-dao#823]
### Discord Name

@HellGuerra

### Soonaverse Profile Id

0x05749e6f1aafc2841f732f63edc2f1801c9452e5

### Payment Action

Purchase NFT from Collection

### Payment Problem

I made a purchase and did not receive an NFT nor a refund.

### Wallet Type

FireFly

### Wallet Version

1.6.5

### Payment Sent to Address

iota1qr2w65528nntput75n2kkgzd9lz0sdtpryu8tqtz6zpq4szqsk7x5tn6uk9

### Amount Sent

1Mi

### Payment Message Id

e6d376cafdd2240cfc13319277b3fbbfbe0632ae426ede150fe27d95d62399da

### NFT Collection Id

https://soonaverse.com/collection/0x5877e5de23683a6978611cdfbbf9c18af48c11b7

### Comments

```shell
I wrote in Discord (https://discord.com/channels/892481940953915433/917930917710925864/1004741661030621205) and they told me to fill out this form. I was trying to buy several NFT from the IOTA MONKI$ collection, however, one of them failed. On discord I added screenshots to show that even though the payment was done, the countdown to make the transfer was still running, until it reached 0.
Thank you.
```

**Comment by adamunchained** [comment]
There was a bug. This should be resolved in upcoming release. 

I've manually refunded you 1Mi from our test wallet: https://explorer.iota.org/mainnet/message/2fe80c8ec336181cddebd29e3a5463729dd40896a3ae347367f36765cce80488
