### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by TomRana** [soonaverse/soonaverse-dao#825]
### Email

ranatom@gmail.com

### Company Name

bikeguide.tirol

### Your Position

Founder / Co-Founder

### Name

Thomas Holaus

### Have you already done a public sale?

No

**Comment by shonuffy** [comment]
Hello Thomas. Have you applied for the KYC applicant award? I need you to have this badge so you can buy the KYC NFT. https://soonaverse.com/award/0x4d02b346167cca51bec4a20576dd4c75a5a35ec9/participants

**Comment by shonuffy** [comment]
Please advise if this is something you still want to pursue

**Comment by shonuffy** [comment]
@TomRana Please respond to let me know this is still an active request

**Comment by adamunchained** [comment]
closing due inactivity
