### ISSUE TITLE
NFTs mislabeled as 'Available' when not for sale and showing incorrect price.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#828]
Some NFTs aren't available, but display on the marketplace page as 'Available'. NFTs that are affected by this bug also have their prices show up incorrectly on the marketplace page and are filterable by the incorrect price. Example:

![image](https://user-images.githubusercontent.com/38050901/184723448-eb17f3fb-ab54-4102-bf2f-9c7abf8d3008.png)
![image](https://user-images.githubusercontent.com/38050901/184723811-cece206e-436a-4ed0-bfa1-16c4483913aa.png)

**Comment by adamunchained** [comment]
stale, this should have been fixed in previous release. If this is still an issue, please re-open.
