### ISSUE TITLE
[TLP]: Talisman

### ISSUE THREAD

**Issue by mookum93** [soonaverse/soonaverse-dao#830]
### Email

mookum93@gmail.com

### Company Name

Talisman

### Your Position

Founder / Co-Founder

### Name

Yanni Jacobs

### Have you already done a public sale?

No

### Files and other information

```shell
My sister an me have created a collection of hand painted artwork.
The Idea behind it is that anybody who bought our NFT will get the original ,hand painted nft, included (The costumer are able to send the shipping adress via email).
There are around 100 paintings we have planed . Some are done yet and ready to launch.
The theme is all kind of krypto.
```

**Comment by shonuffy** [comment]
Thank you. Are you applicant @yammi on the Soonaverse? Not seeing a "yanni" or your project name in any of the applications.

**Comment by shonuffy** [comment]
@mookum93 Please advise if this is something you still want to pursue

**Comment by mookum93** [comment]
Hello … I want to release a nft project . But i think I tried it wrong .
The project isn’t released as yammi ore on any other name.

shonuffy ***@***.***> schrieb am Mo. 5. Sept. 2022 um 07:57:

**Comment by shonuffy** [comment]
Please go to the discord support to address issues around NFTs. I will be closing this issue. Thank you.
