### ISSUE TITLE
#WEN Token Chart time and wrong balance

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#831]
**Describe the bug**
Tradingview on wen.soonaverse doesnt refresh my balance after i offered some tokens for sale, balance says still 100.000 Mario token.
Second thing, the timeragne on the token chart with one minute should be replaced with 1 Month instead, one minute doesnt make much sense.

**To Reproduce**
Check here
Offer some mario for sale, balance stays 100.000

**Expected behavior**
balance should be shown as balance - current offered tokens

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/185871566-0e05704c-f190-4871-869a-5bc4049456f7.png)

**Comment by adamunchained** [comment]
@gundavri Balance should considered amount locked for sale. See distribution record. Please remove.

please remove “1m”, it should be just 24h and 7d

**Comment by adamunchained** [comment]
I've removed the 1m in the chart.
