### ISSUE TITLE
#WEN Zero in fields is not a placeholder

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#832]
**Describe the bug**
The number zero (0) in the amount fields to buy or sell tokens is not an [HTML placeholder](https://www.w3schools.com/TAGS/tryit.asp?filename=tryhtml5_input_placeholder) but actually in the field.
![image](https://user-images.githubusercontent.com/7383572/185873487-55bdc187-ffaf-4667-8502-d5b66576c944.png)

**To Reproduce**
1. Go to the trading view
2. Click on any field and start typing
3. The 0 remains and it can be an issue

**Expected behavior**
The 0 should be an HTML placeholder
Once clicked in the field the zero should not be part of the input

**Screenshots**
![image](https://user-images.githubusercontent.com/7383572/185874277-324102a2-b188-4c8d-9879-a25b1ba5c22c.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chromium
 - Version 104.0.5112.79 

**Smartphone (please complete the following information):**

**Additional context**
How it is in Soonaverse:
https://youtu.be/S5FSKjL_-tA

How e.g. Bitpanda does it:
https://youtu.be/MrfLrtB1iaM

**Comment by humaint** [comment]
i agree
Expected behavior
The 0 should be an HTML placeholder
Once clicked in the field the zero should not be part of the input

**Comment by adamunchained** [comment]
yeah, as per #838 I think it might actually make sense to default 24h avg. price and make limit price default.

**Comment by humaint** [comment]
i would still keep 0 placeholder, you have the quick options for predefined states

**Comment by adamunchained** [comment]
Fair enough. Do we want to default to limit price then?

**Comment by adamunchained** [comment]
changed to place holder, #839 will fix validations.
