### ISSUE TITLE
#WEN input fields not checked, error comes later

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#835]
**Describe the bug**
The amount field allows other characters besides numbers (and comma/dot) and the error message is displayed only once the transaction is being signed

**To Reproduce**
1. Go to the trading page
2. Insert amount with any character
3. Confirm the transaction
4. Sign the transaction
5. Error is visible

**Expected behavior**
The input field should verify if there are other characters besides numbers and separators (comma or dot) and remove those automatically or display the error immediately

**Screenshots**
Input with non valid characters `ßß`
![image](https://user-images.githubusercontent.com/7383572/185876601-5b5a39ba-925f-41ab-b6e7-784216609593.png)
Goes through first verification (of course the numbers are off):
![image](https://user-images.githubusercontent.com/7383572/185876844-6314f0a9-61f5-494b-9aa0-5fd4bc08bb97.png)
Error shown after signing the transaction in metamask:
![image](https://user-images.githubusercontent.com/7383572/185872001-502c5b42-dee5-437a-9356-781fb0cc2362.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chromium
 - Version 104.0.5112.79 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
Only allow numbers in inputs on SELL/BUY
