### ISSUE TITLE
#WEN Order total min value is wrong, although 24h VWAP is selected

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#836]
**Describe the bug**
Error message about total value is shown after signing the transaction although the `24h VWAP` proposed sell price is selected

**To Reproduce**
1. Go to token trading
3. Try to sell
4. Select 24h VWAP limit price
5. Set 1 Mario token amount
6. Review
7. Sign
8. Error message is shown

**Expected behavior**
The system should automatically select a proper price that does not result in an errror while signing the transaction with metamask

**Screenshots**
![image](https://user-images.githubusercontent.com/7383572/185877331-40b632c0-e86a-4107-8cd4-cd76f71a3df4.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chromium
 - Version 104.0.5112.79 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
Will be solved part #839
