### ISSUE TITLE
#WEN token $MARIO

### ISSUE THREAD

**Issue by Opensailor6927** [soonaverse/soonaverse-dao#837]
Unable trading $MARIO

**Comment by Opensailor6927** [comment]
I have been able to claim the $MARIO token, so far everything is perfect, but I cannot trade it. There is no click to do it
![Screenshot_20220822-100623_MetaMask](https://user-images.githubusercontent.com/111735894/185878472-9baf559c-2dce-4f73-984b-26ff7f05339b.jpg)
![Screenshot_20220822-102628_MetaMask](https://user-images.githubusercontent.com/111735894/185878505-7653f7b3-8ba6-40e8-8f69-42a5f92014bc.jpg)
![Screenshot_20220822-102635_MetaMask](https://user-images.githubusercontent.com/111735894/185878517-d451c306-e149-4175-9dbb-7512a662cf65.jpg)
![Screenshot_20220822-102648_MetaMask](https://user-images.githubusercontent.com/111735894/185878521-de870a3b-c7ae-456d-be65-1e57120befad.jpg)

**Comment by Opensailor6927** [comment]
It's fixed, I had to verify my wallet address

**Comment by adamunchained** [comment]
Did you get any reasonable alert? or why did you get confused?
