### ISSUE TITLE
#WEN Buy with market price, error after signing

### ISSUE THREAD

**Issue by antonionardella** [soonaverse/soonaverse-dao#839]
**Describe the bug**
Error message about total min value is shown after signing the transaction although the `market price` proposed buy price is selected

**To Reproduce**
1. Go to token trading
3. Try to buy
4. Select market price
5. Set 012 Mario token amount
6. Review
7. Sign
8. Error message is shown

**Expected behavior**
The system should automatically select a proper price that does not result in an errror while signing the transaction with metamask

**Screenshots**
![image](https://user-images.githubusercontent.com/7383572/185880687-3d188b90-81f6-4830-8347-130bdfe6ccb8.png)

**Desktop (please complete the following information):**
 - OS: GNU/Linux
 - Browser Chromium
 - Version 104.0.5112.79 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
@humaint - there is a minimum of 1 MIOTA / RMS on the order. We need to implement validation on the front-end for this.

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=5819%3A51312

error state added
