### ISSUE TITLE
#WEN The order of the Date column in the My trading module

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#840]
Currently in the `MyTrading` module, the `Date` column is placed between `Price` and `Amount`, which doesn't seem like to be very appropriate when users are generally used to having the 3 number columns calculated to check the results. Please consider placing the Date column in front of Price.

**Comment by adamunchained** [comment]
Yeah I agree. @humaint shouldn't we make sure to make date first column on each tab?

**Comment by humaint** [comment]
![SCR-20220823-dxf.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/88c60101-e0e4-4116-933f-64c6c9ed0c10)

@Gundavri let's move the columns as described on the pic (other my trading tabs will be the same except not showing type columns)
