### ISSUE TITLE
#WEN Orderbook shows only 9 open Orders

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#841]
**Describe the bug**
Orderbook shows only the cheapest 9 open orders.

**To Reproduce**
1. Go to ['wen.soonaverse.com'](https://wen.soonaverse.com/token/0x022e665ad6105959cbe9696d604761c8d2d3cb9d/trade)
2. Orderbook shows only the cheapest 9 open orders.

**Expected behavior**
show all orders, make scrollable, more pages, or something like this

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/185881369-5748309a-0446-4659-b48a-e7572940c8f3.png)

**Comment by adamunchained** [comment]
This is desired behaviour. We don't expect to make that list scrollable atm. You can round it up to higher decimal and it'll give you different overview.
