### ISSUE TITLE
#WEN there should be a link from tokenoverview to tradingpage of the token

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#842]
**Describe the bug**
There should be a link from the tokenoverview to the tradingpage/tradingpairs on the token overwiew page.
When i click on a token in my profile i land on the token overview, but there is now way to the tradingview without clicking on tokens on the left side and then on trade.

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/185883079-b95aa4c8-fc85-430e-9dbb-292de4aa74ad.png)

**Comment by humaint** [comment]
there is already a condition to show Trade token button on the token overview page. 

@Gundavri pls update the logic so it will show button the trade button to all available tokens, like this one https://wen.soonaverse.com/token/0x87cb9c0de98223de944ff60c558a9641b8d8d945/overview

**Comment by Gundavri** [comment]
@humaint I don't see any trade buttons in the link you provided. We do have Trade button and the logic is that it is shown after the cooldown has ended. What do you want me to change in that?

**Comment by adamunchained** [comment]
@Gundavri - when something is pending with @humaint or me, make sure to re-assign it to us.
