### ISSUE TITLE
#WEN Weird format for time/date in tradinghistory

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#844]
**Describe the bug**
Weird data format in tradinghistory for trades older than 1 day

![image](https://user-images.githubusercontent.com/18002532/185921123-fbd30dec-d937-46aa-9152-a78312ac849b.png)

**Comment by adamunchained** [comment]
We've a limited space so we show "-1d" = -1 day.

@Gundavri make sure "d" is translatable and show it as a full word. "day", "week", "month"

**Comment by adamunchained** [comment]
@humaint - we have to show full word so it works in other language. Let me know if you propose different approach.

**Comment by adamunchained** [comment]
Fixed and changed to relative time.
