### ISSUE TITLE
#WEN Tokenoverview

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#845]
**Describe the bug**
In the tokenoverview their is a bug by the displaying of claimable tokens.
I bought some vader and mnemo2 tokens, they landed in my firefly wallet, but the token page still says i can claim them.

**Expected behavior**
hide tokens i cant claim, because i didnt recived them by airdrop

**Screenshots**
![image](https://user-images.githubusercontent.com/18002532/186020612-70c9241a-48d3-4e08-8de6-b6c687d55f44.png)

**Comment by adamunchained** [comment]
fix will be released tonight
