### ISSUE TITLE
#WEN too many zero

### ISSUE THREAD

**Issue by celarium3945** [soonaverse/soonaverse-dao#846]
**Describe the bug**
the display is not very readable due to numbers with 6 zero after the "."
3 zero is by far sufficient
history is not fully readable

**To Reproduce**
go to token, click on Mario

**Expected behavior**
3 zero is by far sufficient after the "."

**Screenshots**
![image](https://user-images.githubusercontent.com/103221824/186022147-f202f682-8f10-4ffe-9035-2bcedc3b2a01.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
@humaint - maybe on mobile we reduce to no zeros? what do you think?

**Comment by humaint** [comment]
I don't like showing "different numbers" on mobile and desktop. I would keep as less zeros as possible everywhere if possible, but not sure what are the limitations.

**Comment by adamunchained** [comment]
yeah, I do agree it should be consistent. Although this is very tricky as it might be very different per each token. I guess we will have to leave this one parked for now and see how it plays out.

**Comment by celarium3945** [comment]
Please also take care of the "historique" windows that is not fully readable (can't see the right part)

**Comment by adamunchained** [comment]
We've done numerous improvements on trading screen to resolve these issue. If there are still pending other issues feel free to reopen.
