### ISSUE TITLE
#WEN Sending wrong token doenst refund the token

### ISSUE THREAD

**Issue by 2g4y1** [soonaverse/soonaverse-dao#847]
**Describe the bug**

Hi guys, experimented around a bit and found out when i try to sell  x amount Mario token and sending x Peach Token (selfminted ff) i dont get the wrong sent token refunded

Payment: https://explorer.shimmer.network/testnet/block/0x040554f7afa69bd65ba42c2059cdce2a6b36ac8d9e30451835d8fc41fd26b29a
Refund: https://explorer.shimmer.network/testnet/block/payment-in-progress-1661250026623

**To Reproduce**
Sell a token where you need to send the token from FF
Send another token then expected, Peach Token instead of Mario Token
There is no refund of the wrong sent token.

**Expected behavior**
fget refund when send a wrong token

**Screenshots**

What did i do?
![image](https://user-images.githubusercontent.com/18002532/186134255-3bc7481d-9fa0-45d6-846e-266d797bd3d4.png)

![image](https://user-images.githubusercontent.com/18002532/186135136-8f324ae3-c166-4590-b6d6-c60c862258c8.png)

**Comment by adamunchained** [comment]
@boldizsar-unchained - hornet responds "{"route":"blocks","httpStatus":400,"code":"400"}"

It seems 400 error code is responded for block id 0x61e5e41e64646c5858e1794627252b728eeb8e1a

Error on the console
```trigger_transactionWrite
0x61e5e41e64646c5858e1794627252b728eeb8e1a {"route":"blocks","httpStatus":400,"code":"400"}```

It might be an issue on our Hornet node although why do we trying to read this block? It does not exists.
