### ISSUE TITLE
#WEN: Firefly Connect - Comma Separator Wrongly Submitted

### ISSUE THREAD

**Issue by GerritoMuc** [soonaverse/soonaverse-dao#851]
**Issue:**
- While Claiming the Mario Token Airdrop I encountered reproducible an issue in transferring the right token amount to claim the airdrop.
- This seems to be caused as a "." as separator is transferred to Firefly instead of the "," 
- This leads to the wrong amount to be sent (e.g. 992 SMR instead of 0,0992 SMR) and ultimately rejection
![image](https://user-images.githubusercontent.com/98845966/186264239-77d996ac-0643-4b42-99b4-ebe0bd11f065.png)

**Steps to reproduce the behavior:**
1. Select English Profile on Soonaverse
2. Select German Profile on Firefly
3. Perform a transaction that causes a <1 SMR token exchange (e.g. Token Claim) which results in a "." separated value
4. Click on Firefly Button to transfer the amount automatically
5. Try to send this amount to approve the transaction on Soonaverse of step 3

**Expected behavior**
Amount is approved that was automatically transferred without a separator issue = in German Case a ","
![image](https://user-images.githubusercontent.com/98845966/186264785-9a9c3262-0a79-4bb7-ae6a-c3474f1a6ead.png)

**Screenshots**
Soonaverse:
![image](https://user-images.githubusercontent.com/98845966/186263037-d582b6d8-0e12-4a13-b47d-c506ec8378f1.png)

Firefly:
![image](https://user-images.githubusercontent.com/98845966/186263208-d602fa11-2be3-41de-80a4-38d0c8bb529d.png)

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version 104.0.5112.102 (Offizieller Build) (64-Bit)

**Comment by adamunchained** [comment]
I’m sorry but this is clearly a Firefly issue. It should support both “,” and “.” Within the url. Maybe we can pass parameter within the URL to indicate language or Firefly disallow decimals within deep link URL.
