### ISSUE TITLE
#WEN: 2 Token Claims inside of the 5 Minute Range Fail

### ISSUE THREAD

**Issue by GerritoMuc** [soonaverse/soonaverse-dao#852]
**Bug**
Trying to claim another token, while the 4 minutes timer is still running for an older claim fails.

**Steps to reproduce the behavior:**
1. Go to Tokens in Soonaverse Profile
2. Claim First Token Airdrop 
3. After finalization try to Claim Second Token Airdrop available 
4. Transaction Window is closed with message "Claim Successful" <- which is of the First Token Claim action

**Expected behavior**
Second Token Airdrop Claim action should start a new counter.

**Desktop**
 - OS: Windows
 - Browser Chrome
 - Version 104.0.5112.102 (Offizieller Build) (64-Bit)

**Comment by adamunchained** [comment]
Claim token pop-up is not differentiating progress between different claims. I suspect this is due how we store claim order id in the cookie. Please investigate and fix.

**Comment by Gundavri** [comment]
@adamunchained I think you've already fixed this

**Comment by adamunchained** [comment]
@Gundavri - did you test the claim? Did the modal worked?

This is current bug in production so please make sure to test above before we close this.

**Comment by adamunchained** [comment]
fixed
