### ISSUE TITLE
#WEN: No Transaction Amount Control in Placing Sell Order

### ISSUE THREAD

**Issue by GerritoMuc** [soonaverse/soonaverse-dao#853]
**Issue**
While Placing a Sell Order there is no final check on the Token Amount actually sent. This leads to unwanted bid amounts placed if a user types faulty values by mistake inside of Firefly.

**To Reproduce**
1. Go to Token Trading
2. Place a Sale Order with 100.000 Mario Tokens
3. Confirm MM transaction
4. Type 100.010 Mario Tokens to be sent in Firefly Wallet (issues can happen as for native tokens there is a manual typing required)
5. The transaction is accepted by the platform = A user places a wrong sell order

**Expected behavior**
As for Buy Orders or any transaction that involves a non-conformant amount of tokens sent, this transaction should have been revoked with "invalid amount send" error and tokens to be refunded to sender.

**Screenshots**
![image](https://user-images.githubusercontent.com/98845966/186501651-9909e886-d4e3-4529-9b4c-96b22c1243f8.png)

**Additional context**
Transaction: https://explorer.shimmer.network/testnet/block/0x3af0ad5cf8434f4b6c93224e23b972f77eb45381b82e3a187dd222379d4c78d9

**Comment by adamunchained** [comment]
This actually desired behaviour (it's allowed to support different amount). This will be avoided once deep links are enabled for native token transfer.
