### ISSUE TITLE
#WEN: Sell Order - Fees Appear on the Seller Side FF as Unclaimed Transactions

### ISSUE THREAD

**Issue by GerritoMuc** [soonaverse/soonaverse-dao#854]
**Issue**
Upon successful selling of tokens via the Token Trading Pad the Fees (0,25% & 2,25%) are deducted . These fee transaction are shown in addition as "unclaimed" transactions in Firefly. This is misleading for the user as it seems as if Fees are deducted twice (once from the selling price itself and additionally via the Firefly Wallet).

**To Reproduce**
1. Go to Token Trading
2. Place a Sell Order of Tokens (Market or Limit Sale) 
3. Upon fulfillment the transactions are processed to show the fees

**Expected behavior**
No additional fee transactions should be shown on the Sellers FF wallet or the complete token sale price shall be accounted to the Sellers FF wallet.

**Screenshots**
Sell:
![image](https://user-images.githubusercontent.com/98845966/186515523-2ed92ad1-9f52-44dc-9bde-30cb2fb0dbff.png)

Firefly:
![image](https://user-images.githubusercontent.com/98845966/186515438-6ec886ca-1954-481e-8db4-3e870e20eb39.png)

**Comment by adamunchained** [comment]
Once Soonaverse Vault/Exchange Vault claims these fees, seller gets refunded with storage deposit. Hence it shows as unclaimed although I think "Firefly" is not showing it very clearly. 

-1.8 is not being deducted from seller. Firefly is just saying that 1.8 is pending return of a storage deposit.
