### ISSUE TITLE
#WEN: Ending Comma in Buy Order Lead to Invalid Pay Amount

### ISSUE THREAD

**Issue by GerritoMuc** [soonaverse/soonaverse-dao#855]
**Issue**
2 Issues appear when using the "." separator in the amount field in certain language combinations, the price is transmitted with a "." separator in FF which leads to invalid transaction ultimately.

**To Reproduce**
1. Firefly in German Profile
2. Soonaverse in English Profile
3. Use a "." separator in the amount field (e.g. purchase 5.000 -> should be 5000 Mario tokens) 
![image](https://user-images.githubusercontent.com/98845966/186518554-287ab9fa-db6e-4d2e-b545-f1e42f8efa81.png)
4. Confirm this transaction in MM
![image](https://user-images.githubusercontent.com/98845966/186518512-8bb13439-65a4-43f9-bab2-60343faa9f3d.png)
5. Use FF autoconnect to transfer the amount to be paid automatically
![image](https://user-images.githubusercontent.com/98845966/186518979-eab7e4e7-86f7-4436-9bfe-a4faf3f9df2c.png)
6. Confirm payment in FF

**Expected behavior**
The amount should be sent with a "," separator to Firefly Wallet.

**Comment by adamunchained** [comment]
We’ve investigated this. How is this our issue? It seems Firefly is not correctly translating 5.5 value. Firefly should work 5.5.
