### ISSUE TITLE
I think I didnt recieve a Payment for a NFT Transaction

### ISSUE THREAD

**Issue by medion62** [soonaverse/soonaverse-dao#856]
### Discord Name

medion62#5929

### Soonaverse Profile Id

0xC5D0726785062Cedc4c208F3a095A20611459436

### Payment Action

Sold NFT - Fixed Price

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.5

### Payment Sent to Address

iota1qrn7jz8pvhtz5am3rerj0f37h7vqa7tqmlmfakvatmaht49y6fpgxtas305

### Amount Sent

699

### Payment Message Id

3ec59dc9f98de7fe175ce132b54f5ecdde143b84ed0ab8f3b5587fb7c19db2f5

### NFT Id

https://soonaverse.com/nft/0x7944434e1043ce46ab58dcfd049f837d30d742df

### Comments

```shell
Hi guys, my adress is: iota1qrn7jz8pvhtz5am3rerj0f37h7vqa7tqmlmfakvatmaht49y6fpgxtas305

On the 30th of April somebody on soonaverse did buy my NFT: https://soonaverse.com/nft/0x7944434e1043ce46ab58dcfd049f837d30d742df for 749 MIOTA.

I checked all incoming transactions on my firefly wallet but this transaction above is missing. How can I verify that I did recieve the payment or is the NFT still mine? I have no clue.
thank you for your help
```

**Comment by adamunchained** [comment]
This has been processed, see here: https://thetangle.org/message/e4c9632cfa19e513a4595884feb3ffe8b1734e197a2a019c2680f6c82b9ea836

711.55 Mi was sent to iota1qrn7jz8pvhtz5am3rerj0f37h7vqa7tqmlmfakvatmaht49y6fpgxtas305
