### ISSUE TITLE
Inconsistent time zones in the token trading page

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#858]
**Describe the bug**
In the token trading screen, the time in the user's time zone is shown on the right side of the trading history header, but the time in the list below and in the My trading list is shown in another time zone. This causes difficulties for users to check their records.

**Expected behavior**
Please set the times displayed on this page all according to the user's time zone.

**Comment by adamunchained** [comment]
This is weird. I don't have this issue. Can you please provide screenshot or video?

**Comment by csxiong** [comment]
![image](https://user-images.githubusercontent.com/86828398/188291579-99847e0b-49af-4a0f-9d09-5a88e58186e4.png)
From here, we can see that the time on the right side is the same as my local time.

But....
![image](https://user-images.githubusercontent.com/86828398/188291604-ea975442-eb78-4db5-9283-5f9cb6f29c16.png)
![image](https://user-images.githubusercontent.com/86828398/188291612-37dfc46a-dfeb-4a95-bb0e-b72323ea4657.png)
![image](https://user-images.githubusercontent.com/86828398/188291621-55ac1636-ab56-4dbe-aef3-e983d47563dc.png)
But as you can see here, the time shown on My trading is 8 hours different from my local time, so I presume that the UTC time is used here, not my local time UTC+8.

Trade History also uses the UTC time,not my local time UTC+8.
![image](https://user-images.githubusercontent.com/86828398/188291707-3fc6d127-c4a0-4544-9321-f719b171d722.png)

So I strongly suggest that all these times be consistent or have its time zone clearly marked with it. Also, considering the time difference, please show the date in full instead of using `-xx days`, For example 2022-9-4 08:27:40 (UTC+8). If it is technically possible to match the time zone set by the user's computer, then it is OK to not display the time zone.

**Comment by adamunchained** [comment]
Thanks @csxiong….Yeah it should be all in user’s browser timezone. Let me investigate this.

**Comment by adamunchained** [comment]
I can't reproduce this, for me, its always all in my timezone. @humaint are you having this issue?

**Comment by humaint** [comment]
@adamunchained it's definitely a bug, see my screen![SCR-20220905-l84.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/2e8c5729-ed27-4110-9f05-864bb23d6928)

MY USE CASE: current time does not use the local time-format and time in the Trade history does not have AM/PM

**Comment by adamunchained** [comment]
@gundavri ~ pls check we use angular date pipeline correctly everywhere
