### ISSUE TITLE
Lack of quick jump to another token on the token trading page

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#859]
**Describe the bug**
Now on the token trading page, if you want to jump to another token's trading page, you need to go back to the token's list first, and then click on it to enter its trading page, which is a bit tedious to operate.

**Expected behavior**
Please consider the following methods for optimization.
1. Replace the text component of the token with a drop-down list component. Toggle the line item in the drop-down list to quickly jump to another token trading page.
2. Change `Website` to `Info` and click it to jump to the info page of that token, while the original Website can be accessed in the Info page.
3. Besides, the `available` tag component, with its two left page elements: `token name` and `Favorite`, is not horizontally centered. Need to tweak the style.

**Comment by adamunchained** [comment]
Those are great ideas. @humaint / @Filip356258 can you investigate if improvements are needed and let's schedule within next sprint....

**Comment by humaint** [comment]
I agree, thanks csxiong. I will get designs for 1 and 2 ready. 3 is assigned already as a bug.

**Comment by humaint** [comment]
quick option added here
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=5896%3A51957

+ header is rearranged 
+ token website link changed to token info link

dropdown here
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=5898%3A52689

**Comment by adamunchained** [comment]
@Gundavri - It's important none of the data within modal will not load until it's open.

**Comment by humaint** [comment]
@Gundavri don't forget about the mobile version
https://www.figma.com/file/7ER3oGXPRXHCEoUGuUfSLl/Responsive?node-id=3577%3A27314

make sure all paddings/margins
