### ISSUE TITLE
Search no longer works in some areas

### ISSUE THREAD

**Issue by Travetown** [soonaverse/soonaverse-dao#860]
When I go to the NFT overview in my profile and enter a name, the display hangs. (screenshot #1)
Likewise, the search within a collection is not executed. (screenshot #2)

<img width="1163" alt="Bildschirmfoto 2022-09-04 um 12 05 00" src="https://user-images.githubusercontent.com/66588710/188308135-533dcfcc-3f6e-43b3-89d8-747c2d3e3cdc.png">

<img width="1091" alt="Bildschirmfoto 2022-09-04 um 12 04 28" src="https://user-images.githubusercontent.com/66588710/188308119-467e2356-f5b5-446c-9fe6-cd09c2e4a8d0.png">

Desktop 
 - OS:macOS 12.5.1
- Browser [Brave 1.42.97 / Safari. 15.6.01

**Comment by adamunchained** [comment]
This is due new indexing. Let’s change this screen to query Algolia instead.
