### ISSUE TITLE
[Payment Issue]: SOON token claiming, sent 1.34mi to address, but tokens were not claimed, nor 1.34mi refunded

### ISSUE THREAD

**Issue by Tombaaa** [soonaverse/soonaverse-dao#862]
### Discord Name

Tombaa#8643

### Soonaverse Profile Id

0xA5F942A9CB17217cf6603166F5eF9228A7EC090E

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

1.6.4

### Payment Sent to Address

iota1qpcqyw4zwx090r9pjxvej7e6qf82e9a5cp8t7scgf2ujwp6gw6kmkkwmdh5

### Amount Sent

1.34Mi

### Payment Message Id

d103143319ad98e1a535f81699917f22eafc1d4e12c5c5254778ed4c82960b9d

### Comments

```shell
tried to claim my SOON tokens, sent the 1.34mi to the adress indicated via Firefly, but the timer counted down to zero and the SOON tokens were not claimed nor the 1.34Mi refunded.
```
![image](https://user-images.githubusercontent.com/77152394/189282043-1bcfea8a-cce3-4c0c-a410-af853a82d828.png)
![image](https://user-images.githubusercontent.com/77152394/189282074-d08a29e9-d1fa-4726-8764-9dcf1e00b368.png)
![image](https://user-images.githubusercontent.com/77152394/189313928-57d57985-abcf-47fc-893e-6f9247b0f4b5.png)

**Comment by Tombaaa** [comment]
I now claimed them again, for 1.32Mi, worked this time.
But still would like to get back my 1.34 Mi I paid in the first attempt.

**Comment by adamunchained** [comment]
You claimed SOON tokens 1520 for 1.34 M successfully. Modal might not show the receiving of transactions correctly but you've receive the token allocation on 26th of August after your claim: https://thetangle.org/message/9f480f716fd8c1a12cf24a77390f53be3f700e96b17e94f568da86b8e8e8cc4f

1.32 Mi claim must have been for another airdrop.
