### ISSUE TITLE
Partnered/connected spaces not displayed anymore

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#866]
**Describe the bug**
Seemingly the connections between spaces is not visible anymore (where u can see which spaces XP are recognized in another space). On september 3rd I was still able to see those connections since I prepared a list of connected/partnered spaces for the IotaPunks-Discord. 

**To Reproduce**
1. Just check any space that has connected spaces. Examples of 100% surely connected spaces follows below:
2. [IotaPunks](https://soonaverse.com/space/0x4dcfd426d4f47019fce9502bf484b51b19f84822/overview)
3. [Iota Trading]Cards (https://soonaverse.com/space/0x965c2cd6b462150b05da0d2cd67a4a5ee46f780e/overview)
4. [Labralords](https://soonaverse.com/space/0xe59e578c515b303d16e33476466553664954bb48/overview)

**Expected behavior**
There should be a table-like view on the right side of a space with connected spaces and the weight they accept each others XP

**Screenshots**
![grafik](https://user-images.githubusercontent.com/104099536/189482422-21c87730-d450-478d-b1e1-660432c2aace.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Firefox]
 - Version [104.0.1 (64-Bit)]

**Smartphone (please complete the following information):**
 - Same with iPhone and Android based smartphones

**Additional context**
This is surely based on the last Soonaverse update (Release 0.13)

**Comment by tccflash** [comment]
Hi Markus from iotatradingcards.com here. Yeah please bring this feature back with the next version. Thats a absolute important feature for the whole IOTA NFT Community. 
Thx 🤙🏻

**Comment by Peratron** [comment]
We at #IotaPunks have formed many partnerships on Soonaverse. Only unfortunately no one can see this at the moment. Please integrate the feature again. Thanks 🤘

**Comment by pxdg2** [comment]
Please fix.

**Comment by YennaTech** [comment]
Requesting support on this asap please.. user experience is highly important

**Comment by DigiMine22** [comment]
Please bring this feature back, it is important to see  the partnerships for the users. Thx.

**Comment by labralords** [comment]
We're also affected by this.

**Comment by adamunchained** [comment]
I'm sorry for the late response. We've decided to shelf this feature as it didn't have significant adoption as well as it'll be hard to support on current version on Shimmer.

We might reimplement it in the future but it'll need significant redesign to be native on Shimmer.
