### ISSUE TITLE
sell order fullfil without following the book order

### ISSUE THREAD

**Issue by celarium3945** [soonaverse/soonaverse-dao#867]
**Describe the bug**
 the book order has at least the following ask :  2079 $soon available at 0.551 and 400 $soon available at 0.511.
a 300 $soon transaction was done at 0.500 without touching the previous ask (0.551 and 0.511)
![image](https://user-images.githubusercontent.com/103221824/189489783-41b4e65e-a8a9-459f-baa2-91dab73fb1e0.png)

**To Reproduce**

**Expected behavior**
  the order before 0.5 shall be fullfil first

**Screenshots**
![image](https://user-images.githubusercontent.com/103221824/189490151-34e2b648-78a4-4d2c-a4f2-6708ee394b93.png)

**Desktop (please complete the following information):**
 windows

**Smartphone (please complete the following information):**
NA

**Additional context**
na

**Comment by adamunchained** [comment]
@boldizsar-unchained - was this fixed with https://github.com/soonaverse/soonaverse/issues/1426 ?

**Comment by boldizsar-unchained** [comment]
> @boldizsar-unchained - was this fixed with [soonaverse/soonaverse#1426](https://github.com/soonaverse/soonaverse/issues/1426) ?

Though so, but know. Fixed here however
https://github.com/soonaverse/soonaverse/pull/1523

**Comment by adamunchained** [comment]
yeah I thought so
