### ISSUE TITLE
Change Token Pricing Views

### ISSUE THREAD

**Issue by TangleAccountant** [soonaverse/soonaverse-dao#872]
Prices on the main token listings page should be the "Mid" price. And the 24 VWAP on the specific token page should be changed to Current Price (which will be "Mid" as well).

**Comment by adamunchained** [comment]
Token price change as requested. We received very positive feedback from the community on this change.
<img width="1259" alt="Screen Shot 2022-09-16 at 8 58 11 PM" src="https://user-images.githubusercontent.com/130610/190839665-e16b0341-b8ae-415e-9a1f-05a8d804ffa6.png">

@humaint - FYI
