### ISSUE TITLE
Issue trying to add NFT to existing collection - "available from" Error (Not a Limited Edition Collection)

### ISSUE THREAD

**Issue by BigDom4Reelz** [soonaverse/soonaverse-dao#874]
**Describe the bug**
I'm having an issue creating NFTs for a collection that went active at the end of last month. It's an empty collection but when I go to create the NFT(s), either individual or multiple, I get an error with the "available from" date upon confirming the transaction in MM. It seems the date is locked to the collection active date and there doesn't seem to be an option to change it. 
I don't think I had this issue whilst playing around on wen... as there was an option for setting the active date and time (using ISO 8601 standard format data) in the csv file, which appears to have disappeared. 
The collection is not a limited collection and was published at the end of August.

**To Reproduce**

**Expected behavior**
NFT to be added to the collection.

**Screenshots**
N/A - Simple "available from" error message

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave 
 - Version: 1.43.89

**Smartphone (please complete the following information):**
- N/A - Not Tested

**Additional context**

**Comment by adamunchained** [comment]
Was this CLASSIC collection?

**Comment by BigDom4Reelz** [comment]
> Was this CLASSIC collection?

It was a Generated collection. As there is an option to make it a limited collection or not I'd assumed I'd still be able to add to the collection. Is it only possible for classic?

**Comment by adamunchained** [comment]
Will be fixed part of the next release, see https://github.com/soonaverse/soonaverse-dao/issues/1022
