### ISSUE TITLE
Some data in the metadata generated by the token trading is suspected to be incorrect.

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#878]
**Describe the bug**
There are two fields in the metadata generated in the token trading: `owner` and `previousOwner`, which literally means the address of the buyer and seller of this trading, but these two fields are the same in all the metadata generated in the token trading so far. It is possible that this is an get/set error.

**To Reproduce**
check this: https://explorer.iota.org/mainnet/message/03bbc9655d52b9e3b13d41027b94b3f28de713d39f0b39ad47e5c30f7c6907ff
or any msgs generated by token trading.

**Comment by adamunchained** [comment]
@boldizsar-unchained - it looks like previousOwner is set to buyer Id by mistake in Bill Payment. It should be seller uid.
