### ISSUE TITLE
[TLP]: 

### ISSUE THREAD

**Issue by PeterPanHH** [soonaverse/soonaverse-dao#879]
### Email

tim.meuler@web.de

### Company Name

German Cities

### Your Position

CEO

### Name

Tim Meuler

### Have you already done a public sale?

No

### Files and other information

```shell
Twitter: https://twitter.com/GermanCitiesNFT
Soonaverse: https://soonaverse.com/space/0x0db525b06c07abb4da71e431c24515ec0692dfcf/collections
```

**Comment by shonuffy** [comment]
Your badge has been approved, please purchase the TLP KYC NFT

**Comment by shonuffy** [comment]
@PeterPanHH Please respond to let me know this is an active request.

**Comment by adamunchained** [comment]
closing due inactivity
