### ISSUE TITLE
[Bug] Infinite repeat fetching of items on some Collections pages when scrolling down.

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#880]
**Describe the bug**
In some collection pages, when the total number of items that should be displayed on the page exceeds the number of items that can be fetched in a single retrieval, the drop-down fetching will result in the infinite fetching of duplicate items.

**To Reproduce**
1. Go to [this collection](https://soonaverse.com/collection/0xa54bb6b25d6e0853eade3c657679754055e1b792)
2. try to scroll down to the bottom.
3. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/86828398/192104629-d2e69035-35f9-4da5-8a83-5c8987f0ae6a.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome

**Comment by adamunchained** [comment]
This seems to be an issue with infinet scroll.

**Comment by adamunchained** [comment]
This was fixed and it'll be in prob in 20 min. It was due migration to new modular firebase functions.
