### ISSUE TITLE
Routing error of back button of member page in some cases.

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#881]
**Describe the bug**
In some cases, after clicking a certain NFT on the member page, clicking the back button, the route incorrectly jumps to the tokens page instead of the member page.

**To Reproduce**
1. Go to '[member page](https://soonaverse.com/member/0x0fc1e3b37b572ba462a8d9c7f781af246876ab64/nfts)'
2. Click on 'any nft'
3. Click on 'Back'
4. See error: route to the tokens page.

**Comment by adamunchained** [comment]
seems to be working well in upcoming release. I'm no longer able to reproduce it.
