### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Karaarl** [soonaverse/soonaverse-dao#883]
### Discord Name

Karaarl#1738

### Soonaverse Profile Id

0x7bFF622CbFa64fdc197F8412bd96b13AD2728c97

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

2.0.0 Shimmer FireFly

### Payment Sent to Address

smr1qpwuwtz9fhx6gv8jfgue7pp6rfl40nu0kgsj6cwrlhywcs0s5uegweh7lj6

### Amount Sent

10000 FEE

### Payment Message Id

0xb7312dda228ae2169bd70b4e3a2c6712cd38eb8a94f3f670821c7f611a17c6d4

### Comments

```shell
I wanted to trade some FEE tokens for some SRM tokens, but I sent it without the option "Gift-Deposit". The transaction is unclaimed and without an expiration time. Hopefully you can help.
```

**Comment by andyfront0** [comment]
Same problem. Sent $FEE to Soonaverse without expiration time but forgot to set gift deposit. Now unclaimed and stuck. smr1qpctnzj5lzxu5sqfe7ty3akukjmnwvp9hnqvsatqyxd4yeyyhkmrwvk9l62

**Comment by adamunchained** [comment]
there is no way for us to refund it. We have no funds to do it. You have to make sure you tick "git storage deposit"
