### ISSUE TITLE
[TLP]: Fjubots

### ISSUE THREAD

**Issue by Razorbob** [soonaverse/soonaverse-dao#887]
### Email

vincent.dibon@fjubots.io

### Company Name

Fjubots

### Token Link

https://soonaverse.com/token/0x7e3f0f240b33a151b6302f108eb09e7b6abbbc19/overview

### Your Position

Founder / Co-Founder

### Name

Vincent Dibon

### Have you already done a public sale?

No

### Files and other information

```shell
I would also like to point out, that I would like to change the Infographic and Token Icon. I have failed to realise that it automatically took the one of my test space and Token... (There is no option to change these right now)
```

**Comment by adamunchained** [comment]
closing due inactivity
