### ISSUE TITLE
[bug] Deep link error of tanglepay when open sale order in Fee/Smr pair

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#888]
**Describe the bug**
Deep link error of tanglepay when open sale order in Fee/Smr pair. The deep link opened at this point shows the wrong sending currency and amount, which will result in incorrect transactions and trades.

**To Reproduce**
1. Go to Fee/smr trading page
2. Click on 'sell tab' and make a sell order
3. Review and sell Fee
4. Check the tanglepay button and Click, You will find the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/86828398/192916990-48caaa36-29ca-44da-a4d1-5bc00d734412.png)

![image](https://user-images.githubusercontent.com/86828398/192917061-00d4c25b-2cb3-4c9a-b09c-f0d0138b2e2f.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by adamunchained** [comment]
@daihanqiao - do you guys now support deep link for native tokens?

**Comment by adamunchained** [comment]
Added support for deep link that was given to me by Firefly team but there seems to be some issues in the wallet.

**Comment by csxiong** [comment]
> 

not firefly deeplink, it's tanglepay deeplink.

**Comment by adamunchained** [comment]
TanglePay deeplinks were added a while back. This issue was resolved.
