### ISSUE TITLE
Collection not visible in search or filter

### ISSUE THREAD

**Issue by f15hfood** [soonaverse/soonaverse-dao#889]
**Describe the bug**
Hi Soonavese Team!
My collection is not visible in the collection search, nor I can add the collection in filter options in new created collections.
[Collection](https://soonaverse.com/collection/0x99331bc76b32037fbbc6442f3bd8031b64ce35d6)

**To Reproduce**
1. Go to Marketplace
2. Click on 'Collections'
3. Search for 'TangleBees'
4. See nothing.
5. Also not appearing in filter options while creating a new collection.

**Expected behavior**
Find the collection

**Comment by adamunchained** [comment]
Can you please provide steps to reproduce? It does not seems to be happening for me.

Note only approved collections are in the list.

<img width="2027" alt="Screen Shot 2022-10-13 at 8 29 33 PM" src="https://user-images.githubusercontent.com/130610/195755944-b7fd36f2-9706-4da9-a23e-f45d5cdb94a0.png">

**Comment by f15hfood** [comment]
Hi Adam!

The collection is approved since March, but since the last Update it was kicked out of the search.
Our newest collection is visible yes, the the OG from the Soonaverse start in March is missing
Collection --> [](https://soonaverse.com/collection/0x99331bc76b32037fbbc6442f3bd8031b64ce35d6)

You need to click "Filter&Sort" than choose "latest" and than the correct collections are appearing.

![grafik](https://user-images.githubusercontent.com/114679963/195767584-ef519f1c-001d-4ec0-a52b-a4f20571bc35.png)

bR
FisH
