### ISSUE TITLE
Warning when withdrawing NFT's

### ISSUE THREAD

**Issue by Travetown** [soonaverse/soonaverse-dao#892]
Withdrawing NFT's works great! But a warning should be integrated until Firefly can display NFT's. At the moment these NFT's are "disappeared". This could lead to confusion for many users.

**Comment by Travetown** [comment]
How the hell does the "invalid" label get there

**Comment by adamunchained** [comment]
It just default template you selected on Github. Don't worry.

We have added warning just now.
