### ISSUE TITLE
IOTA and SRM - Protect addresses

### ISSUE THREAD

**Issue by Travetown** [soonaverse/soonaverse-dao#894]
I would like to see the verified addresses of IOTA and SMR not visible to all. There is no reason for that and some privacy is quite nice after all. 
Wouldn't it be possible to open this area only for the owner of the account? For example, it could happen that someone collects addresses this way and unloads his ShitCoins. Besides, no one should care how much SMR or IOTA I hold on my private wallet. 

<img width="343" alt="Bildschirmfoto 2022-09-30 um 17 24 11" src="https://user-images.githubusercontent.com/66588710/193303634-de5985c0-5eaa-4fe5-b76c-1566cca0f7dd.png">

**Comment by SonicBoomz** [comment]
👍

**Comment by CptBananu** [comment]
If one wants they can detect ur wallet based on a Single NFT of urs without being reliant on ur verified addresses bc the tangle is all public.

But a simple method of keeping ur funds private is that u create a "middle wallet" from where u transfer ur soonaverse-profits to ur "private wallet". This is still visible to anybody who knows how to read the tangle but isn't as easy as just checking ur verified addresses

**Comment by Travetown** [comment]
I am completely aware of the possibilities. But that doesn't change the fact that it doesn't necessarily have to be made easy for everyone. It's as if my account number is publicly displayed everywhere and my balance is visible to everyone. I would then also still need a "secret" account to fix the "mistakes" of those who made the data accessible. 
**If someone gives me a reasonable reason why the data must be visible to everyone, I am happy to withdraw my request.**

**Comment by adamunchained** [comment]
There is no reason to be honest @Travetown - I think our team just hate false sense of privacy. When you don't show the widget you're giving a sense to the user that this information is private which in reality is NOT. It's all public including members details if you try to get them via API or just look at Tangle.

Few people have raised this in the past. It seems more people were concerns about this being shown so we've decided to hide it. It's now hidden in production and it will only show for the logged in user. Let's see how it'll be accepted.
