### ISSUE TITLE
[Payment Issue]: no refund

### ISSUE THREAD

**Issue by punikus** [soonaverse/soonaverse-dao#897]
### Discord Name

punikus#6149

### Soonaverse Profile Id

0xa965f9D3020Dde6F9991018987C0a365a4c7a025

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

2.0.0

### Payment Sent to Address

smr1qpr9mewrkjut9n2lzwluz5vxhmpz7yukz8f29kfrvpvfhgvsravcy74ufmq

### Amount Sent

10000 FEE

### Comments

```shell
I made an order to sell FEE for SMR, i followed the instructions and send 10000 FEE (same amount from the instructions) to soonaverse. I've got the message "invalid amount, try again" however FEE token is not back in my wallet nor on soonaverse in order book. All i can see in order history is that order has expired. If you can help, i would appreciate it, thank you 

I can not find message id in firefly shimmer, so i send you staff that may help...
Transaction ID 0xd93f6bcbdb37556426504bfe4fa30eb49af8f57788b5250cabb4de75e3718a37
My SMR adress  smr1qpyqzse56hfxhgen5h6pxtkjwjkvyakxadnkfyn78dxcuulcxhghkrmnm8x
```

**Comment by adamunchained** [comment]
Looking at transaction you've set storage deposit return. We're unable to accept these payments as we don't have funds to fund the transaction. Unfortunately looking at your transfer it'll be now stuck. You should never not gift storage deposit without expiry. 

<img width="808" alt="Screen Shot 2022-10-06 at 5 40 36 PM" src="https://user-images.githubusercontent.com/130610/194442717-c256146b-9bd7-4753-9897-1fc39537b116.png">
