### ISSUE TITLE
migrating a collection to shimmer loses the ability to modify it 

### ISSUE THREAD

**Issue by TanglePhunks** [soonaverse/soonaverse-dao#898]
**Describe the bug**
After migrating to the Shimmer network, you can no longer customize the collection. 
Edit Button is missing. 
![editbuttonmissing](https://user-images.githubusercontent.com/114867515/193459283-1ed08a5d-983c-47df-b852-dd205924b7f7.PNG)

E.g. change discounts

**To Reproduce**
Just press the "Mint on Shimmer" Button. (Only possible once per Collection)

**Expected behavior**
As possible before the migration, I would like to adjust the memer discounts. 

**Screenshots**
added.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Edge
 - Version 105.0.1343.53

**Comment by adamunchained** [comment]
We'll add enhancement for an ability to edit discounts and access for unsold NFTs in next sprint.

**Comment by adamunchained** [comment]
@humaint - are you happy if we just re-use edit collection but only allow those two fields to be editable?

**Comment by humaint** [comment]
yes, should be okay

**Comment by TanglePhunks** [comment]
any update on this?

**Comment by TanglePhunks** [comment]
Thx for update....

**Comment by adamunchained** [comment]
Edit Button enabled. You will be able to edit: 
- Access to collection 
- Discounts

All other fields are not editable as they've been engraved on Tangle and can't be edited.

**Comment by TanglePhunks** [comment]
thank you for implementing this enhancement! 
unfortunately nothing happens when i change the discount and click on the save button (nothing happens in metamask either)
I have deleted all cookies and also re-entered the network in metamask.

**Comment by adamunchained** [comment]
There was an issue. We've just pushed new update into the production that should fix it. It should be available within next 10 minutes.
