### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by RodrigoMarroquin** [soonaverse/soonaverse-dao#899]
### Discord Name

@RodrigoM#7380

### Soonaverse Profile Id

0x272Da4D67C344625fe338c1615ED6bab24A81E6A

### Payment Action

Other (Please describe in comments)

### Payment Problem

I made a purchase outside of the time window and did not get a refund.

### Wallet Type

Other (Please describe in comments)

### Wallet Version

1.6.5

### Payment Sent to Address

iota1qpsc58pt23k9ua8trnalnddz9z634uj3qhyg7vsx8ysnw8gqrv3ekzxpz3v

### Amount Sent

533.63 Mi

### Payment Message Id

04ce8d20a3c33d0d5205525f0d29afccbe156dea4b270b3f6f32a94b64e08942

### Comments

```shell
Hi, I was trying to buy around 660-670 SOON, I sent the payment of 533.63 Mi to the address on the payment window but it didn't arrived on time. 
I sent it from my wallet on Bitfore, not firefly nor Tangle Pay.
```

**Comment by adamunchained** [comment]
Payment has been refunded to sender. You will have to contact Bitforex support to find your payment. 

See refund: https://thetangle.org/message/cdaff01e10ce5f10c7d978f53e68def492bc1f370327ee225be2d093a8007ea9
