### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by AT22SOD** [soonaverse/soonaverse-dao#908]
### Discord Name

SOD#9530

### Soonaverse Profile Id

0x40764c5528ef04a195b79aa7bd1db38e2676db7f

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

2.0.0

### Payment Sent to Address

smr1qq4hndym40eu068qauxqgldn8htv6xl8gxyeh236t8l39pma05ecj37g0w0

### Comments

```shell
Good day.

On October 6th at 3:28 (Japan time), I wanted to swap FEE to SMR.
To do so, I sent 10,000 FEE to the account that appeared in Soonaverse, without expire limit, following all the steps and details of the popup. As I have always done when sending SMR, or IOTA, I have never had any problems before.

But this time I have not received the SMRs, and the FEEs are still unclaimed, as you can see in my profile:
https://soonaverse.com/member/0x40764c5528ef04a195b79aa7bd1db38e2676db7f/transactions
https://explorer.shimmer.network/shimmer/block/0x6066a056a37a97748e87c3227d8664e4423538aab6133eb82e92b0df33350680

I hope this incident can be solved.

Best regards.
```

**Comment by adamunchained** [comment]
Hi @AT22SOD 

You have sent 10'000 FEE with storage deposit unlock condition. We are not able to unlock these funds as we don't have SMR tokens to do so. 

When you send native token, you have to make sure you always "Gift Storage deposit". You should always never set expiration unlock condition to none.
<img width="657" alt="Screen Shot 2022-10-11 at 10 11 05 PM" src="https://user-images.githubusercontent.com/130610/195255549-2f58af06-c33f-4833-9fc6-d706ecec6c7b.png">
