### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by antonio10101010** [soonaverse/soonaverse-dao#911]
### Discord Name

@alexasturias

### Soonaverse Profile Id

0x6636B9a083E31bF1e12c2CA211c30AD158869398

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

TanglePay

### Wallet Version

1.4.5

### Payment Sent to Address

smr1qp49l2fcadzndd6la6e2e8djccenl6u6nvdspp722fvkw4kgr6t2xu0rs33

### Amount Sent

240 SMR

### Payment Message Id

0x2502e6ec82a36007becc0731e0ba225e46ef47dbc2075b83f06ae9aad4351823

### Comments

```shell
Hola,intente comprar 100 Soon con 240 SMR y no me aparecen en mi billetera,gracias
```

**Comment by adamunchained** [comment]
Your purchase was successful, here is your transaction on tangle: https://explorer.shimmer.network/shimmer/block/0x078b2b1328ab96f0912dcfce20605c1b4565bfa0bd6f0487879f6c510ace8807

**Comment by adamunchained** [comment]
You received 100 SOON
