### ISSUE TITLE
Proposal don't show results correctly.

### ISSUE THREAD

**Issue by tccflash** [soonaverse/soonaverse-dao#912]
I created a new proposal with only two answers. After some people voted and the proposal is ended the % in the overview is not shown/calculated correct.

https://soonaverse.com/proposal/0x95c3a744d2e07f996c74e549052effa8f0349aec/overview

**Comment by adamunchained** [comment]
Seems correct to me. 

There was 15 votes.

12 votes for "Burn the unsold NFTs!" 20 %
3 votes for "Transfer the unsold NFTs to shimmer." 80 %

<img width="1363" alt="Screenshot 2022-11-14 at 9 12 20 PM" src="https://user-images.githubusercontent.com/130610/201831840-50d4d5b6-b7b7-42ee-9584-35061af31ba8.png">

**Comment by tccflash** [comment]
Okay. Than it only don't work on mobile devices. See the picture. ![image](https://user-images.githubusercontent.com/46502426/201835078-fadfa80c-22f2-4a7c-9374-761d35beb986.png)

**Comment by adamunchained** [comment]
ah! @humaint - can you please investigate?

**Comment by humaint** [comment]
@tccflash I can't replicate the issue. I'm using iphone / mac + safari, always same result as adam.

**Comment by tccflash** [comment]
Okay that's crazy. I can create a test proposal later, there we can take a look. Maybe it shows the same error? What do you think?

**Comment by humaint** [comment]
can you check different browsers / devices?

**Comment by tccflash** [comment]
I will check if I can find anyone who can test it.
