### ISSUE TITLE
Add QR Code for address within purchasing flow

### ISSUE THREAD

**Issue by adamunchained** [soonaverse/soonaverse-dao#914]
![image](https://user-images.githubusercontent.com/130610/195725086-ee62f098-f7f7-4d13-8f7d-d2232a1b13aa.jpeg)

**Comment by humaint** [comment]
https://www.figma.com/file/SfW2q5bOtoea2cb5IhQKiu/WebApp?node-id=2238%3A29407&t=xSCAn43JgUcaW6qi-1

design ready

**Comment by adamunchained** [comment]
@humaint - can you get the branch ready pls?

**Comment by humaint** [comment]
![SCR-20230117-ldh.png](https://images.zenhubusercontent.com/621c34bbe05cf522ccfe8330/66f0c0be-7583-4582-903b-a3801ea20f8d)

**Comment by adamunchained** [comment]
FYI: waiting for Firefly team to confirm how it needs to be generated.

**Comment by adamunchained** [comment]
parked until QR code supports deep links
