### ISSUE TITLE
NFT not showing up in profile

### ISSUE THREAD

**Issue by mikaa-ger** [soonaverse/soonaverse-dao#915]
**Describe the bug**
Many users reported us that their NFT is not showing up in the profile. 

Minted NFT: 
https://soonaverse.com/nft/0xfeb7d2b51b9a3285c7c2a9f7adcbba4103bc0ffe
Profile:
https://soonaverse.com/member/0x148ee6680e0f67d601ae718200703a8466bd7dee/nfts

NFT ist not there. It's doesn't matter which Browser. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by CptBananu** [comment]
Ownership of the NFT is correct, but metadata on tangle were not set properly:
https://thetangle.org/message/8c4e0ae91db962f887d31bf2461247bb7e5044efdd36f32f88aaeea296a35e2c

![image](https://user-images.githubusercontent.com/104099536/198852815-b71b13e3-ec9d-4444-bd39-342bdeed52bf.png)

**Comment by adamunchained** [comment]
@boldizsar-unchained - so there are two issues:
- approved flag on NFT wasn't delegated to the NFT from collection for some reason. This is why they didn't see it in their NFT list
- I'm not sure why owner/ownerEntity wasn't set on Tangle metadata
