### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by ATOI-IOTA** [soonaverse/soonaverse-dao#920]
### Discord Name

@ATOI#4134

### Soonaverse Profile Id

0xa8Cff718FC457045EBDCD0d24451feC5D69d8Cd0

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

Other (Please describe in comments)

### Wallet Version

2.0.1

### Comments

```shell
on 19.10. I claimed my 10.000 $FEE tokens on Soonaverse after setting up a Firefly Shimmer Wallet 2.0.1 and verification on Soonaverse. The tokens disappeared from Soonaverse and never appeared in my Firefly Shimmer Wallet. I double checked it was the correct Firefly Shimmer Wallet address which is verified on Soonaverse. Also I already succesfully got other tokens/coins on this address. 
Please assist in reclaiming these 10.000 $Fee. 
Best ATOI
```

**Comment by adamunchained** [comment]
we had some transaction processing delays. This should be now processed.
