### ISSUE TITLE
'Sort by price' does not work as expected

### ISSUE THREAD

**Issue by guhyeonjeong** [soonaverse/soonaverse-dao#925]
**Describe the bug**
When I search NFTs from 'sooonaverse.com/market/nfts', the 'sort by price' feature(low to high and high to low both) does not work as expected.

**To Reproduce**
1. Go to 'soonaverse.com/market/nfts/'
2. Search 'palm'
3. Sort by price: low to high (high to low does not work too)
3. Check 'On Sale' status
4. Result is incorrect

**Expected behavior**
Result should be sorted correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/3461814/197940469-8dc803e5-85c7-4873-8bb0-3262a709a7c1.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: macOS 13.0 / Firefox 106.0.1(64bit)

**Comment by humaint** [comment]
@adamunchained higher priority

**Comment by adamunchained** [comment]
@humaint - we no longer have that path but testing price ordering on collection it seems to work correctly there.
