### ISSUE TITLE
URL missing from transaction history

### ISSUE THREAD

**Issue by borninchb** [soonaverse/soonaverse-dao#927]
in the CSV file the URL to the web page where the transaction is displayed is missing.

In the profile under the item transactions and then execute "export csv".

In the CSV file, there is a URL to thetangle.org for each transaction under the tangle item. 
![grafik](https://user-images.githubusercontent.com/95142017/198579444-ed5f7cb3-8c10-497f-86b0-f6380f0d6e6e.png)

I am using Firefox on Linux Mint.
mint-0001 -1.0.

On Windows 10 also with Firefox I get same result.
Firefox 106.0.2

**Comment by adamunchained** [comment]
This has been added. It should in prod by EOD

**Comment by borninchb** [comment]
Now the URL are present but the tokenAmount and tokenId is missing.
![grafik](https://user-images.githubusercontent.com/95142017/199656559-15b2ffb0-0a7e-484f-99ba-a14e73b469dc.png)
