### ISSUE TITLE
[Payment Issue]: Claim locked FEE tokens 3times fail

### ISSUE THREAD

**Issue by poorviv** [soonaverse/soonaverse-dao#933]
### Discord Name

@WLTSAIJ#4980

### Soonaverse Profile Id

0x7EF281ef3C264D2F731faa397d67CC20C170d87d

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

2.0.0

### Payment Sent to Address

smr1qphusj0x2ypu6y3fltkfn8ftvl3r8l0zc9yw3d0lqw6grd3hgp2024vt4jx

### Amount Sent

0.0538

### Comments

```shell
Hi, I am try claim locked FEE tokens 3 times. But the system seems not work. (Soonaverse ID: WLNO1)
```

**Comment by adamunchained** [comment]
@boldizsar-unchained - see member transactions: https://soonaverse.com/member/0x7EF281ef3C264D2F731faa397d67CC20C170d87d/transactions 

It seems they’re unable to claim back locked funds

**Comment by adamunchained** [comment]
This has been fixed and refunded
