### ISSUE TITLE
Page with permission errors

### ISSUE THREAD

**Issue by csxiong** [soonaverse/soonaverse-dao#935]
**Describe the bug**
Check this url: https://soonaverse.com/token/0xbe507db0f565c4b7a145f32daaed6bd6655fda7c/airdrops
Even though I am not the issuer of this token, I was still able to download the airdrop template and perform the upload operation.

**To Reproduce**
1. go to 'https://soonaverse.com/tokens/all'
2. click 'RTO'
3. click 'token info'
4. click 'airdrops'

**Comment by adamunchained** [comment]
<img width="619" alt="Screenshot 2022-11-05 at 7 44 52 PM" src="https://user-images.githubusercontent.com/130610/200151530-020e40ce-cdc0-49e3-8ebd-a0ba6e4ee3fb.png">

Validation will kick in on the backend although I agree tab should not show. Will fix in upcoming release.

**Comment by adamunchained** [comment]
fixed in branch fix/ui_improvements
