### ISSUE TITLE
clicking the 'tokens' icon makes display disappeared

### ISSUE THREAD

**Issue by guhyeonjeong** [soonaverse/soonaverse-dao#937]
**Describe the bug**
In the '/tokens/all' page, if I click the 'tokens' icon in the left sidebar, then displayed tokens are disappeared.
it seems that the '/tokens' page is linked to the 'tokens' icon instead of '/tokens/all'

**To Reproduce**
1. Go to 'soonaverse.com'
2. redirected to 'soonaverse.com/tokens/all'
3. Click on 'the tokens button in the left sidebar'
4. directed to 'soonaverse.com/tokens', which is an empty display.

**Expected behavior**
a refreshed display of the listed tokens

**Screenshots**
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/3461814/200525507-676c1892-6342-4a05-9af5-cdeae8b21670.png">

**Desktop (please complete the following information):**
 - OS: macOS 13.0
 - Browser : Firefox, Safari

**Comment by adamunchained** [comment]
fixed in upcoming release
