### ISSUE TITLE
Migrate member search to use Algolia instead

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#943]
When a user's name doesn't appear on the list of members when trying to sell an NFT to a specific member, our workaround is to tell them to type in the Metemask id of the user instead and it will find their profile. This is not the case for this user. Entering this user's MetaMask id produces no results. 

https://soonaverse.com/member/0xf08247c99638a81a07f791b8543ef335577c90bd/activity
![image](https://user-images.githubusercontent.com/38050901/201974883-b1a9b9f0-6aa7-463c-9dfc-7865effe3b0f.png)

Note that using the Metamask id is a workaround to begin with.

**Comment by adamunchained** [comment]
We need to fix member search on all places (i.e. space, nft available, etc.)

**Comment by adamunchained** [comment]
This has been fixed in prod.
