### ISSUE TITLE
I cannot change the limit price(buy/sell) of tokens if the width of a browser is narrow

### ISSUE THREAD

**Issue by guhyeonjeong** [soonaverse/soonaverse-dao#944]
**Describe the bug**
The price per 1 token cannot be selected if the browser size is too small, although 'Amount to buy' is still able to be focused.
Because of this issue, some users could misunderstand that they cannot choose the limit price in this condition.

**To Reproduce**
1. Go to 'soonaverse.com/token/0x9600b5afbb84f15e0d4c0f90ea60b2b8d7bd0f1e/trade'
2. Resize the browser until the Buy/Sell frame does not get smaller anymore.
3. Try to change the 'set your price per 1 token' number.

**Expected behavior**
It has to be able to changed as the number of 'Amount to buy' can be.

**Screenshots**
![image](https://user-images.githubusercontent.com/3461814/202616484-95b4efdb-d08e-4e59-b3e5-55dbb9b8298d.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox 107.0(64-bit)

**Comment by adamunchained** [comment]
@humaint - any updates on this one?

**Comment by humaint** [comment]
fixed pointer events so the whole input now reacts better
