### ISSUE TITLE
Collection stuck in migration

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#946]
Thr following collection has been in the process of minting and has been stuck on the final 23 NFTs to be minted for over 24 hours at the time of this ticket. Will delete this if the collection spontaneously mints.

https://soonaverse.com/collection/0xfaf71b314f1e3c60a11cdec1b723e4404cd5cade

**Comment by adamunchained** [comment]
@boldizsar-unchained - can you check pls?
