### ISSUE TITLE
User has impossible 'joined' date.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#948]
A user can have thier 'joined' date listed inaccurately. Cause currently unknown, will update if more details arise.

Below is an example of a user with activity dated a date incompatible with the 'joined' date

![Bildschirmfoto_2022-11-29_um_15 39 45](https://user-images.githubusercontent.com/38050901/204593053-169406e0-7fa2-41c1-821c-6f126f1eb03f.png)

![Bildschirmfoto_2022-11-29_um_15 39 22](https://user-images.githubusercontent.com/38050901/204593488-093c4ab6-20ac-4229-a785-1cacb6c3171b.png)

**Comment by adamunchained** [comment]
This has been corrected in prod.
