### ISSUE TITLE
Claiming Token gets invalid amount but still processes

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#949]
**Describe the bug**
This was encountered on the wen2 environment

1) Airdropped token to claim
![image](https://user-images.githubusercontent.com/44786846/204875167-18c484f5-dabc-4507-9653-d13ec51c63dd.png)

2) Signed and received address to send MI to
3) sent correct amount of MI
4) system said incorrect amount and started refund
5) System then said transaction confirmed
6) system then showed invalid amount page
![image](https://user-images.githubusercontent.com/44786846/204875109-436dd83c-dd72-4fd5-8c0b-9545726f33cd.png)

7) Tokens show as claimed correctly in the system afterwards
![image](https://user-images.githubusercontent.com/44786846/204875198-2b659eb4-7f50-405d-98ff-9b2c3a4da4fe.png)

**Comment by adamunchained** [comment]
I believe this has been fixed. If you still have this issue, please re-open the issue.
