### ISSUE TITLE
VIP Level for staking is not correct

### ISSUE THREAD

**Issue by Chris2031** [soonaverse/soonaverse-dao#952]
**Describe the bug**
I have staked some SOON token today and the summary screen, before you do the final transcation confirmation, has shown me "You will earn - VIP Level 2" but after staking I have got VIP Level 1 assigned.

**To Reproduce**
1. Stake Soontoken and check transaction summary before commit.
![Staking_Level_2](https://user-images.githubusercontent.com/101657592/205074676-d753fb5e-3258-4671-b765-a3bc4235221c.JPG)

3. Check VIP Level in Profile after successful staking
![Profile - My_Staking_Level_1](https://user-images.githubusercontent.com/101657592/205074870-999a19e4-34e7-41d0-a43a-09931109be46.JPG)

**Comment by adamunchained** [comment]
What's your member ID?

**Comment by Chris2031** [comment]
Do you mean this?
0x11bbeb386504b9cd124f4287b1feb91ad221e79f

**Comment by humaint** [comment]
is this still valid? 

@adamunchained I can't check what LEVEL does it show to member, as it visible only to him 0x11bbeb386504b9cd124f4287b1feb91ad221e79f.

But it works fine with my account, or all testing accounts.

**Comment by adamunchained** [comment]
I can't replicate this either. Let's close this. 

@Chris2031 - if it's still an issue feel free to re-open.

**Comment by Chris2031** [comment]
Hello Adam,

I have just checked and it looks like someone removed the "You will earn" information from the "Stake your token" overview.
Therfore I`m not able to replicate this issue anymore.
