### ISSUE TITLE
Staking amounts for SOON being displayed in areas meant for amounts of other tokens.

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#954]
In this example, a user has staked both SDDT and SOON, but the value of staked soon is showing up where SDDT should be.

![image](https://user-images.githubusercontent.com/38050901/205401411-a140985a-da97-45aa-a59f-c6c8e76a20a5.png)
^the user's staking for SDDT (pay attention to the amount)

![image-1](https://user-images.githubusercontent.com/38050901/205401455-0691349e-fe81-44fd-8532-25d5a0bacaa0.png)
^

Is the same as their staked SOON total (both rows added. I am assuming that the sddt amount staked is a very similar number (just times 1000) because they were both staked on the same day.

**Comment by adamunchained** [comment]
This was fixed and it'll be released by end of today.

**Comment by adamunchained** [comment]
We were always getting value for SOON token instead of space's token.
