### ISSUE TITLE
Staked Tokens page links users to a blank overview page instead of to the token

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#956]
In the Staked Tokens page of a user's profile, clicking one of the staked tokens links users to a blank overview page instead of to the token

Example of a blank overview
https://soonaverse.com/token/0x323d6666ae07bf05dfeff4ed26febef6781f361c/overview

**Comment by adamunchained** [comment]
Fixed and it'll be released by EOD
