### ISSUE TITLE
Soonaverse soon token staking error

### ISSUE THREAD

**Issue by picco1999** [soonaverse/soonaverse-dao#959]
![KakaoTalk_20221202_165220989](https://user-images.githubusercontent.com/119843791/205585859-5471369e-0a9e-4fd2-8e92-d506b1ab3782.png)

![KakaoTalk_20221202_163753506](https://user-images.githubusercontent.com/119843791/205585873-aee8b3d5-eb5e-45b6-91ef-a15306d50408.jpg)
![KakaoTalk_20221202_163755402](https://user-images.githubusercontent.com/119843791/205585876-318ebfd5-1d43-4830-afa6-b608bcfa5426.jpg)

I staked the 12624.51 soon token on Soonaverse through my smr Firefly on December 2nd.
The payment was made normally, and I received a lockout token of 12624.51 soon on my Shimmer Firefly for 365 days.

However, the staking history is not displayed in Soonaverse. Please let me know if I can get an airdrop for staking normally. my smr address “smr1qpvxy98p6zg0ywf9qz77zlkq70unlytqeljxuejx0esnu79pwaltwpk0mjv”. I would like to ask you to check and see the status of Soonaverse staking normally.

**Comment by picco1999** [comment]
![12345](https://user-images.githubusercontent.com/119843791/205587043-cbddc2f2-3deb-493f-970f-765c7f8e9db1.jpg)


My ID

**Comment by adamunchained** [comment]
@boldizsar-unchained - could you check this please?

**Comment by picco1999** [comment]
@boldizsar-unchained 

I will provide the transaction reference that you request.The 12624.51 soon token is currently locked.
The Soon token balance on Smr Firefly is zero.
And for the locked soon token, it is not confirmed in the soonavers transaction 
 
![1](https://user-images.githubusercontent.com/119843791/205888896-2d49ba3a-85b9-4df3-897c-ef89f5922451.png)
![2](https://user-images.githubusercontent.com/119843791/205888921-e6f75d71-ec06-4f08-af50-1ae7f791874c.png)
![3](https://user-images.githubusercontent.com/119843791/205888950-9eacbabe-c103-4c98-8cd1-99b5e7d74387.png)


soon token staking transaction Block ID: "0x6303c4167d6805a4559506bc577d1d8258008786dda47a8842f61ca3cbb5f036
soon token locked transaction block ID: "0xa784b54d9982619dce50631cf3df38d502f256a0723eb8c5c5b564acfdce00a9

Attached is a picture of a momentary capture of Shimmer Explorer.
I ask you to check and reflect i

**Comment by boldizsar-unchained** [comment]
@picco1999 I managed to find the stake in our system but it seems that it was initiated by a different user
(https://soonaverse.com/member/0x443224166e86e5a93bf44157163972868744307f/tokens) and not picco1999.

**Comment by picco1999** [comment]
@boldizsar-unchained
There is no possibility that I used another account. However, I connect to the same account on my desktop and laptop. The pure token claim was accessed from the desktop, and the pure token staking was accessed and paid with a laptop. Two are the same account.
The smr wallet is managed by a personal laptop, and Soonaverse is accessed from the desktop. Both access records are the same account.

Please apply soon token staking to my account (@picco1999). Thank you.

**Comment by adamunchained** [comment]
@picco1999 - you might have generated a new wallet in your MetaMask. It's very easy. When you did the stake you have actually used the other account to sign and stake. I would check your metamask.

**Comment by adamunchained** [comment]
Note, you could have a situation where your metamask preferred account is different to the one you're currently connected with on the portal. This means when you sign requests, you sign them with your "metamask account" not the one that shows on Soonaverse.

**Comment by picco1999** [comment]
@boldizsar-unchained

You're right.
At first, I used my laptop to access Soonaverse.
Since then, I have restored the meta-mask to my desktop at work and have been using two devices.
I thought it was the same account because both desktop and laptop were logged in with the same ID.

1. Is it a problem to restore the meta mask and access it with the same ID through two different devices?

2. If I restore the meta mask to another device, will the recently restored account be recognized as true?

3. I installed and used a meta mask on my laptop first. After that, the meta-mask was restored to the desktop and used.
Soon token claim was possible only on the desktop.
There was an error in the normal Soon token staking on the laptop.
So my laptop meta mask is not true?



If you let me know the exact part of the error, I will share the information with our Korean community, which has a large stake in Soonavers.

Thank you.

**Comment by picco1999** [comment]
@boldizsar-unchained
**The urgent matter is that I want to receive the compensation for the steak that is scheduled to be paid on the 8th.
Can you reflect the staking status of the soon token in my soonavers account?**

**Comment by adamunchained** [comment]
There is nothing for us to do. Since you have linked it to the account: 0x443224166e86e5a93bf44157163972868744307f you will receive your reward there. You can claim it there and those SOON will come back to your Firefly wallet. 

You just have to manage your two metamask addresses.

**Comment by picco1999** [comment]
@boldizsar-unchained

I can't see the staking status for both accounts. 
Are you saying that there will be a reward even if there is no current status of the steak?
I don't see the status of the staking in both accounts. Please connect to my account (@picco1999) so that I can see the status of the staking and claim compensation.
"0x443224166e86e5a93bf44157163972868744307f" There is no other way to check the status of the staking than to press this address directly into it. I beg you.

![스테이킹화면1](https://user-images.githubusercontent.com/119843791/206090771-4053265a-161c-43ef-94ae-ada9e56e2c1e.jpg)
![스테이킹2](https://user-images.githubusercontent.com/119843791/206090777-8ad6ad25-1098-447f-92c2-8d3ec6a76285.jpg)
![스테이킹3](https://user-images.githubusercontent.com/119843791/206090792-da618af2-fcf9-4cfe-99e7-8c49bc5a5c35.jpg)
![스테이킹4](https://user-images.githubusercontent.com/119843791/206090802-739238f5-a1b3-44a0-8a26-ec83c1771b6a.jpg)

**Comment by adamunchained** [comment]
You have signed with Metamask 0x443224166e86e5a93bf44157163972868744307f - You just have to login into Soonaverse with that Metamask and you'll see your staked amount and stakes. That's where you will be claiming your rewards. Its not linked to your @picco1999 account as mentioned above. I'm not able merge two different metamask wallets.

<img width="1331" alt="Screenshot 2022-12-06 at 8 57 12 PM" src="https://user-images.githubusercontent.com/130610/206092454-77fca700-90b0-43d7-82d3-628303ed0438.png">

We can't link it to your other account.

**Comment by adamunchained** [comment]
If you need further support on this please reach out to the support team on discord.

**Comment by picco1999** [comment]
@boldizsar-unchained

Please wait for a moment.

I will show you the video and ID of the laptop.

**Comment by picco1999** [comment]
@boldizsar-unchained

The picture you showed me doesn't have a shimmer address or verification history at all, look at the picture.
The soon token is somewhere else.
![스테이크 사진3333](https://user-images.githubusercontent.com/119843791/206094292-b5080767-48b9-4151-b60e-40fa1a08330d.jpg)

**Comment by picco1999** [comment]
@boldizsar-unchained
Please check the video. Staking has been carried out with this device

https://user-images.githubusercontent.com/119843791/206099518-b3415365-64e6-49af-b672-f01ddb253707.mp4

**Comment by picco1999** [comment]
@boldizsar-unchained
Thank you. Thanks to you, I found a pure token steak.
As a result of carefully examining the account address you mentioned,

I have confirmed that url changes from the account I accessed to another account by clicking Favorites in Explorer or clicking My Profile. 

Thank you again for giving me a hint to find SOON token.
