### ISSUE TITLE
Video not loading on some browsers

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#963]
Unsure if this is related to the other issue about the home page videos.

Some browser setups are not loading the .mp4 file format videos for this collection <https://soonaverse.com/collection/0xcd8f364bf020613a1c8a1181ac94ddab425bc6f2>

It is not clear at this time if this is the only collection affected by this. A user did some investigation and determined:

Play video not possible:
Android / Chrome
Android / Opera
Chromebook / Chrome
Windows 10 / Chrome

Play video possible:
Apple / Safari
Apple / Chrome

This is an NFT from the collection in question <https://soonaverse.com/nft/0x5843d3b13a613fa333eeb4144d9c8bca8a4229f6>
![image](https://user-images.githubusercontent.com/38050901/206005506-95aaeaed-cf04-491f-9703-cb81e87e074d.png)

**Comment by adamunchained** [comment]
This collection has been fixed. Let me know if there is any other one.
