### ISSUE TITLE
[Payment Issue]: 

### ISSUE THREAD

**Issue by Konjunktiv** [soonaverse/soonaverse-dao#964]
### Discord Name

Konjunktiv#7491

### Soonaverse Profile Id

0x21ebfac09cd474ecbaa28deaf948610fd22e6bc0

### Payment Action

Other (Please describe in comments)

### Payment Problem

Other (Please describe in comments)

### Wallet Type

FireFly

### Wallet Version

2.0.1

### Payment Sent to Address

smr1qpyfsq4chjeyxfurmcjp99kmcp9xw2jnznsyvr7z6xqs03yuthh25nq8etu

### Amount Sent

4200 soon

### Payment Message Id

0xff56c0ee893d07088670de36b23b87f972d63b1ccda2b198909ec54dc1ab8103

### Comments

```shell
Hallo, am 02.12.22, 07:03  hatte ich versucht meine Soon Token zu staken. Leider ist dabei etwas schief gelaufen. Nun liegen meine Token bei euch und ich habe keinen Zugriff mehr darauf. Ich bitte euch mir meine Soon Token zurück zu senden. Mein Account auf soonaverse: 0x21ebfac09cd474ecbaa28deaf948610fd22e6bc0 Adresse von der ich gesendet habe: smr1qqmjmwvkqtk0a86cj39ddaf879ag3p999ncqqlxj0pat7hn989k2x9tlntx  Adresse an die ich gesendet habe: smr1qpyfsq4chjeyxfurmcjp99kmcp9xw2jnznsyvr7z6xqs03yuthh25nq8etu  Viele Grüße Konjunktiv
```

**Comment by Konjunktiv** [comment]
Hello, on 02.12.22, 07:03 I had tried to stak my Soon Token. Unfortunately something went wrong. Now my tokens are with you and I have no access to them. I ask you to send me back my Soon Token. My account on soonaverse: 0x21ebfac09cd474ecbaa28deaf948610fd22e6bc0 Address from which I sent: smr1qqmjmwvkqtk0a86cj39ddaf879ag3p999ncqqlxj0pat7hn989k2x9tlntx Address I sent to: smr1qpyfsq4chjeyxfurmcjp99kmcp9xw2jnznsyvr7z6xqs03yuthh25nq8etu Many greetings conjunct.

Translated with www.DeepL.com/Translator (free version)

**Comment by adamunchained** [comment]
Hi @Konjunktiv 

There was an issue where invalid payments with expiration unlock got stuck. This issue has now been resolved but your payment wasn't reprocessed. You should now have your SOON in your wallet: smr1qqmjmwvkqtk0a86cj39ddaf879ag3p999ncqqlxj0pat7hn989k2x9tlntx
