### ISSUE TITLE
Language mixing on the site

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#972]
Language settings will sometimes become incorrectly set and change from one language to another. Here is an example of a user with both german and english UI.

![Screenshot_2022-12-09_at_16-47-02_Discover_-_Spaces_Soonaverse](https://user-images.githubusercontent.com/38050901/206755130-9a8a41ca-fc65-429e-985e-7d133c717739.png)
![no](https://user-images.githubusercontent.com/38050901/206755210-481ddb11-9973-45d6-9e3e-9bd1e8e9ef80.png)

I know this kind of language issue has been put in github before, but there is no current issue for it that I can see. Apologies if dupe.

**Comment by adamunchained** [comment]
@SeanTMartin - I'm aware of this issue but tbh we don't know how to fix it. It's cause by Cloudflare and how content is cached.

**Comment by ivanbeerlama** [comment]
Maybe let the user have the ability to select their default language on their profile page? In the same section where you can update your profile name, info and mint your avatar?

**Comment by adamunchained** [comment]
We have that ability. The issue is due cloudflare not serving right cached content based on pre-set cookie that stores the language preference. It’s vendor issue, we’re following up with them to get more info on this.

**Comment by adamunchained** [comment]
This has been believe for the next release. Language selectors works again.

We still might have languages that are not fully translated and those will of course have mixture of languages.
