### ISSUE TITLE
NFT migration to Shimmer got stuck (after december update)

### ISSUE THREAD

**Issue by CptBananu** [soonaverse/soonaverse-dao#975]
**Describe the bug**
_Disclaimer:
This seems to be the same bug as reported in #973 but we have more details for this one here._

User from discord-ticket #bugissue-74 initially created their collection (https://soonaverse.com/space/0x01bd67e2135b77fa242ac42d54622e51e7aebdab/collections) on dec. 5th/6th and started migration to Shimmer shortly after.

The collection only consists of 10 NFTs but still says "Minting in progress" after many days.
Data of the NFT pictures: 3072 x 2304 px, 240dpi (so nothing crazy). Total size of all 10 pictures is 23 MB.

I remember the december patch notes saying that there were changes in IPFS structure so maybe that's the root of this problem.

Finally here a pretty silly idea that came to my mind:
User is in Thailand atm so they uploaded the NFTs there (which obviously worked). But could it be that the IPFS servers (or the entry point to IPFS) there suck so hard, that this could be the cause of this unususal long minting time? 

**Related transactions**
Address where the migration fee was sent to:
https://explorer.shimmer.network/shimmer/addr/smr1qzkdudd04elpjz29fga394qedaddejsmjw2ksens4w4jn9twueaj5e6qq98

TX details in Firefly (block):
https://explorer.shimmer.network/shimmer/block/0x6628c490807a46f4a0571d05c8f19b68a588cb6fe2dbcfefdb137ef1ee052f20

Transaction itself:
https://explorer.shimmer.network/shimmer/transaction/0x6628c490807a46f4a0571d05c8f19b68a588cb6fe2dbcfefdb137ef1ee052f20

Thanks in advance

**Comment by adamunchained** [comment]
You are right, there was an issue with minting process that was fixed but we didn't restart collection that were in progress.

This collection has now been minted.
