### ISSUE TITLE
ERROR STAKING SOON

### ISSUE THREAD

**Issue by Jokinfs** [soonaverse/soonaverse-dao#979]
### Discord Name

@jokin#5169

### Soonaverse Profile Id

@jokin

### Payment Action

Staked Token

### Payment Problem

I staked a token and do not see it in my wallet

### Wallet Type

FireFly

### Wallet Version

2.0.1

### Payment Sent to Address

snr 1qquc9hpwwpc3ve9lőwrul2lrnez eceduclnsh7gdrt4c5jr75r4pwzjntrt

### Amount Sent

715,84

**Comment by adamunchained** [comment]
<img width="1518" alt="Screenshot 2022-12-13 at 2 59 56 PM" src="https://user-images.githubusercontent.com/130610/207463589-b06413d6-b109-4fe8-8d76-d94b31ed022e.png">

It went back to you (smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5) and it's time-locked, see transaction on shimmer: https://explorer.shimmer.network/shimmer/block/0x1c4a58f9bf255e4d9f01bea43e1370b361603adcd39dbaef783513b2ffd6890d

Feel free to re-open the issue if I've missed something.

**Comment by Jokinfs** [comment]
Hello Adam,

In my ticket #979 said to me this screenshot.

And it is my transacctión.

https://explorer.shimmer.network/shimmer/block/0x1c4a58f9bf255e4d9f01bea43e1370b361603adcd39dbaef783513b2ffd6890d

I dont have my Soon in my wallet from tanglepay or firefly.

Thanks.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adamunchained** [comment]
Is smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5 your wallet?

**Comment by Jokinfs** [comment]
Hello Adam,

Yes, it is my wallet from Tanglepay smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5

But i remember that Tanglepay not funcioned when i did staking Soon. I used Firefly and my wallet is  smr1qrx98knll7638775rfqcee9xdkftf7kkur5kpjkwzs2g8zflnrjn2egjx0d

In Tanglepay i have this:

[cid:03cd7978-f641-4614-bc76-ac464ff35c81][cid:cb4f0667-5025-4b26-9d9e-36f6de56a45c][cid:ebf5bdea-fbc6-42e8-bfe4-e923232fa796]


________________________________
De: Adam ***@***.***>
Enviado: miércoles, 14 de diciembre de 2022 09:49 p. m.
Para: soonaverse/soonaverse-dao ***@***.***>
CC: Jokinfs ***@***.***>; Author ***@***.***>
Asunto: Re: [soonaverse/soonaverse-dao] ERROR STAKING SOON (Issue #979)


Is smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5 your wallet?

**Comment by Jokinfs** [comment]
Hello,

You closed #979 and i have not received anything.

Thanks.

**Comment by adamunchained** [comment]
If you look at this transaction on Shimmer you can funds were send to your address smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5

https://explorer.shimmer.network/shimmer/block/0x1c4a58f9bf255e4d9f01bea43e1370b361603adcd39dbaef783513b2ffd6890d

You might need to just refresh your balances in wallet. Check with Firefly/TanglePay teams.

**Comment by Jokinfs** [comment]
Hello Adam,

It is my transactions in wallet  smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5.

[txhistory-smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5 (1).zip](https://github.com/soonaverse/soonaverse-dao/files/10251316/txhistory-smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5.1.zip)

And in:
https://explorer.shimmer.network/shimmer/block/0x1c4a58f9bf255e4d9f01bea43e1370b361603adcd39dbaef783513b2ffd6890d

"quantity": 0,

Im sorry but i dont understand this...

**Comment by Jokinfs** [comment]
Im waiting...

thanks.

**Comment by adamunchained** [comment]
As mentioned above, I can see your funds are in your address. I think there might be an issue with wallet you're using, make sure you reach out to the community. This does not seems to be an issue with Soonaverse hence it should not be discussed here.

**Comment by Jokinfs** [comment]
Hello Adam,

Yes, i can see my Soon now.

Thank you!!!
