### ISSUE TITLE
Error staking soon

### ISSUE THREAD

**Issue by Jokinfs** [soonaverse/soonaverse-dao#980]
### Discord Name

@jokin#5169

### Soonaverse Profile Id

@jokin

### Payment Action

Staked Token

### Payment Problem

I staked a token and do not see it in my wallet

### Wallet Type

FireFly

### Wallet Version

2.0.1

### Payment Sent to Address

snr1gqmnz97camgke437dsum@ gccg2d qllpsf2ltyvg7exa 83w8ldeeryfu9yr9

### Amount Sent

10

**Comment by adamunchained** [comment]
Can you provide which transaction on Shimmer are you talking about? 

Payment address also seems to be invalid SMR address.

**Comment by Jokinfs** [comment]
Im sorry.


My 10 Soon were sent to:

smr1qqmnz97camqk0437dsum0qccg2dqllp5f2ltyvq70x383w8ld00ryfu9yr9
smr1qqmnz97camqk0437dsum0qccg2dqllp5f2ltyvq70x383w8ld00ryfu9yr9
________________________________
De: Adam ***@***.***>
Enviado: martes, 13 de diciembre de 2022 11:03 p. m.
Para: soonaverse/soonaverse-dao ***@***.***>
CC: Jokinfs ***@***.***>; Author ***@***.***>
Asunto: Re: [soonaverse/soonaverse-dao] Error staking soon (Issue #980)


Can you provide which transaction on Shimmer are you talking about?

Payment address also seems to be invalid SMR address.

**Comment by adamunchained** [comment]
sry for delayed response. You can see here it was sent back to you: https://explorer.shimmer.network/shimmer/block/0x7300709b6d1a852a91dcdd5bde5af8780bc24bfef73786e8b04f7a59f54ba7e8

smr1qpjhe7sz4me4yxfczm4gf2wey4tau63r6zctet97y5fwpk0mcf66wehgfm5 address seems to be yours.
