### ISSUE TITLE
[Soonaverse-lib] integer fieldValues not working

### ISSUE THREAD

**Issue by ivanbeerlama** [soonaverse/soonaverse-dao#986]
The fieldValue filter in the getMany api call does not seem to work for numbers, like price etc. Only for strings. For example: 

https://soonaverse.com/api/getMany?collection=nft&fieldName=available&fieldValue=1

Available is stored as an integer, and should return a list of NFTs where available=1. Instead it returns an empty list. It does work for strings. For example: 

https://soonaverse.com/api/getMany?collection=nft&fieldName=space&fieldValue=0x63830b88835955ac53d82692a53cf3efee6cd37f

Both direct api calls and calls by the NftRepository in soonaverse-lib are affected

**Comment by ivanbeerlama** [comment]
The updatedAter filter also seems to be broken:

The following call returns a list with elements where the _updatedOn_ field is earlier than the _updatedAfter_ ISO data:

https://soonaverse.com/api/getUpdatedAfter?collection=nft&updatedAfter=1672300625

**Comment by adamunchained** [comment]
You have to provide timestamp in microseconds. So https://soonaverse.com/api/getUpdatedAfter?collection=nft&updatedAfter=1672300625000
