### ISSUE TITLE
Funds arriving after/at address window expiration time locked

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#987]
User sent funds trying to stake that arrived at the very end of or after the payment window expired, but were still sent with an expiration condition.

Funds remain locked but with no staking rewards visible. Funds were not sent back and no transaction appears on the profile.

Profile : https://soonaverse.com/member/0xE761bCbA825B1F6B3bA520882A2F1DcDc3936D99

(Does not show up in transactions)

Tx: https://explorer.shimmer.network/shimmer/transaction/0x97b1211268f9ec3deb6f74991f492fc6faa3cf34881ba0132790d6d0c5074b07

(From screenshot)

**Comment by SeanTMartin** [comment]
Here is the address funds were sent to. smr1qpm87q3dnp67xfum4x605v34mwuat8kkd4kpt0ka9pnellyjgx3cg8sal7e

https://media.discordapp.net/attachments/1053805819537412206/1053806276594896966/20221209_101408.jpg

**Comment by adamunchained** [comment]
User has signed it with this Metamask ID: 0x133cabc4f93940e8aa43495918f8ec7bbef887f6 not with 0xE761bCbA825B1F6B3bA520882A2F1DcDc3936D99 as mentioned above.

See the transaction here:
https://soonaverse.com/member/0x133cabc4f93940e8aa43495918f8ec7bbef887f6/transactions

You can also see the credit for the refunded tokens. There was an issue with refunds in the past (this was now fixed) but it causes this credit to stuck. I've fixed it and they should get their refund on their sender's address.

See: https://explorer.shimmer.network/shimmer/block/0xb4cd2da646210819b79f3f6b4a3a91bb1c7a814aca8e560635567640b4a37203
