### ISSUE TITLE
Text is not readable in DARK MODE "Staking_Table"

### ISSUE THREAD

**Issue by issaus2020** [soonaverse/soonaverse-dao#991]
**Describe the bug**
The text is not readable in dark mode!

**To Reproduce**
1. Go to 'Staking'
2. Scroll down and see the table under "Current level"

**Expected behavior**

**Screenshots**

![Bildschirmfoto 2022-12-20 um 21 17 37](https://user-images.githubusercontent.com/115226074/208758592-45db80e7-28ab-4b3b-8188-1b1c6f9d292f.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome,]

**Comment by Phyloiota** [comment]
This is basically in all white-background fields in Dark mode. See here:
![image](https://user-images.githubusercontent.com/77154511/209453553-baf90019-be03-4147-a85e-72a3445b2a87.png)

**Comment by humaint** [comment]
@Phyloiota thanks! I've fixed this, will be released with a next update.
