### ISSUE TITLE
Staking not sent back

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#992]
User staked for 2 weeks, but did not get staking funds sent back upon completion of the staking period.

Payment: https://explorer.shimmer.network/shimmer/transaction/0x4c96e93c782ea1651f85724383f7cbbdcda1c903ed46ac389ac79cf3a32df469

Bill payment: https://explorer.shimmer.network/shimmer/transaction/0x1f5c041eb3272a90e22c7263125f3f495fabcae595151f906336691ebdd57ba4

Profile: https://soonaverse.com/member/0x6a202f991c4c1df079449be9847b1dac3f51854f/

**Comment by adamunchained** [comment]
Locked funds were sent back to smr1qzm73cehz37467zuhjxkxcdz3cd68fk3ukxlc4uj8rc9tkzcjzkeu7mehyn . It seems to be their validated address on Member too.

You can see the transaction here: https://explorer.shimmer.network/shimmer/transaction/0x1f5c041eb3272a90e22c7263125f3f495fabcae595151f906336691ebdd57ba4

Am I missing something here? If so feel free to re-open.

**Comment by Alemty** [comment]
> 

Could you help me by checking if the funds were moved to another account? Since tanglepay does not reflect that movement to me. And if you tell me that it is correct I will have to verify it directly with tanglepay,

**Comment by Alemty** [comment]
Could you help me by checking if the funds were moved to another account? Since tanglepay does not reflect that movement to me. And if you tell me that it is correct I will have to verify it directly with tanglepay.
On the soonaverse platform they appear to me as if they are still blocked, but it has already expired.

**Comment by Alemty** [comment]
![image](https://user-images.githubusercontent.com/99059511/208812357-0af4b445-0904-4bb6-a8cd-29cdea91eab6.png)
This is the only transaction that appears to me in TP the day the stake ended.
In the hash it indicates that the date was 12-1-2022, but the stake ended on 12-15-2022 and that does not appear.

**Comment by Alemty** [comment]
![image](https://user-images.githubusercontent.com/99059511/208812667-0b4c3414-7343-446d-9b57-14237dca0a24.png)

I don't see the stake that has returned on the soonaverse platform either, only the rewards as you can see on 12-16-2022. Remember that it is the day 12-15-2022.
If you require any specific information, I can gladly help you to verify this inconvenience

**Comment by Alemty** [comment]
![image](https://user-images.githubusercontent.com/99059511/208813110-8ec13811-4d06-42e1-840a-265b63659d04.png)
And the day I made the stake for 2 weeks, I made a lot of movements, that's why maybe the hash is incorrect, but tell me which one I can share to help me recover those tokens.

**Comment by adamunchained** [comment]
I'm lost. You asked to verify above transactions and I can see above transaction went back to you by looking at Shimmer Explorer. There does no seems to be bug in soonaverse. Maybe reach out to our support channel for further help.

**Comment by Alemty** [comment]
On 01-12-2022 I did a stake of soon for 2 weeks until 15-12-2022. He gave me the rewards but he did not return the 1000 soon staked, there is no trace of the transaction of the 1000 soon returned on 15-12-2022 neither in Soonaverse nor in TanglePay. Who can I contact to find a solution?. Because the hash that you say returned the soon to me is marked on 01-12-2022 and not on 15-12-2022 and that is a clear error, they stayed in Limbo.

**Comment by Alemty** [comment]
Thanks for your attention, verifying tanglepay today, automatically already shows me reflected the 1000 soon that I had stakeado, it was probably a mistake of soonaverse or tanglepay because yesterday I raised this tiket did not show them. Thanks

**Comment by Alemty** [comment]
Thanks for your attention, verifying tanglepay today, automatically already shows me reflected the 1000 soon that I had stake, it was probably a mistake of soonaverse or tanglepay because yesterday I raised this tiket did not show them. Thanks
