### ISSUE TITLE
Profile Transaction History Loops on mobile

### ISSUE THREAD

**Issue by centercirclesolutions** [soonaverse/soonaverse-dao#994]
**Describe the bug**
Transaction history on mobile seems to loop back to the beginning after one page

Follow this link: https://soonaverse.com/member/0x16b59bc84626437251d17799167d033d3f885e0f/transactions
on mobile (i did it on android pixel 7) scroll down on transactions. after Mar 2022 it goes back to Dec 2022

**Comment by humaint** [comment]
@centercirclesolutions can you pls review this as it seems okay now
