### ISSUE TITLE
NFT "Collections" overview does not appear sorted by "community vote"

### ISSUE THREAD

**Issue by Phyloiota** [soonaverse/soonaverse-dao#996]
**Describe the bug**
When you enter the NFT collections overview the site does not show you the collections sorted by community ranking. It shows a (random?) sorting. This happens when you visit it for the first time. Once you refresh the page or go to another soonaverse page and back to Marketplace, the sorting works.

Happens on Firefox and Chrome

See the videos attached:

https://user-images.githubusercontent.com/77154511/209453935-7c332d5f-b066-43df-977e-14c9227f51ef.mp4

https://user-images.githubusercontent.com/77154511/209453869-ffcffcef-360d-4a45-9f42-f4d10dd8844c.mp4

**To Reproduce**
1. Go to 'https://soonaverse.com/market/collections'

**Expected behavior**
Collections should appear ranked by community rank
![image](https://user-images.githubusercontent.com/77154511/209453748-893715c6-0cd8-4699-a384-ed94bb963109.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Win 11]
 - Browser [Firefox]
 - Version [latest]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adamunchained** [comment]
I was not able to replicate this in upcoming release so I'm assuming this is now working well. I've tried numerous things. 

Please if you experience this issue again let us know.

@humaint - just to be sure, can you re-test?
