### ISSUE TITLE
Image of NFT not displaying properly

### ISSUE THREAD

**Issue by SeanTMartin** [soonaverse/soonaverse-dao#997]
NFT image on the Soonaverse is blank for this NFT both in it's NFT page and when viewing the preview thumbnail. The image looks like it is being treated like a video for some reason. The image loads normally if you go to its 'video address' which ends in .jpeg. https://images.soonaverse.com/0x614730e13933fb20bfb91825a03511acfeacf274/lmp4jk9lk4r/nft_media.jpeg

![image](https://user-images.githubusercontent.com/38050901/209900333-bbb6205e-cc1c-4a5e-9ca4-ceb1a4bc850a.png)

![image](https://user-images.githubusercontent.com/38050901/209900361-4595c4b1-f14d-4115-8f99-85d14f8b8286.png)

**Comment by adamunchained** [comment]
fixed in upcoming release
