### ISSUE TITLE
Error airdrop 

### ISSUE THREAD

**Issue by priceactionbars** [soonaverse/soonaverse-dao#998]
We already airdropped to our NFT holders , but when we also tried to airdrop to all our community members, it gave us an error.
1. We exported our members 1348 members  from our page group: https://soonaverse.com/space/0x3435cfba9481541ec722256049d7c3f8a84ae8ce/overview
2. We downloaded our CSV-templated and put all our eth-adresses (1348 members) in the eth adresse section.
3. We put all data  as well beside staking section (look to the file we added)
4. we uploaded the CSV file: https://soonaverse.com/token/0x10ba907cc33418555dd1203ede5fd2c26fef4c68/airdrops
5. when we upload it , it says all ethadresses are invalid(in dutch). for example i copied  some of these data that says it's invalid, but it's all from the CSV file: 0xe3f284ae21b2574a22c4aaf65844711151e51889 rij is ongeldig (means invalid)
[soonaverse_airdrop_template (11).csv](https://github.com/soonaverse/soonaverse-dao/files/10328981/soonaverse_airdrop_template.11.csv)
[soonaverse_airdrop_template (11).csv](https://github.com/soonaverse/soonaverse-dao/files/10328988/soonaverse_airdrop_template.11.csv)

0x946e86495bc2f2e9e963f16e7c480bd1527ff5fd rij is ongeldig
0x4a1c773689688cebfe4f14061aaaba5e388adb23 rij is ongeldig
0x137b9e4361c8ff02e6e1552b635f0824c9d9ce34 rij is ongeldig
0xc11cc6d8043e8f1405ba133df4df9c86475f49e4 rij is ongeldig
0x232fe7709c5ada85ac73a2a199b580d6101f917d rij is ongeldig
0x773133d88e36a8bcd456ef3943339ca25230118d rij is ongeldig
0xed4fa8d56426014be44864eeb7d396c6606c41b7 rij is ongeldig
0xb7d9028f474fad20e12d9de75057f48ac15b9836 rij is ongeldig
0x56b54608ad146bd0562f925c6e34d21ff72ca944 rij is ongeldig
0xf29cd2830d0df87c9d12e7f97a9b60d6eba5ea72 rij is ongeldig
0xc367df142221aada116c2f3061a8d20479b4e25c rij is ongeldig
0xa735de13bdef6c21acee0b65f5566e8f8b25c812 rij is ongeldig
0xf41c3a7c49349a92f73f1ae0af0a552079f24037 rij is ongeldig
0xe7e7523884887de38c915543f916445f3d48c5   etc...
etc
etc....
We uploaded the printscreen error and the completed CSV file and we hope we gave you the detailed solution what's the problem.
![2023-01-01](https://user-images.githubusercontent.com/82802122/210176552-d711f230-d604-4ae8-a85e-397d0220bf56.png)
![csv-printscreen](https://user-images.githubusercontent.com/82802122/210176744-848b3256-c88e-4faf-8c5e-b805ea5bdc9e.png)

**Comment by adamunchained** [comment]
Airdrop is limited to maximum 450 records per batch. Can you try smaller batch?

In the next release (somewhere in Jan) this limit is removed.

**Comment by priceactionbars** [comment]
Unfortunatly the same issue when we upload smaller records.
![smallerecords](https://user-images.githubusercontent.com/82802122/210184058-09eeb867-43df-4a29-b71b-9db2a4f1e701.png)

**Comment by adamunchained** [comment]
This issue has now been fixed. It was a minor UI validation bug where we only allow airdrop for >1 tokens instead of just one. It'll be deployed within production in next 10 minutes.

**Comment by adamunchained** [comment]
Please note, you still have to break it down into 500 records batches before our next release.
